'use strict';
// Standalone HTML5 prototype. No dependencies or external art.
const $=id=>document.getElementById(id), canvas=$('world'), ctx=canvas.getContext('2d');
const BIOMES=[['Пустошь','#243a3b'],['Мёртвый лес','#203d36'],['Красный карьер','#49342f'],['Ледяной перегон','#344957'],['Затопленный город','#263848'],['Последний рубеж','#3b3048']];
const RARITY=['Обычный','Редкий','Эпический','Легендарный'], COLORS=['#bdced1','#72c4ee','#c29aff','#efb76a'];
const TYPES=['Пулемёт','Тесла','Мортира'];
const fresh=()=>({version:1,coins:0,unlocked:1,cleared:[],attack:0,armor:0,parts:[{type:0,rarity:0,power:1}],equipped:0});
let save=fresh(),storageOK=true;
try{const s=JSON.parse(localStorage.getItem('last-wagon-v1'));if(s?.version===1&&Array.isArray(s.parts)&&s.parts.length&&s.parts.every(p=>Number.isInteger(p.type)&&p.type>=0&&p.type<3&&Number.isInteger(p.rarity)&&p.rarity>=0&&p.rarity<4&&Number.isFinite(p.power)&&p.power>0)){save={...fresh(),...s};for(const k of ['coins','attack','armor'])save[k]=Math.max(0,Math.floor(Number(save[k])||0));save.unlocked=Math.min(60,Math.max(1,Math.floor(Number(save.unlocked)||1)));save.cleared=Array.isArray(save.cleared)?save.cleared.filter(n=>Number.isInteger(n)&&n>0&&n<=60):[];save.equipped=Math.min(save.parts.length-1,Math.max(0,Math.floor(Number(save.equipped)||0)));}}catch{}
let mode='depot',selected=save.unlocked,chapter=Math.floor((selected-1)/10),run=null,enemies=[],shots=[],sparks=[],target=null,clock=0,last=0,spawn=0,fire=0,shake=0,sdk=null,adBusy=false,platformPaused=false,playing=false;
let W=innerWidth,H=innerHeight;
function resize(){W=innerWidth;H=innerHeight;const d=Math.min(devicePixelRatio||1,2);canvas.width=W*d;canvas.height=H*d;ctx.setTransform(d,0,0,d,0,0);}addEventListener('resize',resize);resize();
function persist(){try{localStorage.setItem('last-wagon-v1',JSON.stringify(save));}catch{storageOK=false;toast('Хранилище недоступно: прогресс сохранится только до закрытия.');}}
function toast(t){$('toast').textContent=t;$('toast').style.opacity=1;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').style.opacity=0,3300);}
function sync(){const active=mode==='battle'&&!document.hidden&&!platformPaused&&!adBusy;if(active!==playing){playing=active;try{sdk?.features?.GameplayAPI?.[active?'start':'stop']();}catch{}}}
function setMode(m){mode=m;sync();$('controls').hidden=m!=='battle';$('pause').hidden=m==='depot';}
function btn(label,fn,cls='',disabled=false){const b=document.createElement('button');b.textContent=label;b.className=cls;b.disabled=disabled;b.onclick=()=>{if(!adBusy)fn();};return b;}
function panel(title,desc){$('panel').replaceChildren();const tag=document.createElement('div');tag.className='eyebrow';tag.textContent='ПОСЛЕДНИЙ ВАГОН / ПРОТОТИП';const h=document.createElement('h1');h.textContent=title;const p=document.createElement('p');p.textContent=desc;$('panel').append(tag,h,p);return $('panel');}
function row(parent,...nodes){const d=document.createElement('div');d.className='row';d.append(...nodes);parent.append(d);}
function card(parent,title,desc,color){const d=document.createElement('div');d.className='card';const b=document.createElement('b'),s=document.createElement('small');b.textContent=title;s.textContent=desc;if(color)b.style.color=color;d.append(b,s);parent.append(d);return d;}
function depot(){setMode('depot');enemies=[];const p=panel('Довези живых.\nЗабери своё.','60 станций · 6 регионов · 3 минуты боя на станцию. На развилках выбирай улучшения или эвакуируй добычу. Поражение сохраняет только 35% собранного металла.');card(p,`${BIOMES[chapter][0]} · регион ${chapter+1}/6`,'Каждая пятая станция — босс. Пройденные станции можно играть снова.');row(p,btn('← Регион',()=>{chapter=Math.max(0,chapter-1);depot();},'',chapter===0),btn('Регион →',()=>{chapter=Math.min(5,chapter+1);depot();},'',chapter===5));const map=document.createElement('div');map.className='map';for(let i=chapter*10+1;i<=chapter*10+10;i++){map.append(btn(`${i}${i%5===0?' ◆':''}`,()=>{selected=i;depot();},`${save.cleared.includes(i)?'done ':''}${selected===i?'selected':''}`,i>save.unlocked));}p.append(map);row(p,btn(`В путь · станция ${selected}`,start,'primary'));const atk=80+save.attack*65,arm=65+save.armor*55;row(p,btn(`Урон +12% · ${atk} ⚙`,()=>upgrade('attack',atk),'',save.coins<atk),btn(`Броня +25 · ${arm} ⚙`,()=>upgrade('armor',arm),'',save.coins<arm));row(p,btn(`Арсенал · ${save.parts.length}`,inventory));card(p,'Управление','Пушки ведут огонь автоматически. Касание зомби — приоритетная цель. Электроимпульс уничтожает толпу, затем перезаряжается 18 секунд.');if(!sdk)card(p,'Локальный режим','Реклама недоступна вне Яндекс Игр. Все основные уровни и обычный лут доступны бесплатно.');}
function upgrade(k,cost){if(save.coins<cost)return;save.coins-=cost;save[k]++;persist();depot();}
function inventory(){const p=panel('Арсенал','Выбери вооружение. Пулемёт стреляет быстрее; Тесла бьёт по трём целям; мортира наносит урон по площади.');save.parts.forEach((part,i)=>{const c=card(p,`${RARITY[part.rarity]} ${TYPES[part.type]}`,`Мощность ×${part.power.toFixed(2)}`,COLORS[part.rarity]);c.append(btn(i===save.equipped?'Установлено':'Установить',()=>{save.equipped=i;persist();inventory();},'',i===save.equipped));});row(p,btn('← В депо',depot));}
function start(){const part=save.parts[save.equipped];run={station:selected,time:0,wave:1,hp:130+save.armor*25,max:130+save.armor*25,damage:(11+save.attack*1.32)*part.power,type:part.type,cooldown:0,coins:0,kills:0,rate:1,revived:false,bonus:false,settled:false,boss:false};enemies=[];shots=[];sparks=[];spawn=0;fire=0;target=null;$('panel').replaceChildren();setMode('battle');}
function checkpoint(){setMode('choice');enemies=[];const p=panel('Станция держится.',`Волна ${run.wave} из 3 пройдена. В вагоне ${run.coins} металла. Продолжишь — получишь больше, но рискуешь добычей.`);const options=[['Спаренный затвор','Урон +25%',()=>run.damage*=1.25],['Ремонтная бригада','Восстановить 40% корпуса',()=>run.hp=Math.min(run.max,run.hp+run.max*.4)],['Форсированный привод','Скорострельность +22%',()=>run.rate*=1.22]];options.forEach(([name,desc,fn])=>{const c=card(p,name,desc);c.append(btn('Выбрать и продолжить',()=>{fn();run.wave++;$('panel').replaceChildren();setMode('battle');}));});row(p,btn('Эвакуировать добычу',()=>finish('extract')));}
function loot(){const roll=Math.random(),rarity=roll<.6?0:roll<.88?1:roll<.98?2:3,type=Math.floor(Math.random()*3),power=1+rarity*.35+Math.floor((run.station-1)/10)*.15;const existing=save.parts.find(p=>p.type===type&&p.rarity===rarity);if(existing){if(existing.power<power)existing.power=power;else save.coins+=25*(rarity+1);}else save.parts.push({type,rarity,power});return `${RARITY[rarity]} ${TYPES[type]} · ×${power.toFixed(2)} (дубликат превращается в металл)`;}
function finish(result){if(run.settled)return;run.settled=true;setMode('result');const won=result==='win',gain=Math.floor(run.coins*(result==='loss'?.35:1))+(won?75+run.station*5:0);save.coins+=gain;let drop='';if(won){if(!save.cleared.includes(run.station))save.cleared.push(run.station);save.unlocked=Math.max(save.unlocked,Math.min(60,run.station+1));drop=loot();}persist();const p=panel(won?'Поезд прорвался.':result==='extract'?'Добыча спасена.':'Поезд остановлен.',`Получено ${gain} металла. Уничтожено зомби: ${run.kills}. ${won?'Следующая станция открыта.':'Улучшай поезд в депо и возвращайся.'}`);if(drop)card(p,'Сундук станции',drop);if(won){const b=btn('▶ Реклама → дополнительный сундук',()=>rewarded(()=>{run.bonus=true;const item=loot();persist();card(p,'Дополнительный сундук',item);b.disabled=true;}),'',!sdk);p.append(b);}row(p,btn('Вернуться в депо',()=>{selected=save.unlocked;chapter=Math.floor((selected-1)/10);depot();},'primary'));}
function death(){setMode('dead');const p=panel('Корпус пробит.', 'Можно завершить заезд с 35% металла или один раз восстановить поезд за просмотр рекламы.');row(p,btn('▶ Реклама → восстановить 60%',()=>rewarded(()=>{run.revived=true;run.hp=run.max*.6;enemies=[];$('panel').replaceChildren();setMode('battle');}),'primary',run.revived||!sdk),btn('Завершить',()=>finish('loss')));}
function rewarded(grant){if(adBusy)return;if(!sdk){toast('Реклама доступна только на платформе Яндекс Игр.');return;}adBusy=true;sync();let awarded=false,closed=false;const close=()=>{if(closed)return;closed=true;adBusy=false;sync();};try{sdk.adv.showRewardedVideo({callbacks:{onRewarded:()=>{if(!awarded&&!closed){awarded=true;grant();}},onClose:()=>{close();if(!awarded)toast('Просмотр не засчитан. Награда не выдана.');},onError:()=>{close();toast('Реклама недоступна. Можно продолжить без неё.');}}});}catch{close();toast('Не удалось загрузить рекламу.');}}
function pause(){if(adBusy)return;if(mode==='battle'){setMode('paused');const p=panel('Привал.','Игра приостановлена.');row(p,btn('Продолжить',resume,'primary'));}else if(mode==='paused')resume();}
function resume(){if(document.hidden||platformPaused||adBusy)return;$('panel').replaceChildren();setMode('battle');}
$('pause').onclick=pause;document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode==='battle')pause();sync();});addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();blast();}if(e.code==='Escape')pause();});
function blast(){if(mode!=='battle'||run.cooldown>0||adBusy||platformPaused)return;run.cooldown=18;shake=12;for(const e of enemies){e.hp-=run.damage*5;burst(e.x,e.y,'#82dfdf');}prune();}
$('blast').onclick=blast;canvas.addEventListener('pointerdown',e=>{if(mode!=='battle')return;let dist=65;target=null;for(const z of enemies){const d=Math.hypot(z.x-e.clientX,z.y-e.clientY);if(d<dist){target=z;dist=d;}}});
function burst(x,y,color){for(let i=0;i<9;i++){const a=Math.random()*Math.PI*2;sparks.push({x,y,vx:Math.cos(a)*80,vy:Math.sin(a)*80,life:.45,color});}}
function prune(){enemies=enemies.filter(e=>{if(e.hp>0)return true;run.coins+=e.boss?45:3;run.kills++;burst(e.x,e.y,e.boss?'#edb365':'#9ab987');return false;});}
function spawnEnemy(boss=false){const a=Math.random()*Math.PI*2,cx=W*.5,cy=H*.52,r=Math.hypot(W,H)*.6;const kind=boss?3:Math.random()<.2?2:Math.random()<.3?1:0;const scale=1+(run.station-1)*.085;const hp=(boss?180:kind===2?35:kind===1?12:20)*scale;enemies.push({x:cx+Math.cos(a)*r,y:cy+Math.sin(a)*r,hp,max:hp,kind,boss,r:boss?26:kind===2?15:11,speed:(boss?20:kind===1?44:kind===2?16:26)*(1+Math.floor((run.station-1)/10)*.05),hit:0});}
function tick(dt){run.time+=dt;run.cooldown=Math.max(0,run.cooldown-dt);spawn-=dt;fire-=dt;if(spawn<=0&&enemies.length<90){spawn=Math.max(.28,1.05-run.station*.009-run.wave*.12);spawnEnemy();}if(run.station%5===0&&run.time>=130&&!run.boss){run.boss=true;spawnEnemy(true);}const cx=W*.5,cy=H*.52;for(const e of enemies){const dx=cx-e.x,dy=cy-e.y,d=Math.hypot(dx,dy);if(d>65){e.x+=dx/d*e.speed*dt;e.y+=dy/d*e.speed*dt;}else{e.hit-=dt;if(e.hit<=0){run.hp-=e.boss?16: e.kind===2?7:4;e.hit=1;shake=4;}}}if(fire<=0&&enemies.length){fire=(run.type===0?.3:run.type===1?.65:.85)/run.rate;const ranked=[...enemies].sort((a,b)=>Math.hypot(a.x-cx,a.y-cy)-Math.hypot(b.x-cx,b.y-cy));const aim=enemies.includes(target)?target:ranked[0];let victims=run.type===1?[aim,...ranked.filter(e=>e!==aim).slice(0,2)]:run.type===2?enemies.filter(e=>Math.hypot(e.x-aim.x,e.y-aim.y)<75):[aim];for(const e of victims){e.hp-=run.damage*(run.type===2?2:1);shots.push({x:cx,y:cy,tx:e.x,ty:e.y,life:.12,color:run.type===1?'#83e1ed':'#efb76a'});}prune();}if(run.hp<=0){run.hp=0;death();return;}if(run.time>=180){if(enemies.some(e=>e.boss)){run.time=180;return;}finish('win');return;}if(run.time>=run.wave*60&&run.wave<3)checkpoint();}
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(x,y,w,h);}function circle(x,y,r,c){ctx.fillStyle=c;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();}
function draw(dt){clock+=dt;const biome=BIOMES[Math.floor(((run?.station||selected)-1)/10)];rect(0,0,W,H,biome[1]);ctx.save();if(shake){ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);shake*=.88;}const cx=W*.5,cy=H*.52;for(let i=0;i<65;i++){const x=(i*137.3)%W,y=((i*97.7+clock*(mode==='battle'?12:3))%(H+40))-20;circle(x,y,1+(i%3),'#ffffff09');}rect(cx-33,0,66,H,'#101e22');for(let y=(clock*30)%32-32;y<H;y+=32)rect(cx-46,y,92,7,'#53605a');rect(cx-30,0,4,H,'#91a0a0');rect(cx+26,0,4,H,'#91a0a0');for(let i=0;i<3;i++){const y=cy-85+i*61;rect(cx-30,y+5,66,54,'#0004');rect(cx-28,y,56,52,i===0?'#b58e53':'#557579');rect(cx-23,y+4,46,42,i===0?'#d2b478':'#6c8d89');rect(cx-20,y+9,40,4,'#ffffff25');for(let j=0;j<2;j++){rect(cx-34,y+8+j*28,7,12,'#111b20');rect(cx+27,y+8+j*28,7,12,'#111b20');}circle(cx,y+27,13,'#293b42');ctx.save();ctx.translate(cx,y+27);const aim=target&&enemies.includes(target)?target:enemies[0];ctx.rotate(aim?Math.atan2(aim.y-y-27,aim.x-cx):-.6);rect(0,-4,28,8,'#c0d0c5');ctx.restore();}rect(cx-17,cy-99,34,13,'#33474b');circle(cx-15,cy-86,4,'#ffd58b');circle(cx+15,cy-86,4,'#ffd58b');for(const e of enemies){circle(e.x+3,e.y+5,e.r,'#0004');circle(e.x,e.y,e.r,e.boss?'#a96957':e.kind===2?'#63786a':e.kind===1?'#b7ae71':'#8cab7c');circle(e.x-4,e.y-2,2,'#ecdda0');circle(e.x+4,e.y-2,2,'#ecdda0');rect(e.x-4,e.y+5,8,2,'#26382c');if(e.hp<e.max){rect(e.x-e.r,e.y-e.r-8,e.r*2,3,'#152126');rect(e.x-e.r,e.y-e.r-8,e.r*2*e.hp/e.max,3,'#edb365');}if(e===target){ctx.strokeStyle='#efb76a';ctx.lineWidth=2;ctx.beginPath();ctx.arc(e.x,e.y,e.r+7,0,7);ctx.stroke();}}for(const s of shots){ctx.strokeStyle=s.color;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(s.x,s.y);ctx.lineTo(s.tx,s.ty);ctx.stroke();s.life-=dt;}shots=shots.filter(s=>s.life>0);for(const s of sparks){s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;rect(s.x,s.y,3,3,s.color);}sparks=sparks.filter(s=>s.life>0);ctx.restore();if(mode==='battle'||mode==='paused'){$('stats').textContent=`Корпус ${Math.ceil(run.hp)}/${run.max}\nДобыча ${run.coins} ⚙`;const left=Math.max(0,180-Math.floor(run.time));$('mission').textContent=`${biome[0]} · Станция ${run.station} · Волна ${run.wave}/3 · ${Math.floor(left/60)}:${String(left%60).padStart(2,'0')}${left===0?' · Уничтожь босса':''}`;$('blast').textContent=run.cooldown>0?`Перезарядка · ${Math.ceil(run.cooldown)} с`:'⚡ Электроимпульс';$('blast').disabled=run.cooldown>0;}else $('stats').textContent=`${save.coins} ⚙ МЕТАЛЛ\nПройдено ${save.cleared.length}/60`;}
function frame(t){const dt=Math.min((t-last)/1000||0,.04);last=t;if(mode==='battle'&&!document.hidden&&!platformPaused&&!adBusy)tick(dt);draw(dt);requestAnimationFrame(frame);}depot();requestAnimationFrame(frame);
async function initSDK(){if(!window.YaGames)return;try{sdk=await YaGames.init();sdk.on?.('game_api_pause',()=>{platformPaused=true;if(mode==='battle')pause();sync();});sdk.on?.('game_api_resume',()=>{platformPaused=false;sync();});sdk.features?.LoadingAPI?.ready();if(mode==='depot')depot();sync();}catch{toast('Платформа недоступна. Игра работает с локальным сохранением.');}}
// /sdk.js only exists on Yandex. Loading failure never blocks local play.
const sdkScript=document.createElement('script');sdkScript.src='/sdk.js';sdkScript.onload=initSDK;document.head.append(sdkScript);
