(function(){
const W=4200,FLOOR=430,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const state={started:false,cam:0,kills:0,coins:0,gateOpen:false,player:null,enemies:[],particles:[],attackT:0,dashT:0};
function reset(){state.cam=0;state.kills=0;state.coins=0;state.gateOpen=false;state.attackT=0;state.dashT=0;state.player={x:120,y:FLOOR-42,w:24,h:42,vx:0,vy:0,hp:10,maxHp:10,face:1,onGround:false,inv:0};state.enemies=[];for(let i=0;i<18;i++){const type=i%4===0?'bat':i%3===0?'hound':'skeleton';state.enemies.push({type,x:500+i*180,y:type==='bat'?250+(i%3)*35:FLOOR-(type==='hound'?24:38),w:type==='bat'?30:type==='hound'?42:24,h:type==='bat'?20:type==='hound'?24:38,hp:type==='hound'?4:type==='bat'?2:3,max:type==='hound'?4:type==='bat'?2:3,t:Math.random()*100,dead:false});}}
function hit(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function burst(x,y){for(let i=0;i<9;i++)state.particles.push({x,y,vx:(Math.random()-.5)*4,vy:(Math.random()-.7)*4,t:28});}
function update(){if(!state.started)return;const p=state.player;if(p.inv>0)p.inv--;let move=(Input.held.right?1:0)-(Input.held.left?1:0);p.face=move||p.face;let sp=3.2;if(Input.consume('dash')&&state.dashT<=0)state.dashT=10;if(state.dashT>0){state.dashT--;sp=8;move=p.face}p.vx=move*sp;if(Input.consume('jump')&&p.onGround){p.vy=-9.2;p.onGround=false}p.vy+=.48;p.x=clamp(p.x+p.vx,20,W-40);p.y+=p.vy;if(p.y+p.h>=FLOOR){p.y=FLOOR-p.h;p.vy=0;p.onGround=true}if(Input.consume('attack'))state.attackT=12;if(state.attackT>0)state.attackT--;
 const atk=state.attackT>4?{x:p.face>0?p.x+p.w:p.x-52,y:p.y+6,w:52,h:30}:null;
 for(const e of state.enemies){if(e.dead)continue;e.t++;const dx=p.x-e.x;if(e.type==='bat'){e.y+=Math.sin(e.t*.08)*.7;if(Math.abs(dx)<330)e.x+=Math.sign(dx)*1.1}else if(Math.abs(dx)<310)e.x+=Math.sign(dx)*(e.type==='hound'?1.45:.65);if(atk&&hit(atk,e)){e.hp--;state.attackT=4;burst(e.x+e.w/2,e.y+e.h/2);if(e.hp<=0){e.dead=true;state.kills++;state.coins+=e.type==='hound'?3:1}}if(hit(p,e)&&p.inv===0){p.hp--;p.inv=65;p.vy=-5;p.x+=Math.sign(p.x-e.x)*28;if(p.hp<=0)reset()}}
 state.gateOpen=state.kills>=8;for(const q of state.particles){q.x+=q.vx;q.y+=q.vy;q.vy+=.18;q.t--}state.particles=state.particles.filter(q=>q.t>0);state.cam=clamp(p.x-innerWidth*.38,0,W-innerWidth);}
function draw(g,w,h){if(!state.started)return;const c=state.cam,p=state.player;g.fillStyle='#090916';g.fillRect(0,0,w,h);for(let i=0;i<12;i++){const x=i*430-c*.15;g.fillStyle=i%2?'#17132a':'#111126';g.fillRect(x,90,240,340)}g.fillStyle='#201b31';g.fillRect(0,FLOOR,w,h-FLOOR);g.fillStyle='#3c324d';for(let x=0;x<W;x+=96)g.fillRect(x-c,FLOOR,92,12);
 for(const e of state.enemies){if(e.dead)continue;const x=e.x-c;g.fillStyle=e.type==='bat'?'#8f6db0':e.type==='hound'?'#6d5561':'#b8b0a2';if(e.type==='bat'){g.beginPath();g.moveTo(x,e.y+10);g.lineTo(x+15,e.y);g.lineTo(x+30,e.y+10);g.lineTo(x+15,e.y+20);g.fill()}else g.fillRect(x,e.y,e.w,e.h);g.fillStyle='#e04d5a';g.fillRect(x,e.y-7,e.w*(e.hp/e.max),3)}
 const px=p.x-c;g.save();if(p.inv&&Math.floor(p.inv/5)%2)g.globalAlpha=.35;g.fillStyle='#d8dbe8';g.fillRect(px,p.y,24,42);g.fillStyle='#3b324e';g.fillRect(px+4,p.y+8,16,12);g.strokeStyle='#e8e0c8';g.lineWidth=4;g.beginPath();g.moveTo(px+12,p.y+23);g.lineTo(px+12+p.face*(state.attackT?54:27),p.y+(state.attackT?12:31));g.stroke();g.restore();
 const gx=W-180-c;g.fillStyle=state.gateOpen?'#6dce9b':'#513b66';g.fillRect(gx,FLOOR-120,70,120);g.fillStyle='#080812';g.fillRect(gx+12,FLOOR-94,46,94);g.fillStyle='#fff';g.font='bold 16px Arial';g.fillText('HP '+p.hp+'/'+p.maxHp,18,32);g.fillText('KILLS '+state.kills+'/8',18,54);g.fillText('COINS '+state.coins,18,76);if(!state.gateOpen&&p.x>W-650)g.fillText(I18N.lang==='ru'?'ВОРОТА: ПОБЕДИТЕ 8 ВРАГОВ':'GATE: DEFEAT 8 ENEMIES',w/2-130,60);for(const q of state.particles){g.globalAlpha=q.t/28;g.fillStyle='#e9d6a4';g.fillRect(q.x-c,q.y,3,3)}g.globalAlpha=1;}
function start(canvas){reset();state.started=true;const g=canvas.getContext('2d');let last=0;function frame(t){if(t-last>15){update();last=t}draw(g,innerWidth,innerHeight);requestAnimationFrame(frame)}requestAnimationFrame(frame)}
window.NightWorld={start,state};
})();