// Lightweight visual effects tuned for mobile HTML5.
const TAU=Math.PI*2;
export function createEffects(){return {flashes:[],trails:[],sparks:[],auras:[],bossTelegraphs:[],worldMotes:[]}}
export function flash(fx,x,y,color='#fff',r=28,life=.16){fx.flashes.push({x,y,color,r,life,max:life})}
export function trail(fx,x,y,color='#fff',r=5,life=.18){fx.trails.push({x,y,color,r,life,max:life})}
export function sparks(fx,x,y,color='#fff',count=8,power=120){for(let i=0;i<count;i++){const a=Math.random()*TAU,s=power*(.45+Math.random()*.75);fx.sparks.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,color,r:1.5+Math.random()*2.5,life:.28+.18*Math.random(),max:.46})}}
export function aura(fx,x,y,color='#fff',r=40,life=.35){fx.auras.push({x,y,color,r,life,max:life})}
export function bossTelegraph(fx,x,y,color='#fff',r=90,life=.8,kind='ring'){fx.bossTelegraphs.push({x,y,color,r,life,max:life,kind})}
export function evolutionBurst(fx,x,y,color='#ffd75e'){for(let i=0;i<4;i++)aura(fx,x,y,color,45+i*24,.55+i*.08);sparks(fx,x,y,color,22,180);flash(fx,x,y,'#fff',42,.22)}
export function updateEffects(fx,dt,player,worldId){for(const k of ['flashes','trails','auras','bossTelegraphs'])for(const e of fx[k])e.life-=dt;for(const s of fx.sparks){s.x+=s.vx*dt;s.y+=s.vy*dt;s.vx*=.96;s.vy*=.96;s.life-=dt}for(const k of ['flashes','trails','sparks','auras','bossTelegraphs'])fx[k]=fx[k].filter(e=>e.life>0);
 // Sparse world particles. Keep a hard cap for mobile.
 if(player&&fx.worldMotes.length<34&&Math.random()<dt*7){const spread=520,a=Math.random()*TAU,d=120+Math.random()*spread;fx.worldMotes.push({x:player.x+Math.cos(a)*d,y:player.y+Math.sin(a)*d,vx:(Math.random()-.5)*12,vy:worldId==='frost'?22:(worldId==='abyss'?-8:8),life:4+Math.random()*3,max:7,size:1+Math.random()*2})}
 for(const m of fx.worldMotes){m.x+=m.vx*dt;m.y+=m.vy*dt;m.life-=dt}fx.worldMotes=fx.worldMotes.filter(m=>m.life>0&&(!player||Math.hypot(m.x-player.x,m.y-player.y)<900))}
export function drawWorldMotes(c,fx,worldId){const colors={emerald:'#8ee79a',dunes:'#e8bb73',frost:'#c9f3ff',abyss:'#d596ff'},color=colors[worldId]||'#fff';c.save();for(const m of fx.worldMotes){c.globalAlpha=Math.min(.38,m.life/m.max*.4);c.fillStyle=color;c.beginPath();c.arc(m.x,m.y,m.size,0,TAU);c.fill()}c.restore()}
export function drawEffects(c,fx){c.save();for(const t of fx.trails){c.globalAlpha=Math.max(0,t.life/t.max)*.45;c.fillStyle=t.color;c.beginPath();c.arc(t.x,t.y,t.r,0,TAU);c.fill()}for(const a of fx.auras){const q=1-a.life/a.max;c.globalAlpha=(1-q)*.65;c.strokeStyle=a.color;c.lineWidth=4*(1-q)+1;c.beginPath();c.arc(a.x,a.y,a.r*(.75+.3*q),0,TAU);c.stroke()}for(const b of fx.bossTelegraphs){const q=1-b.life/b.max;c.globalAlpha=.28+.45*Math.abs(Math.sin(q*10));c.strokeStyle=b.color;c.lineWidth=3;if(b.kind==='cross'){c.beginPath();c.moveTo(b.x-b.r,b.y);c.lineTo(b.x+b.r,b.y);c.moveTo(b.x,b.y-b.r);c.lineTo(b.x,b.y+b.r);c.stroke()}else{c.beginPath();c.arc(b.x,b.y,b.r*(.88+.12*q),0,TAU);c.stroke()}}for(const s of fx.sparks){c.globalAlpha=Math.max(0,s.life/s.max);c.fillStyle=s.color;c.beginPath();c.arc(s.x,s.y,s.r,0,TAU);c.fill()}for(const f of fx.flashes){const q=1-f.life/f.max;c.globalAlpha=(1-q)*.5;c.fillStyle=f.color;c.beginPath();c.arc(f.x,f.y,f.r*(.8+.4*q),0,TAU);c.fill()}c.restore()}
