const cv=document.getElementById('game'),ctx=cv.getContext('2d');
let W=0,H=0,D=1,last=performance.now(),state='menu',t=0,kills=0,xp=0,level=1,shake=0,hitstop=0,boss=null;
const keys={},shots=[],enemies=[],fx=[],loot=[];
let p={x:0,y:0,hp:328,max:328,sp:235,a:0,fire:0,inv:0,walk:0};
const TAU=Math.PI*2,R=(a,b)=>a+Math.random()*(b-a),hash=(x,y)=>{const n=Math.sin(x*12.9898+y*78.233)*43758.5453;return n-Math.floor(n)};
const AS={rain:'assets/v12/rain.svg',drone:'assets/v12/drone.svg',hound:'assets/v12/hound.svg',crawler:'assets/v12/crawler.svg',brute:'assets/v12/brute.svg',boss:'assets/v12/boss.svg',arch:'assets/v14/ruin-arch.svg',tree:'assets/v14/crystal-tree.svg',fall:'assets/v14/waterfall.svg',altar:'assets/v14/altar.svg',bridge:'assets/v18/stone-bridge.svg',wall:'assets/v18/ruined-wall.svg',flowers:'assets/v18/flower-cluster.svg'};
const IMG={};let assetsReady=0;for(const [k,u] of Object.entries(AS)){const im=new Image();im.onload=()=>assetsReady++;im.onerror=()=>assetsReady++;im.src=u;IMG[k]=im}
function resize(){D=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;cv.width=W*D;cv.height=H*D;cv.style.width=W+'px';cv.style.height=H+'px';ctx.setTransform(D,0,0,D,0,0)}addEventListener('resize',resize);resize();
const landmarks=[{x:-780,y:-420,k:'fall',w:330,h:290},{x:460,y:-430,k:'arch',w:250,h:250},{x:-250,y:500,k:'tree',w:230,h:255},{x:650,y:410,k:'altar',w:220,h:200},{x:40,y:-760,k:'wall',w:240,h:190},{x:-900,y:230,k:'tree',w:205,h:235},{x:940,y:40,k:'fall',w:300,h:260},{x:70,y:455,k:'bridge',w:300,h:175},{x:780,y:-720,k:'wall',w:220,h:175},{x:-1040,y:-80,k:'arch',w:210,h:210}];
const deco=[];for(let i=0;i<180;i++){let a=i*2.399,d=180+(i%20)*90;deco.push({x:Math.cos(a)*d+Math.sin(i*3.1)*120,y:Math.sin(a)*d+Math.cos(i*1.7)*120,k:i%11===0?'flowers':i%7===0?'crystal':i%4===0?'stone':'grass',s:.65+(i%8)*.08})}
function start(){state='play';document.getElementById('menu').classList.add('hidden');document.getElementById('hud').classList.remove('hidden');p={x:0,y:0,hp:328,max:328,sp:235,a:0,fire:0,inv:0,walk:0};enemies.length=shots.length=fx.length=loot.length=0;t=kills=xp=0;level=1;boss=null;for(let i=0;i<12;i++)spawn()}
function spawn(type){let a=R(0,TAU),d=R(520,880),k=type||(['hound','crawler','brute'][Math.random()*3|0]);let hp=k==='brute'?180:k==='crawler'?80:105;enemies.push({x:p.x+Math.cos(a)*d,y:p.y+Math.sin(a)*d,k,hp,max:hp,sp:k==='brute'?50:k==='crawler'?98:78,r:k==='brute'?34:k==='crawler'?25:27,hit:0,phase:R(0,TAU)})}
function spawnBoss(){boss={x:p.x+560,y:p.y-80,hp:2800,max:2800,r:82,phase:0,cd:1.8}}
function burst(x,y,c,n=10){for(let i=0;i<n;i++){let a=R(0,TAU),s=R(40,280);fx.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,l:R(.25,.68),m:.68,c,r:R(2,7)})}}
function nearest(){return [...enemies,boss].filter(Boolean).sort((a,b)=>(a.x-p.x)**2+(a.y-p.y)**2-((b.x-p.x)**2+(b.y-p.y)**2))[0]}
function fire(){let target=nearest();if(!target)return;let a=Math.atan2(target.y-p.y,target.x-p.x);p.a=a;shots.push({x:p.x+Math.cos(a)*38,y:p.y+Math.sin(a)*38,vx:Math.cos(a)*760,vy:Math.sin(a)*760,l:1.25,a});burst(p.x+Math.cos(a)*48,p.y+Math.sin(a)*48,'#ffb52e',7)}
function damage(e,d){e.hp-=d;e.hit=.11;shake=Math.max(shake,7);hitstop=.032;burst(e.x,e.y,'#76edff',9);if(e.hp<=0){if(e===boss){burst(e.x,e.y,'#b261ff',65);boss=null;loot.push({x:e.x,y:e.y,k:'chest'})}else{enemies.splice(enemies.indexOf(e),1);kills++;xp+=10;loot.push({x:e.x,y:e.y,k:'crystal'});if(enemies.length<16)spawn()}}}
function update(dt){if(state!=='play')return;if(hitstop>0){hitstop-=dt;return}t+=dt;let dx=(keys.d||keys.ArrowRight?1:0)-(keys.a||keys.ArrowLeft?1:0),dy=(keys.s||keys.ArrowDown?1:0)-(keys.w||keys.ArrowUp?1:0),m=Math.hypot(dx,dy)||1;p.x+=dx/m*p.sp*dt;p.y+=dy/m*p.sp*dt;if(dx||dy){p.a=Math.atan2(dy,dx);p.walk+=dt*9}p.fire-=dt;if(p.fire<=0){fire();p.fire=.26}if(!boss&&t>32)spawnBoss();if(enemies.length<14&&Math.random()<dt*3.4)spawn();for(const e of enemies){let a=Math.atan2(p.y-e.y,p.x-e.x),d=Math.hypot(p.x-e.x,p.y-e.y);e.x+=Math.cos(a)*e.sp*dt;e.y+=Math.sin(a)*e.sp*dt;e.phase+=dt*4.5;e.hit-=dt;if(d<e.r+19&&p.inv<=0){p.hp-=e.k==='brute'?22:10;p.inv=.48;shake=11;burst(p.x,p.y,'#ff554f',18)}}if(boss){let e=boss,a=Math.atan2(p.y-e.y,p.x-e.x),d=Math.hypot(p.x-e.x,p.y-e.y);e.phase+=dt;e.cd-=dt;e.x+=Math.cos(a)*32*dt;e.y+=Math.sin(a)*32*dt;if(d<100&&p.inv<=0){p.hp-=30;p.inv=.7;shake=15}if(e.cd<0){e.cd=2.15;burst(e.x,e.y,'#a85cff',18);for(let q=0;q<14;q++){let aa=q/14*TAU;shots.push({x:e.x,y:e.y,vx:Math.cos(aa)*200,vy:Math.sin(aa)*200,l:3.2,enemy:true,a:aa})}}}p.inv-=dt;for(const s of [...shots]){s.x+=s.vx*dt;s.y+=s.vy*dt;s.l-=dt;if(s.enemy){if(Math.hypot(s.x-p.x,s.y-p.y)<20&&p.inv<=0){p.hp-=12;p.inv=.4;s.l=0;burst(p.x,p.y,'#ff4f80',11)}}else{for(const e of [...enemies,boss].filter(Boolean))if(Math.hypot(s.x-e.x,s.y-e.y)<e.r+10){damage(e,46);s.l=0;break}}if(s.l<=0)shots.splice(shots.indexOf(s),1)}for(const f of fx){f.x+=f.vx*dt;f.y+=f.vy*dt;f.vx*=.95;f.vy*=.95;f.l-=dt}for(let i=fx.length-1;i>=0;i--)if(fx[i].l<=0)fx.splice(i,1);if(xp>=level*36){xp=0;level++;burst(p.x,p.y,'#ffe45b',40)}if(p.hp<=0)start()}
function shadow(x,y,rx,ry){ctx.fillStyle='#03101888';ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,TAU);ctx.fill()}
function crystal(x,y,s=1,c='#8259ff'){shadow(x,y+18*s,20*s,7*s);ctx.fillStyle=c;ctx.beginPath();ctx.moveTo(x,y-28*s);ctx.lineTo(x+15*s,y+5*s);ctx.lineTo(x,y+22*s);ctx.lineTo(x-14*s,y+5*s);ctx.closePath();ctx.fill();ctx.fillStyle='#77efff';ctx.beginPath();ctx.moveTo(x,y-23*s);ctx.lineTo(x+5*s,y+2*s);ctx.lineTo(x,y+15*s);ctx.closePath();ctx.fill()}
function drawSprite(im,x,y,w,h,rot=0,flip=false,alpha=1){if(!im.complete)return;ctx.save();ctx.globalAlpha=alpha;ctx.translate(x,y);ctx.rotate(rot);ctx.scale(flip?-1:1,1);ctx.drawImage(im,-w/2,-h/2,w,h);ctx.restore();ctx.globalAlpha=1}
function drawHero(x,y){shadow(x,y+44,33,11);let bob=Math.sin(p.walk*2)*2,flip=Math.cos(p.a)<0;drawSprite(IMG.rain,x,y-26+bob,112,138,0,flip,p.inv>0&&Math.sin(t*45)>0?.45:1);let dx=Math.cos(t*2.2)*52,dy=Math.sin(t*2.2)*31;shadow(x+dx,y+dy+8,18,6);drawSprite(IMG.drone,x+dx,y+dy-8,70,56,Math.sin(t*3)*.05,false,1)}
function drawEnemy(e,x,y){shadow(x,y+e.r*.72,e.r*1.05,e.r*.38);let sz=e.k==='brute'?[122,110]:e.k==='crawler'?[100,82]:[112,76],flip=e.x<p.x,bob=Math.sin(e.phase*2)*3;drawSprite(IMG[e.k],x,y-14+bob,sz[0],sz[1],0,flip,e.hit>0?.55:1)}
function drawBoss(e,x,y){shadow(x,y+86,96,25);let pulse=1+Math.sin(e.phase*3)*.025;drawSprite(IMG.boss,x,y-50,220*pulse,238*pulse,0,e.x<p.x,1);ctx.strokeStyle=e.cd<.55?'#ff77d7cc':'#7feeff88';ctx.lineWidth=e.cd<.55?7:4;ctx.beginPath();ctx.arc(x,y-47,54+Math.sin(e.phase*4)*8,0,TAU);ctx.stroke()}
function drawGround(ox,oy){ctx.fillStyle='#14362f';ctx.fillRect(0,0,W,H);const g=128;for(let yy=Math.floor((p.y-H/2)/g)*g;yy<p.y+H/2+g;yy+=g)for(let xx=Math.floor((p.x-W/2)/g)*g;xx<p.x+W/2+g;xx+=g){const n=hash(xx/g,yy/g),x=xx+ox,y=yy+oy;ctx.fillStyle=n>.67?'#244b3b':n<.25?'#0f3033':'#193d32';ctx.beginPath();ctx.ellipse(x+64+(n-.5)*28,y+64+(hash(yy,xx)-.5)*24,92,72,n*TAU,0,TAU);ctx.fill();if(n>.45){ctx.strokeStyle='#4f77555c';ctx.lineWidth=3;for(let i=0;i<4;i++){let hx=hash(xx+i,yy)*g,hy=hash(yy+i,xx)*g;ctx.beginPath();ctx.moveTo(x+hx,y+hy+9);ctx.quadraticCurveTo(x+hx-3,y+hy,x+hx+2,y+hy-10);ctx.stroke()}}}
ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle='#4c514b';ctx.lineWidth=118;ctx.beginPath();ctx.moveTo(-340+ox,-1000+oy);ctx.bezierCurveTo(-480+ox,-350+oy,160+ox,-130+oy,900+ox,410+oy);ctx.stroke();ctx.strokeStyle='#858b7b';ctx.lineWidth=82;ctx.stroke();ctx.setLineDash([22,16]);ctx.strokeStyle='#b7bea8aa';ctx.lineWidth=4;ctx.stroke();ctx.setLineDash([]);
ctx.strokeStyle='#153f4f';ctx.lineWidth=176;ctx.beginPath();ctx.moveTo(-1300+ox,520+oy);ctx.bezierCurveTo(-720+ox,260+oy,-230+ox,730+oy,640+ox,520+oy);ctx.stroke();ctx.strokeStyle='#248ea6';ctx.lineWidth=134;ctx.stroke();ctx.strokeStyle='#55d6e0';ctx.lineWidth=90;ctx.stroke();ctx.strokeStyle='#d5ffff77';ctx.lineWidth=7;ctx.stroke();for(let i=0;i<14;i++){let x=-1180+i*140+ox,y=520+Math.sin(i*.8)*80+oy;ctx.strokeStyle='#a9ffff55';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,20+hash(i,4)*25,0,TAU);ctx.stroke()}}
function drawDeco(ox,oy){for(const q of deco){let x=q.x+ox,y=q.y+oy;if(x<-100||y<-100||x>W+100||y>H+100)continue;if(q.k==='crystal')crystal(x,y,q.s);else if(q.k==='flowers')drawSprite(IMG.flowers,x,y,92*q.s,76*q.s,Math.sin(t+q.x*.01)*.02);else if(q.k==='stone'){shadow(x,y+9,24*q.s,8*q.s);ctx.fillStyle='#4f6262';ctx.beginPath();ctx.ellipse(x,y,23*q.s,15*q.s,-.2,0,TAU);ctx.fill();ctx.fillStyle='#75888a';ctx.beginPath();ctx.ellipse(x-5*q.s,y-4*q.s,10*q.s,5*q.s,-.2,0,TAU);ctx.fill()}else{ctx.strokeStyle='#5f9a63';ctx.lineWidth=3;for(let i=-2;i<=2;i++){ctx.beginPath();ctx.moveTo(x+i*3,y+10);ctx.quadraticCurveTo(x+i*4+Math.sin(t*2+q.x)*3,y,x+i*5,y-8-(i%2)*4);ctx.stroke()}}}}
function drawLandmarks(ox,oy){for(const q of [...landmarks].sort((a,b)=>a.y-b.y)){let x=q.x+ox,y=q.y+oy;if(x<-260||y<-260||x>W+260||y>H+260)continue;drawSprite(IMG[q.k],x,y,q.w,q.h)}}
function world(){let ox=W/2-p.x,oy=H/2-p.y,sx=shake?R(-shake,shake):0,sy=shake?R(-shake,shake):0;shake*=.84;ctx.save();ctx.translate(sx,sy);drawGround(ox,oy);drawDeco(ox,oy);drawLandmarks(ox,oy);for(const l of loot){let x=l.x+ox,y=l.y+oy;if(l.k==='crystal')crystal(x,y,.5,'#42dfff');else{shadow(x,y+15,28,8);ctx.fillStyle='#673319';ctx.fillRect(x-22,y-16,44,30);ctx.fillStyle='#ffc53b';ctx.fillRect(x-22,y-5,44,8);ctx.fillRect(x-3,y-16,7,30)}}for(const e of enemies)drawEnemy(e,e.x+ox,e.y+oy);if(boss)drawBoss(boss,boss.x+ox,boss.y+oy);for(const s of shots){let x=s.x+ox,y=s.y+oy;ctx.save();ctx.translate(x,y);ctx.rotate(s.a);ctx.shadowBlur=16;ctx.shadowColor=s.enemy?'#ff3f9a':'#ffbd3c';ctx.fillStyle=s.enemy?'#ff3f9a':'#ffc14a';ctx.fillRect(-9,-4,25,8);ctx.fillStyle=s.enemy?'#d7a0ff':'#fff5b2';ctx.fillRect(10,-2,18,4);ctx.restore()}ctx.shadowBlur=0;for(const f of fx){ctx.globalAlpha=Math.max(0,f.l/f.m);ctx.fillStyle=f.c;ctx.beginPath();ctx.arc(f.x+ox,f.y+oy,f.r,0,TAU);ctx.fill()}ctx.globalAlpha=1;drawHero(W/2,H/2);ctx.restore()}
function hud(){document.getElementById('hpText').textContent=`❤ ${Math.max(0,p.hp|0)}/${p.max}`;document.getElementById('lvlText').textContent=`УР. ${level}`;document.getElementById('timeText').textContent=`${String(t/60|0).padStart(2,'0')}:${String(t%60|0).padStart(2,'0')}`;document.getElementById('coinText').textContent=`☠ ${kills}`;document.getElementById('xpFill').style.width=Math.min(100,xp/(level*36)*100)+'%';if(boss){ctx.fillStyle='#090b12e8';ctx.fillRect(W*.16,70,W*.68,48);ctx.fillStyle='#421426';ctx.fillRect(W*.18,98,W*.64,10);ctx.fillStyle='#ff3659';ctx.fillRect(W*.18,98,W*.64*(boss.hp/boss.max),10);ctx.fillStyle='#fff';ctx.font='bold 18px system-ui';ctx.textAlign='center';ctx.fillText('КРИСТАЛЬНЫЙ СТРАЖ',W/2,91)}ctx.fillStyle='#d6f8ffbb';ctx.font='700 12px system-ui';ctx.textAlign='left';ctx.fillText('МИР 1/5 · КРИСТАЛЬНЫЕ РУИНЫ',18,H-22)}
function loading(){ctx.fillStyle='#07131b';ctx.fillRect(0,0,W,H);ctx.fillStyle='#dffbff';ctx.font='700 24px system-ui';ctx.textAlign='center';ctx.fillText(`Загрузка мира ${assetsReady}/${Object.keys(AS).length}`,W/2,H/2)}
function frame(now){let dt=Math.min(.033,(now-last)/1000);last=now;if(assetsReady<Object.keys(AS).length){loading();requestAnimationFrame(frame);return}update(dt);ctx.clearRect(0,0,W,H);if(state==='play'){world();hud()}requestAnimationFrame(frame)}requestAnimationFrame(frame);
addEventListener('keydown',e=>{keys[e.key]=true;if(e.key==='Escape'&&state==='play')state='pause';else if(e.key==='Escape'&&state==='pause')state='play'});addEventListener('keyup',e=>keys[e.key]=false);document.getElementById('playBtn').onclick=start;document.getElementById('pauseBtn').onclick=()=>state=state==='play'?'pause':'play';