import {YandexBridge} from './yandex.js';
const $=id=>document.getElementById(id),c=$('game'),x=c.getContext('2d'),b=new YandexBridge();await b.init();
let W=0,H=0,D=1,last=performance.now();function rs(){D=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;c.width=W*D;c.height=H*D;c.style.width=W+'px';c.style.height=H+'px';x.setTransform(D,0,0,D,0,0)}addEventListener('resize',rs);rs();
const RU=(b.lang||'ru').startsWith('ru');let lang=RU?'ru':'en',tr=(ru,en)=>lang==='ru'?ru:en;
const heroes=[
{id:'rain',ru:'Капитан Рейн',en:'Captain Rain',hp:150,sp:188,d:1,u:0,col:'#49b8ff',w:'gun',desc:'Плазмобластер'},
{id:'luna',ru:'Луна',en:'Luna',hp:110,sp:196,d:1.08,u:0,col:'#b66cff',w:'orbit',desc:'Орбитальные клинки'},
{id:'ice',ru:'Айс',en:'Ice',hp:125,sp:205,d:1.02,u:2,col:'#55e4ff',w:'frost',desc:'Крио-волна'},
{id:'chaos',ru:'Хаос',en:'Chaos',hp:140,sp:190,d:1.16,u:5,col:'#ff704d',w:'nova',desc:'Солнечная нова'},
{id:'shade',ru:'Тень',en:'Shade',hp:100,sp:232,d:1.1,u:8,col:'#7f67ff',w:'knife',desc:'Теневые ножи'}];
const pets=[
{id:'orb',i:'🤖',ru:'Орб',en:'Orb',u:0,txt:'+35 магнит',a:p=>p.pick+=35},{id:'fox',i:'🦊',ru:'Лис',en:'Fox',u:0,txt:'+10% скорость',a:p=>p.sp*=1.1},{id:'owl',i:'🦉',ru:'Сова',en:'Owl',u:3,txt:'+15% опыта',a:p=>p.xpb*=1.15},{id:'dragon',i:'🐉',ru:'Дракон',en:'Dragon',u:6,txt:'+12% урон',a:p=>p.d*=1.12},{id:'wolf',i:'🐺',ru:'Волк',en:'Wolf',u:9,txt:'+12% атака',a:p=>p.h*=1.12}];
const WD={gun:{i:'🔫',ru:'Плазмобластер',en:'Plasma Blaster',r:.55,col:'#68e9ff'},knife:{i:'🗡️',ru:'Теневые ножи',en:'Shadow Knives',r:.42,col:'#c9b7ff'},frost:{i:'❄️',ru:'Крио-волна',en:'Cryo Wave',r:1.8,col:'#79f6ff'},nova:{i:'☄️',ru:'Солнечная нова',en:'Solar Nova',r:2.4,col:'#ff9f55'},orbit:{i:'🌀',ru:'Орбитальные клинки',en:'Orbit Blades',r:.1,col:'#da8cff'},laser:{i:'⚡',ru:'Лучевой жезл',en:'Arc Wand',r:1.25,col:'#ffe66f'},mine:{i:'💣',ru:'Кристаллические мины',en:'Crystal Mines',r:2.7,col:'#5dff9e'},boom:{i:'🪃',ru:'Фотонный бумеранг',en:'Photon Boomerang',r:1.6,col:'#ff73d7'}};
const worlds=[{n:'Кристальные руины',bg:'#071827',g:'#0c2434',grid:'#17394a',gl:'#4ae4ff'},{n:'Ксеноджунгли',bg:'#07170f',g:'#0d2517',grid:'#173b25',gl:'#6bff8f'},{n:'Красная кузня',bg:'#210c09',g:'#32110d',grid:'#542319',gl:'#ff794f'}];
const DEF={best:0,runs:0,kills:0,currency:0,wins:0,meta:{power:0,health:0,speed:0,fortune:0},settings:{muted:false}};let save=Object.assign({},DEF,await b.load()||{});save.meta=Object.assign({},DEF.meta,save.meta||{});save.settings=Object.assign({},DEF.settings,save.settings||{});const persist=()=>b.save(save),fmt=s=>`${String(s/60|0).padStart(2,'0')}:${String(s%60|0).padStart(2,'0')}`;
let st='menu',hpick=null,ppick=null,p=null,en=[],shots=[],gems=[],fx=[],haz=[],weps={},keys={},joy={on:false,id:0,x:0,y:0,dx:0,dy:0};let time=0,spawn=0,bossN=0,kills=0,lvl=1,xp=0,need=24,coins=0,paused=false,rev=false,shake=0,audio=null;
function snd(f=440,d=.04,v=.01){if(save.settings.muted)return;try{audio??=new AudioContext();audio.resume();let o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;g.gain.value=v;o.connect(g);g.connect(audio.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.stop(audio.currentTime+d)}catch{}}
function show(id){['menu','select','upgrade','pause','revive','result','meta','help'].forEach(q=>$(q).classList.toggle('hidden',q!==id));$('hud').classList.toggle('hidden',!['play','upgrade','pause','revive'].includes(id));if(id!=='play')$('joystick').classList.add('hidden')}
function menu(){st='menu';paused=false;b.gameplayStop();show('menu');$('bestText').textContent=`${tr('Лучшее время','Best')}: ${fmt(save.best)} · ${tr('Забегов','Runs')}: ${save.runs}`;$('walletText').textContent=`✦ ${tr('Кристаллы','Crystals')}: ${save.currency}`}
function hi(h){return `<div style="width:60px;height:60px;border-radius:50%;margin:auto;background:radial-gradient(circle at 35% 30%,#fff,${h.col} 35%,#102237 37%);box-shadow:0 0 18px ${h.col}88"><div style="margin:auto;transform:translateY(21px);width:29px;height:15px;border-radius:50%;background:#08121c;border:3px solid #dff7ff"></div></div>`}
function cards(){let card=(o,type)=>`<div class="card ${save.runs>=o.u?'':'locked'}" data-${type}="${o.id}">${type==='hero'?hi(o):`<div class="icon">${o.i}</div>`}<b>${o[lang]}</b><small>${save.runs>=o.u?(type==='hero'?o.desc:o.txt):tr(`Откроется после ${o.u} забегов`,`Unlock after ${o.u} runs`)}</small></div>`;$('heroes').innerHTML=heroes.map(v=>card(v,'hero')).join('');$('pets').innerHTML=pets.map(v=>card(v,'pet')).join('');document.querySelectorAll('[data-hero]').forEach(e=>e.onclick=()=>{let h=heroes.find(v=>v.id===e.dataset.hero);if(save.runs<h.u)return;hpick=h.id;document.querySelectorAll('[data-hero]').forEach(q=>q.classList.toggle('selected',q===e));ready()});document.querySelectorAll('[data-pet]').forEach(e=>e.onclick=()=>{let h=pets.find(v=>v.id===e.dataset.pet);if(save.runs<h.u)return;ppick=h.id;document.querySelectorAll('[data-pet]').forEach(q=>q.classList.toggle('selected',q===e));ready()})}
function ready(){$('startBtn').disabled=!(hpick&&ppick)}
function meta(){if(!$('metaGrid'))return;$('metaWallet').textContent=`✦ ${tr('Кристаллы','Crystals')}: ${save.currency}`;let M=[['power','⚔️','Сила',8],['health','❤','Здоровье',8],['speed','⚡','Скорость',6],['fortune','✦','Удача',6]];$('metaGrid').innerHTML=M.map(m=>{let l=save.meta[m[0]]||0,co=30+l*40;return `<div class="metaCard"><b>${m[1]} ${m[2]} · ${l}/${m[3]}</b><button data-m="${m[0]}" ${l>=m[3]||save.currency<co?'disabled':''}>${l>=m[3]?'MAX':`✦ ${co}`}</button></div>`}).join('');document.querySelectorAll('[data-m]').forEach(e=>e.onclick=()=>{let id=e.dataset.m,l=save.meta[id]||0,co=30+l*40;if(save.currency<co)return;save.currency-=co;save.meta[id]=l+1;persist();meta()})}
function ui(){let map=[['playBtn','ИГРАТЬ','PLAY'],['metaBtn','УЛУЧШЕНИЯ','UPGRADES'],['howBtn','КАК ИГРАТЬ','HOW TO PLAY'],['heroTitle','Выбери героя','Choose a hero'],['petTitle','Выбери питомца','Choose a pet'],['startBtn','В БОЙ','START'],['backBtn','НАЗАД','BACK'],['upgradeTitle','Новый уровень','Level up'],['upgradeHint','Выбери оружие или усиление','Choose a weapon or upgrade'],['pauseTitle','Пауза','Paused'],['resumeBtn','ПРОДОЛЖИТЬ','RESUME'],['quitBtn','В МЕНЮ','MENU'],['reviveBtn','ВОСКРЕСНУТЬ','REVIVE'],['skipReviveBtn','ЗАКОНЧИТЬ ЗАБЕГ','END RUN'],['retryBtn','ЕЩЁ РАЗ','RUN AGAIN'],['resultMenuBtn','В МЕНЮ','MENU'],['metaTitle','Постоянные улучшения','Permanent upgrades'],['metaBackBtn','НАЗАД','BACK'],['helpTitle','Как играть','How to play'],['helpBackBtn','ПОНЯТНО','GOT IT']];map.forEach(v=>$(v[0]).textContent=tr(v[1],v[2]));$('helpBody').innerHTML=`<p>${tr('Survivor-roguelite в духе Vampire Survivors: двигайся, а оружие атакует автоматически. Каждую минуту волны плотнее. Собирай опыт, открывай до 6 оружий и прокачивай каждое до 8 уровня. Босс каждые 2 минуты. Выживи 10 минут.','Move while weapons attack automatically. Waves get denser every minute. Collect XP, carry up to 6 weapons and level each to 8. Boss every 2 minutes. Survive 10 minutes.')}</p>`;cards();meta();if(st==='menu')menu()}
function addW(id){weps[id]?weps[id].lv=Math.min(8,weps[id].lv+1):weps[id]={id,lv:1,cd:.1,spin:0};strip()}
function start(){let h=heroes.find(v=>v.id===hpick)||heroes[0],pet=pets.find(v=>v.id===ppick)||pets[0];p={x:0,y:0,r:19,max:h.hp+save.meta.health*9,hp:h.hp+save.meta.health*9,sp:h.sp*(1+save.meta.speed*.025),d:h.d*(1+save.meta.power*.06),h:1+save.meta.fortune*.02,pick:110,xpb:1,face:0,hero:h,pet:pet.id};pet.a(p);en=[];shots=[];gems=[];fx=[];haz=[];weps={};time=0;spawn=.1;bossN=0;kills=0;lvl=1;xp=0;need=24;coins=0;paused=false;rev=false;addW(h.w);st='play';show('play');b.gameplayStart();last=performance.now()}
function finish(win=false,quit=false){if(!p)return menu();paused=true;st='result';b.gameplayStop();save.best=Math.max(save.best,time);save.runs++;save.kills+=kills;save.currency+=coins;save.wins+=win?1:0;persist();b.submitScore('arena_survival',time*100+kills*2|0);if(quit)return menu();$('resultTitle').textContent=win?tr('Победа!','Victory!'):tr('Забег окончен','Run over');$('resultStats').innerHTML=`<p>${tr('Время','Time')}: <b>${fmt(time)}</b></p><p>${tr('Уровень','Level')}: <b>${lvl}</b></p><p>${tr('Врагов','Enemies')}: <b>${kills}</b></p><p>${tr('Оружия','Weapons')}: <b>${Object.keys(weps).length}</b></p><p>${tr('Кристаллов','Crystals')}: <b>✦ ${coins}</b></p>`;show('result')}
function wave(){return 1+Math.floor(time/60)}function wi(){return Math.min(2,Math.floor(time/200))}
function spawnE(boss=false){let a=Math.random()*6.283,d=Math.max(W,H)*.72+160,s=1+time/240,r=Math.random(),type=r<.44?'scout':r<.73?'runner':r<.91?'mech':'elite';if(wave()>4&&Math.random()<.13)type='swarm';let e={x:p.x+Math.cos(a)*d,y:p.y+Math.sin(a)*d,t:type,r:20,hp:34*s,max:34*s,sp:70+Math.random()*22,dmg:10+wave()*.5,hit:0};if(type==='runner'){e.r=17;e.hp=e.max=26*s;e.sp=112+wave()*2}if(type==='swarm'){e.r=13;e.hp=e.max=18*s;e.sp=138+wave()*2}if(type==='mech'){e.r=28;e.hp=e.max=95*s;e.sp=49+wave()}if(type==='elite'){e.r=33;e.hp=e.max=150*s;e.sp=56+wave();e.dmg=20+wave()}if(boss){e.t='boss';e.r=64;e.hp=e.max=1400*(1+bossN*.45);e.sp=42+bossN*2;e.dmg=34+bossN*4}en.push(e)}
function near(range=680,from=p){let q=null,bd=range*range;for(let e of en){let dx=e.x-from.x,dy=e.y-from.y,d=dx*dx+dy*dy;if(d<bd){bd=d;q=e}}return q}
function burst(px,py,col,n=8){for(let i=0;i<n;i++){let a=Math.random()*6.28,s=60+Math.random()*180;fx.push({x:px,y:py,vx:Math.cos(a)*s,vy:Math.sin(a)*s,l:.4,m:.4,col})}}
function hit(e,d,col){e.hp-=d;e.hit=.08;burst(e.x,e.y,col,2);if(e.hp<=0)kill(e)}function kill(e){let i=en.indexOf(e);if(i<0)return;en.splice(i,1);kills++;if(Math.random()<.13||e.t==='boss')coins+=e.t==='boss'?12:1;gems.push({x:e.x,y:e.y,r:e.t==='boss'?12:7,v:e.t==='boss'?38:e.t==='elite'?12:6});burst(e.x,e.y,e.t==='boss'?'#ff9b55':'#71ecff',e.t==='boss'?28:10)}
function fire(w){let d=WD[w.id],lv=w.lv,mul=p.d;if(w.id==='gun'||w.id==='knife'){let e=near();if(!e)return;let a=Math.atan2(e.y-p.y,e.x-p.x),n=w.id==='knife'?Math.min(5,1+Math.floor(lv/2)):Math.min(4,1+Math.floor((lv-1)/3));for(let i=0;i<n;i++){let aa=a+(i-(n-1)/2)*(w.id==='knife'?.16:.09),sp=w.id==='knife'?760:680;shots.push({k:w.id,x:p.x,y:p.y,vx:Math.cos(aa)*sp,vy:Math.sin(aa)*sp,r:6,dmg:(w.id==='knife'?16:24)*mul*(1+lv*.13),l:1.15,p:w.id==='knife'?Math.floor(lv/3):0,col:d.col})}}
else if(w.id==='frost'||w.id==='nova'){let rad=(w.id==='frost'?115:95)+lv*(w.id==='frost'?15:18),dmg=(w.id==='frost'?30:42)+lv*(w.id==='frost'?9:12);haz.push({k:'ring',x:p.x,y:p.y,r:10,max:rad,l:.45,m:.45,col:d.col});for(let e of [...en])if(Math.hypot(e.x-p.x,e.y-p.y)<rad+e.r)hit(e,dmg*mul,d.col);shake=6}
else if(w.id==='laser'){let e=near(760);if(!e)return;haz.push({k:'beam',x:p.x,y:p.y,x2:e.x,y2:e.y,l:.16,m:.16,col:d.col});hit(e,(48+lv*14)*mul,d.col)}
else if(w.id==='mine'){let a=Math.random()*6.28,di=40+Math.random()*90;haz.push({k:'mine',x:p.x+Math.cos(a)*di,y:p.y+Math.sin(a)*di,r:9,l:8,m:8,dmg:(55+lv*14)*mul,rad:75+lv*8,col:d.col})}
else if(w.id==='boom'){let e=near();if(!e)return;let a=Math.atan2(e.y-p.y,e.x-p.x);shots.push({k:'boom',x:p.x,y:p.y,vx:Math.cos(a)*510,vy:Math.sin(a)*510,r:11,dmg:(34+lv*10)*mul,l:1.7,p:5+lv,col:d.col,age:0})}}
function weapons(dt){for(let w of Object.values(weps)){w.cd-=dt;w.spin+=dt*(1.8+w.lv*.08);if(w.id==='orbit'){let n=Math.min(6,1+Math.floor((w.lv+1)/2)),rad=54+w.lv*4;for(let i=0;i<n;i++){let a=w.spin+i*6.283/n,px=p.x+Math.cos(a)*rad,py=p.y+Math.sin(a)*rad;for(let e of en)if(!e.oh||e.oh<time-.18)if(Math.hypot(e.x-px,e.y-py)<e.r+11){e.oh=time;hit(e,(18+w.lv*6)*p.d,WD.orbit.col)}}continue}if(w.cd<=0){fire(w);w.cd=WD[w.id].r/(p.h*(1+w.lv*.055))}}}
function levelup(){lvl++;xp-=need;need=Math.floor(need*1.24+8);paused=true;st='upgrade';b.gameplayStop();show('upgrade');let a=[];for(let w of Object.values(weps))if(w.lv<8)a.push({t:`${WD[w.id].i} ${WD[w.id][lang]} · ${w.lv+1}/8`,s:tr('Усилить оружие','Upgrade weapon'),f:()=>addW(w.id)});if(Object.keys(weps).length<6)for(let id in WD)if(!weps[id])a.push({t:`${WD[id].i} ${WD[id][lang]}`,s:tr('Новое оружие','New weapon'),f:()=>addW(id)});a.push({t:'❤ '+tr('Здоровье +25','Health +25'),s:tr('Лечение и максимум HP','Heal and max HP'),f:()=>{p.max+=25;p.hp=Math.min(p.max,p.hp+25)}});a.push({t:'⚡ '+tr('Скорость атак +10%','Attack speed +10%'),s:tr('Все оружия быстрее','All weapons faster'),f:()=>p.h*=1.1});a.push({t:'🧲 '+tr('Магнит +40','Pickup +40'),s:tr('Больше радиус опыта','Larger XP radius'),f:()=>p.pick+=40});a.sort(()=>Math.random()-.5);$('upgradeCards').innerHTML='';for(let o of a.slice(0,3)){let q=document.createElement('button');q.className='upgradeCard';q.innerHTML=`<b>${o.t}</b><span>${o.s}</span>`;q.onclick=()=>{o.f();paused=false;st='play';show('play');b.gameplayStart();last=performance.now();strip();snd(760)};$('upgradeCards').appendChild(q)}}
function strip(){$('weaponStrip').innerHTML=Object.values(weps).map(w=>`<span class="weaponPill">${WD[w.id].i}<b>${w.lv}</b></span>`).join('')}
function update(dt){if(st!=='play'||paused||!p)return;time+=dt;if(time>=600)return finish(true);let mx=(keys.ArrowRight||keys.d?1:0)-(keys.ArrowLeft||keys.a?1:0),my=(keys.ArrowDown||keys.s?1:0)-(keys.ArrowUp||keys.w?1:0);if(joy.on){mx=joy.dx;my=joy.dy}let m=Math.hypot(mx,my)||1;if(mx||my){p.face=Math.atan2(my,mx);p.x+=mx/m*p.sp*dt;p.y+=my/m*p.sp*dt}weapons(dt);spawn-=dt;if(spawn<=0){let n=Math.min(6,1+Math.floor(wave()/2));for(let i=0;i<n;i++)spawnE();spawn=Math.max(.13,.67-wave()*.045)}let bn=Math.floor(time/120);if(bn>bossN){bossN=bn;spawnE(true);shake=16;snd(70,.2,.03)}for(let e of en){let dx=p.x-e.x,dy=p.y-e.y,l=Math.hypot(dx,dy)||1;e.x+=dx/l*e.sp*dt;e.y+=dy/l*e.sp*dt;e.hit=Math.max(0,e.hit-dt);if(l<p.r+e.r){p.hp-=e.dmg*dt;shake=3;if(p.hp<=0)return die()}}for(let i=shots.length-1;i>=0;i--){let s=shots[i];s.age=(s.age||0)+dt;if(s.k==='boom'&&s.age>.82){let dx=p.x-s.x,dy=p.y-s.y,l=Math.hypot(dx,dy)||1;s.vx=dx/l*620;s.vy=dy/l*620}s.x+=s.vx*dt;s.y+=s.vy*dt;s.l-=dt;let rem=s.l<=0;for(let e of [...en]){if(rem)break;s.hit??=new Set();if(s.hit.has(e))continue;if(Math.hypot(s.x-e.x,s.y-e.y)<s.r+e.r){s.hit.add(e);hit(e,s.dmg,s.col);if(s.p>0)s.p--;else rem=true}}if(rem)shots.splice(i,1)}for(let i=haz.length-1;i>=0;i--){let h=haz[i];h.l-=dt;if(h.k==='mine')for(let e of [...en])if(Math.hypot(e.x-h.x,e.y-h.y)<e.r+h.r+5){for(let q of [...en])if(Math.hypot(q.x-h.x,q.y-h.y)<h.rad+q.r)hit(q,h.dmg,h.col);burst(h.x,h.y,h.col,20);h.l=0;break}if(h.l<=0)haz.splice(i,1)}for(let i=gems.length-1;i>=0;i--){let g=gems[i],dx=p.x-g.x,dy=p.y-g.y,l=Math.hypot(dx,dy);if(l<p.pick){let s=Math.max(180,600*(1-l/p.pick));g.x+=dx/(l||1)*s*dt;g.y+=dy/(l||1)*s*dt}if(l<p.r+14){xp+=g.v*p.xpb;gems.splice(i,1);if(xp>=need)levelup()}}for(let i=fx.length-1;i>=0;i--){let f=fx[i];f.x+=f.vx*dt;f.y+=f.vy*dt;f.l-=dt;if(f.l<=0)fx.splice(i,1)}shake=Math.max(0,shake-18*dt);$('hpText').textContent=`❤ ${Math.ceil(p.hp)}/${Math.ceil(p.max)}`;$('lvlText').textContent=`${tr('УР.','LV.')} ${lvl} · ${tr('ВОЛНА','WAVE')} ${wave()}`;$('timeText').textContent=fmt(time);$('coinText').textContent=`✦ ${coins}`;$('xpFill').style.width=Math.min(100,xp/need*100)+'%'}
function die(){if(!rev&&b.ysdk?.adv?.showRewardedVideo){paused=true;st='revive';b.gameplayStop();show('revive')}else finish()}
async function revive(){let ok=await b.rewarded();if(!ok)return;p.hp=p.max*.55;rev=true;en=en.filter(e=>Math.hypot(e.x-p.x,e.y-p.y)>280);paused=false;st='play';show('play');b.gameplayStart();last=performance.now()}
function sh(px,py,rx,ry){x.fillStyle='#0007';x.beginPath();x.ellipse(px,py+ry*.8,rx,ry,0,0,6.28);x.fill()}
function ground(){let w=worlds[wi()];x.fillStyle=w.g;x.fillRect(0,0,W,H);let z=96,ox=(((-p.x)%z)+z)%z,oy=(((-p.y)%z)+z)%z;x.strokeStyle=w.grid;x.globalAlpha=.65;for(let q=ox-z;q<W+z;q+=z){x.beginPath();x.moveTo(q,0);x.lineTo(q,H);x.stroke()}for(let q=oy-z;q<H+z;q+=z){x.beginPath();x.moveTo(0,q);x.lineTo(W,q);x.stroke()}x.globalAlpha=1;for(let i=0;i<28;i++){let gx=((i*233-p.x*.18)%(W+160)+W+160)%(W+160)-80,gy=((i*137-p.y*.18)%(H+160)+H+160)%(H+160)-80;x.fillStyle=i%3?w.gl+'33':'#ffffff08';x.beginPath();x.arc(gx,gy,4+i%5,0,6.28);x.fill()}x.fillStyle='#fff';x.font='800 12px Arial';x.fillText(w.n,14,H-18)}
function hero(){sh(p.x,p.y,25,10);x.save();x.translate(p.x,p.y+Math.sin(time*9)*2);x.rotate(p.face);x.shadowColor=p.hero.col;x.shadowBlur=15;x.fillStyle='#172334';x.beginPath();x.ellipse(0,4,21,24,0,0,6.28);x.fill();x.fillStyle=p.hero.col;x.beginPath();x.arc(0,-8,17,0,6.28);x.fill();x.fillStyle='#07111d';x.beginPath();x.ellipse(5,-9,12,7,0,0,6.28);x.fill();x.fillStyle=p.hero.col;x.fillRect(14,-2,20,6);x.restore();let pet=pets.find(v=>v.id===p.pet),a=time*1.9,px=p.x+Math.cos(a)*38,py=p.y+Math.sin(a)*24;sh(px,py,10,4);x.font='18px sans-serif';x.textAlign='center';x.fillText(pet.i,px,py+6);x.textAlign='start'}
function enemy(e){sh(e.x,e.y,e.r*.8,e.r*.3);x.save();x.translate(e.x,e.y);x.rotate(Math.atan2(p.y-e.y,p.x-e.x));if(e.hit){x.shadowColor='#fff';x.shadowBlur=18}if(e.t==='boss'){x.fillStyle='#3a164b';x.beginPath();x.arc(0,0,55,0,6.28);x.fill();x.strokeStyle='#d861ff';x.lineWidth=6;for(let i=0;i<8;i++){let a=i*.785+time*.3;x.beginPath();x.moveTo(Math.cos(a)*45,Math.sin(a)*45);x.lineTo(Math.cos(a)*75,Math.sin(a)*75);x.stroke()}x.fillStyle='#ff4f88';x.beginPath();x.arc(12,-8,17,0,6.28);x.fill();x.fillStyle='#000b';x.fillRect(-65,-87,130,9);x.fillStyle='#ff5b78';x.fillRect(-65,-87,130*Math.max(0,e.hp/e.max),9)}else if(e.t==='runner'||e.t==='swarm'){x.fillStyle=e.t==='swarm'?'#7dff75':'#ff5f6d';x.beginPath();x.moveTo(24,0);x.lineTo(-14,-14);x.lineTo(-7,0);x.lineTo(-14,14);x.closePath();x.fill()}else if(e.t==='mech'){x.fillStyle='#aeb7c2';x.beginPath();x.arc(0,0,25,0,6.28);x.fill();x.fillStyle='#ffb44e';x.beginPath();x.arc(8,-3,7,0,6.28);x.fill()}else if(e.t==='elite'){x.fillStyle='#ff9d4a';x.beginPath();x.moveTo(30,0);x.lineTo(8,-25);x.lineTo(-25,-16);x.lineTo(-28,16);x.lineTo(8,25);x.closePath();x.fill()}else{x.fillStyle='#65d6ff';x.beginPath();x.ellipse(0,0,22,17,0,0,6.28);x.fill();x.fillStyle='#10202b';x.beginPath();x.arc(8,-2,7,0,6.28);x.fill()}x.restore()}
function draw(){if(!p){x.fillStyle='#071827';x.fillRect(0,0,W,H);return}ground();let cx=W/2-p.x,cy=H/2-p.y;x.save();if(shake)x.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);x.translate(cx,cy);for(let g of gems){x.save();x.translate(g.x,g.y);x.rotate(time*2);x.fillStyle='#55e8ff';x.shadowColor='#55e8ff';x.shadowBlur=12;x.beginPath();x.moveTo(0,-g.r);x.lineTo(g.r,0);x.lineTo(0,g.r);x.lineTo(-g.r,0);x.closePath();x.fill();x.restore()}for(let h of haz){x.save();x.strokeStyle=x.fillStyle=h.col;x.globalAlpha=Math.max(.15,h.l/(h.m||1));if(h.k==='ring'){let r=10+(h.max-10)*(1-h.l/h.m);x.lineWidth=9;x.beginPath();x.arc(h.x,h.y,r,0,6.28);x.stroke()}else if(h.k==='beam'){x.lineWidth=6;x.beginPath();x.moveTo(h.x,h.y);x.lineTo(h.x2,h.y2);x.stroke()}else{x.beginPath();x.arc(h.x,h.y,h.r+Math.sin(time*8)*2,0,6.28);x.fill()}x.restore()}for(let s of shots){x.save();x.translate(s.x,s.y);x.fillStyle=s.col;x.shadowColor=s.col;x.shadowBlur=14;if(s.k==='knife'){x.rotate(Math.atan2(s.vy,s.vx)+1.57);x.beginPath();x.moveTo(0,-12);x.lineTo(5,8);x.lineTo(-5,8);x.closePath();x.fill()}else if(s.k==='boom'){x.strokeStyle=s.col;x.lineWidth=6;x.beginPath();x.arc(0,0,11,.2,4.7);x.stroke()}else{x.beginPath();x.arc(0,0,s.r,0,6.28);x.fill()}x.restore()}let ow=weps.orbit;if(ow){let n=Math.min(6,1+Math.floor((ow.lv+1)/2)),rad=54+ow.lv*4;for(let i=0;i<n;i++){let a=ow.spin+i*6.283/n,px=p.x+Math.cos(a)*rad,py=p.y+Math.sin(a)*rad;x.save();x.translate(px,py);x.rotate(a);x.fillStyle=WD.orbit.col;x.beginPath();x.moveTo(12,0);x.lineTo(-8,-6);x.lineTo(-4,0);x.lineTo(-8,6);x.closePath();x.fill();x.restore()}}for(let e of en)enemy(e);for(let f of fx){x.globalAlpha=Math.max(0,f.l/f.m);x.fillStyle=f.col;x.beginPath();x.arc(f.x,f.y,3,0,6.28);x.fill();x.globalAlpha=1}hero();x.restore()}
function loop(n){let dt=Math.min(.033,(n-last)/1000||0);last=n;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
$('playBtn').onclick=()=>{st='select';show('select')};$('backBtn').onclick=menu;$('startBtn').onclick=start;$('howBtn').onclick=()=>{st='help';show('help')};$('helpBackBtn').onclick=menu;$('pauseBtn').onclick=()=>{if(st!=='play')return;paused=true;st='pause';b.gameplayStop();show('pause')};$('resumeBtn').onclick=()=>{paused=false;st='play';show('play');b.gameplayStart();last=performance.now()};$('quitBtn').onclick=()=>finish(false,true);$('retryBtn').onclick=start;$('resultMenuBtn').onclick=menu;$('reviveBtn').onclick=revive;$('skipReviveBtn').onclick=()=>finish();$('metaBtn').onclick=()=>{st='meta';meta();show('meta')};$('metaBackBtn').onclick=menu;$('langBtn').onclick=()=>{lang=lang==='ru'?'en':'ru';ui()};function sound(){save.settings.muted=!save.settings.muted;persist()}$('soundBtn').onclick=sound;$('pauseSoundBtn').onclick=sound;
addEventListener('keydown',e=>keys[e.key]=1);addEventListener('keyup',e=>keys[e.key]=0);c.addEventListener('touchstart',e=>{if(st!=='play'||paused)return;let q=e.changedTouches[0];joy={on:true,id:q.identifier,x:q.clientX,y:q.clientY,dx:0,dy:0};$('joystick').style.left=q.clientX-54+'px';$('joystick').style.top=q.clientY-54+'px';$('joystick').classList.remove('hidden')},{passive:true});c.addEventListener('touchmove',e=>{if(!joy.on)return;for(let q of e.changedTouches)if(q.identifier===joy.id){let dx=q.clientX-joy.x,dy=q.clientY-joy.y,l=Math.hypot(dx,dy),m=40;if(l>m){dx*=m/l;dy*=m/l}joy.dx=dx/m;joy.dy=dy/m;$('stick').style.transform=`translate(${dx}px,${dy}px)`}},{passive:true});function te(){joy.on=false;joy.dx=joy.dy=0;$('stick').classList.add('hidden')};c.addEventListener('touchend',te);c.addEventListener('touchcancel',te);ui();menu();