import { YandexBridge } from './yandex.js';

const $ = id => document.getElementById(id);
const canvas = $('game');
const ctx = canvas.getContext('2d');
const bridge = new YandexBridge();
await bridge.init();

let W=0,H=0,DPR=1,last=performance.now();
function resize(){DPR=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=W*DPR;canvas.height=H*DPR;canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(DPR,0,0,DPR,0,0)}
addEventListener('resize',resize);resize();

const lang0=(bridge.lang||'ru').startsWith('ru')?'ru':'en';
let lang=lang0;
const tr=(ru,en)=>lang==='ru'?ru:en;
const fmt=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(Math.floor(s%60)).padStart(2,'0')}`;
const TAU=Math.PI*2, clamp=(v,a,b)=>Math.max(a,Math.min(b,v));

const HEROES=[
 {id:'rain',ru:'Капитан Рейн',en:'Captain Rain',hp:155,sp:190,dmg:1.00,col:'#4cc9ff',weapon:'gun',u:0,skill:'shield'},
 {id:'luna',ru:'Луна',en:'Luna',hp:115,sp:200,dmg:1.08,col:'#c77dff',weapon:'orbit',u:0,skill:'moon'},
 {id:'ice',ru:'Айс',en:'Ice',hp:130,sp:205,dmg:1.03,col:'#72f1ff',weapon:'frost',u:2,skill:'freeze'},
 {id:'chaos',ru:'Хаос',en:'Chaos',hp:145,sp:192,dmg:1.16,col:'#ff7b54',weapon:'nova',u:5,skill:'rage'},
 {id:'shade',ru:'Тень',en:'Shade',hp:105,sp:235,dmg:1.12,col:'#8b74ff',weapon:'knife',u:8,skill:'dash'}
];
const PETS=[
 {id:'orb',ru:'Орб',en:'Orb',u:0,icon:'🤖',desc:'Магнит + импульс',passive:p=>p.pick+=40},
 {id:'fox',ru:'Лис',en:'Fox',u:0,icon:'🦊',desc:'Скорость + огненный рывок',passive:p=>p.sp*=1.10},
 {id:'owl',ru:'Сова',en:'Owl',u:3,icon:'🦉',desc:'Опыт + электрический залп',passive:p=>p.xpMul*=1.16},
 {id:'dragon',ru:'Дракон',en:'Dragon',u:6,icon:'🐉',desc:'Урон + огненное дыхание',passive:p=>p.dmg*=1.12},
 {id:'wolf',ru:'Волк',en:'Wolf',u:9,icon:'🐺',desc:'Темп + охота на элиту',passive:p=>p.haste*=1.13}
];
const WEAPONS={
 gun:{icon:'🔫',ru:'Плазмобластер',en:'Plasma Blaster',cd:.58,col:'#67e8ff',evo:'storm'},
 knife:{icon:'🗡️',ru:'Теневые ножи',en:'Shadow Knives',cd:.45,col:'#c9b7ff',evo:'voidknife'},
 frost:{icon:'❄️',ru:'Крио-волна',en:'Cryo Wave',cd:1.8,col:'#83f5ff',evo:'blizzard'},
 nova:{icon:'☄️',ru:'Солнечная нова',en:'Solar Nova',cd:2.5,col:'#ff9f56',evo:'supernova'},
 orbit:{icon:'🌀',ru:'Орбитальные клинки',en:'Orbit Blades',cd:.12,col:'#e191ff',evo:'moonring'},
 laser:{icon:'⚡',ru:'Лучевой жезл',en:'Arc Wand',cd:1.18,col:'#ffe975',evo:'thunder'},
 mine:{icon:'💣',ru:'Кристаллические мины',en:'Crystal Mines',cd:2.55,col:'#65ff9e',evo:'starfield'},
 boom:{icon:'🪃',ru:'Фотонный бумеранг',en:'Photon Boomerang',cd:1.45,col:'#ff7bdc',evo:'comet'}
};
const EVO={storm:'⚡ Плазменный шторм',voidknife:'🌑 Клинки пустоты',blizzard:'🌨️ Абсолютный ноль',supernova:'🌞 Сверхновая',moonring:'🌙 Лунное кольцо',thunder:'⛈️ Громовержец',starfield:'✨ Звёздное поле',comet:'☄️ Кометный разрез'};
const WORLDS=[
 {name:'Кристальные руины',bg:'#071827',ground:'#0d2638',grid:'#173b50',glow:'#55e9ff',accent:'#69f0ff'},
 {name:'Ксеноджунгли',bg:'#06170f',ground:'#0d2818',grid:'#1a4028',glow:'#6dff8b',accent:'#b7ff78'},
 {name:'Красная кузня',bg:'#200c09',ground:'#32140f',grid:'#59251a',glow:'#ff7d54',accent:'#ffc15a'}
];
const DEF={best:0,runs:0,kills:0,currency:0,wins:0,meta:{power:0,health:0,speed:0,fortune:0},settings:{muted:false}};
let save=Object.assign({},DEF,await bridge.load()||{});save.meta=Object.assign({},DEF.meta,save.meta||{});save.settings=Object.assign({},DEF.settings,save.settings||{});
const persist=()=>bridge.save(save);

let state='menu',heroPick=null,petPick=null,player=null;
let enemies=[],shots=[],gems=[],fx=[],hazards=[],chests=[],weapons={},keys={};
let joystick={on:false,id:null,x:0,y:0,dx:0,dy:0};
let elapsed=0,spawnClock=0,bossCount=0,kills=0,level=1,xp=0,xpNeed=24,coins=0,paused=false,revived=false,shake=0,screenFlash=0,audio=null,leveling=false;

function sound(freq=440,d=.05,v=.015){if(save.settings.muted)return;try{audio??=new AudioContext();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=freq;g.gain.value=v;o.connect(g);g.connect(audio.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.stop(audio.currentTime+d)}catch{}}
function show(id){['menu','select','upgrade','pause','revive','result','meta','help'].forEach(q=>$(q).classList.toggle('hidden',q!==id));$('hud').classList.toggle('hidden',!['play','upgrade','pause','revive'].includes(id));if(id!=='play')$('joystick').classList.add('hidden')}
function menu(){state='menu';paused=false;bridge.gameplayStop();show('menu');$('bestText').textContent=`${tr('Лучшее время','Best')}: ${fmt(save.best)} · ${tr('Забегов','Runs')}: ${save.runs}`;$('walletText').textContent=`✦ ${tr('Кристаллы','Crystals')}: ${save.currency}`}
function heroBadge(h){return `<div style="width:64px;height:64px;margin:auto;position:relative"><div style="position:absolute;inset:4px;border-radius:50%;background:radial-gradient(circle at 35% 28%,#fff,${h.col} 32%,#11243a 34%);box-shadow:0 0 20px ${h.col}88"></div><div style="position:absolute;left:16px;top:28px;width:32px;height:17px;border-radius:50%;background:#07111d;border:3px solid #e8fbff"></div></div>`}
function selectionCards(){const mk=(o,type)=>`<div class="card ${save.runs>=o.u?'':'locked'}" data-${type}="${o.id}">${type==='hero'?heroBadge(o):`<div class="icon">${o.icon}</div>`}<b>${o[lang]}</b><small>${save.runs>=o.u?(type==='hero'?`${WEAPONS[o.weapon].icon} ${WEAPONS[o.weapon][lang]}`:o.desc):tr(`Откроется после ${o.u} забегов`,`Unlock after ${o.u} runs`)}</small></div>`;$('heroes').innerHTML=HEROES.map(o=>mk(o,'hero')).join('');$('pets').innerHTML=PETS.map(o=>mk(o,'pet')).join('');document.querySelectorAll('[data-hero]').forEach(el=>el.onclick=()=>{const h=HEROES.find(v=>v.id===el.dataset.hero);if(save.runs<h.u)return;heroPick=h.id;document.querySelectorAll('[data-hero]').forEach(q=>q.classList.toggle('selected',q===el));$('startBtn').disabled=!(heroPick&&petPick)});document.querySelectorAll('[data-pet]').forEach(el=>el.onclick=()=>{const p=PETS.find(v=>v.id===el.dataset.pet);if(save.runs<p.u)return;petPick=p.id;document.querySelectorAll('[data-pet]').forEach(q=>q.classList.toggle('selected',q===el));$('startBtn').disabled=!(heroPick&&petPick)})}
function meta(){const M=[['power','⚔️','Сила',8],['health','❤','Здоровье',8],['speed','⚡','Скорость',6],['fortune','✦','Удача',6]];$('metaWallet').textContent=`✦ ${tr('Кристаллы','Crystals')}: ${save.currency}`;$('metaGrid').innerHTML=M.map(m=>{const l=save.meta[m[0]]||0,c=30+l*40;return `<div class="metaCard"><b>${m[1]} ${m[2]} · ${l}/${m[3]}</b><button data-meta="${m[0]}" ${l>=m[3]||save.currency<c?'disabled':''}>${l>=m[3]?'MAX':`✦ ${c}`}</button></div>`}).join('');document.querySelectorAll('[data-meta]').forEach(el=>el.onclick=()=>{const id=el.dataset.meta,l=save.meta[id]||0,c=30+l*40;if(save.currency<c)return;save.currency-=c;save.meta[id]=l+1;persist();meta()})}
function localize(){const map=[['playBtn','ИГРАТЬ','PLAY'],['metaBtn','УЛУЧШЕНИЯ','UPGRADES'],['howBtn','КАК ИГРАТЬ','HOW TO PLAY'],['heroTitle','Выбери героя','Choose a hero'],['petTitle','Выбери питомца','Choose a pet'],['startBtn','В БОЙ','START'],['backBtn','НАЗАД','BACK'],['upgradeTitle','Новый уровень','Level up'],['upgradeHint','Выбери оружие или усиление','Choose a weapon or upgrade'],['pauseTitle','Пауза','Paused'],['resumeBtn','ПРОДОЛЖИТЬ','RESUME'],['quitBtn','В МЕНЮ','MENU'],['retryBtn','ЕЩЁ РАЗ','RUN AGAIN'],['resultMenuBtn','В МЕНЮ','MENU'],['metaTitle','Постоянные улучшения','Permanent upgrades'],['metaBackBtn','НАЗАД','BACK'],['helpTitle','Как играть','How to play'],['helpBackBtn','ПОНЯТНО','GOT IT']];map.forEach(([id,ru,en])=>$(id).textContent=tr(ru,en));$('helpBody').innerHTML=`<p>${tr('Survivor-roguelite: двигайся, оружие атакует автоматически. Каждую минуту волны сильнее. Собирай опыт, носи до 6 оружий, прокачивай их до 8 уровня и эволюционируй через сундуки боссов. У каждого питомца есть собственная атака. Босс каждые 2 минуты. Выживи 10 минут.','Move while weapons attack automatically. Waves intensify each minute. Collect XP, carry up to 6 weapons, level them to 8 and evolve them through boss chests. Every pet has its own attack. Boss every 2 minutes. Survive 10 minutes.')}</p>`;selectionCards();meta();if(state==='menu')menu()}

function addWeapon(id){if(weapons[id])weapons[id].lv=Math.min(8,weapons[id].lv+1);else weapons[id]={id,lv:1,cd:.05,spin:0,evolved:false};refreshStrip()}
function refreshStrip(){$('weaponStrip').innerHTML=Object.values(weapons).map(w=>`<span title="${WEAPONS[w.id][lang]}">${w.evolved?'⭐':WEAPONS[w.id].icon}<b>${w.lv}</b></span>`).join('')}
function startRun(){const h=HEROES.find(v=>v.id===heroPick)||HEROES[0],pet=PETS.find(v=>v.id===petPick)||PETS[0];player={x:0,y:0,r:19,max:h.hp+save.meta.health*9,hp:h.hp+save.meta.health*9,sp:h.sp*(1+save.meta.speed*.025),dmg:h.dmg*(1+save.meta.power*.06),haste:1+save.meta.fortune*.02,pick:115,xpMul:1,face:0,hero:h,pet:pet.id,petCd:1.2,inv:0,skillCd:0,walk:0};pet.passive(player);enemies=[];shots=[];gems=[];fx=[];hazards=[];chests=[];weapons={};elapsed=0;spawnClock=.1;bossCount=0;kills=0;level=1;xp=0;xpNeed=24;coins=0;paused=false;revived=false;leveling=false;addWeapon(h.weapon);state='play';show('play');bridge.gameplayStart();last=performance.now()}
function finish(win=false,quit=false){if(!player)return menu();paused=true;state='result';bridge.gameplayStop();save.best=Math.max(save.best,elapsed);save.runs++;save.kills+=kills;save.currency+=coins;save.wins+=(win?1:0);persist();bridge.submitScore('arena_survival',Math.floor(elapsed*100+kills*2));if(quit)return menu();$('resultTitle').textContent=win?tr('Победа!','Victory!'):tr('Забег окончен','Run over');$('resultStats').innerHTML=`<p>${tr('Время','Time')}: <b>${fmt(elapsed)}</b></p><p>${tr('Уровень','Level')}: <b>${level}</b></p><p>${tr('Врагов','Enemies')}: <b>${kills}</b></p><p>${tr('Эволюций','Evolutions')}: <b>${Object.values(weapons).filter(w=>w.evolved).length}</b></p><p>${tr('Кристаллов','Crystals')}: <b>✦ ${coins}</b></p>`;show('result')}
function wave(){return 1+Math.floor(elapsed/60)}
function worldIndex(){return Math.min(2,Math.floor(elapsed/200))}
function spawnEnemy(boss=false){const a=Math.random()*TAU,d=Math.max(W,H)*.72+180,s=1+elapsed/230,r=Math.random();let type=r<.40?'scout':r<.70?'runner':r<.88?'mech':'elite';if(wave()>4&&Math.random()<.18)type='swarm';const e={x:player.x+Math.cos(a)*d,y:player.y+Math.sin(a)*d,t:type,r:20,hp:35*s,max:35*s,sp:72+Math.random()*18,dmg:10+wave()*.6,hit:0,slow:0,phase:Math.random()*TAU};if(type==='runner'){e.r=17;e.hp=e.max=27*s;e.sp=118+wave()*2}if(type==='swarm'){e.r=12;e.hp=e.max=18*s;e.sp=145+wave()*2}if(type==='mech'){e.r=28;e.hp=e.max=100*s;e.sp=50+wave()}if(type==='elite'){e.r=34;e.hp=e.max=165*s;e.sp=58+wave();e.dmg=20+wave()}if(boss){e.t='boss';e.r=68;e.hp=e.max=1500*(1+bossCount*.5);e.sp=44+bossCount*2;e.dmg=36+bossCount*4;e.shotCd=2.2}enemies.push(e)}
function nearest(range=720,from=player){let best=null,bd=range*range;for(const e of enemies){const dx=e.x-from.x,dy=e.y-from.y,d=dx*dx+dy*dy;if(d<bd){bd=d;best=e}}return best}
function particles(px,py,col,n=8,power=180){for(let i=0;i<n;i++){const a=Math.random()*TAU,s=40+Math.random()*power;fx.push({x:px,y:py,vx:Math.cos(a)*s,vy:Math.sin(a)*s,l:.45,m:.45,col,r:2+Math.random()*3})}}
function damageEnemy(e,d,col='#fff',slow=0){e.hp-=d;e.hit=.09;e.slow=Math.max(e.slow,slow);particles(e.x,e.y,col,2,90);if(e.hp<=0)killEnemy(e)}
function killEnemy(e){const i=enemies.indexOf(e);if(i<0)return;enemies.splice(i,1);kills++;if(Math.random()<.14||e.t==='boss')coins+=e.t==='boss'?14:1;gems.push({x:e.x,y:e.y,r:e.t==='boss'?13:7,v:e.t==='boss'?45:e.t==='elite'?13:6});particles(e.x,e.y,e.t==='boss'?'#ffb45e':'#7ae9ff',e.t==='boss'?34:10,240);if(e.t==='boss'){chests.push({x:e.x,y:e.y,r:22,spin:0});screenFlash=.35;shake=12;sound(110,.22,.04)}}
function spawnShot(x,y,vx,vy,r,dmg,col,life=1.6,kind='bullet',pierce=0){shots.push({x,y,vx,vy,r,dmg,col,life,kind,pierce,age:0})}
function fireWeapon(w){const base=WEAPONS[w.id],lv=w.lv,evo=w.evolved,mul=player.dmg*(evo?1.55:1);if(w.id==='gun'||w.id==='knife'){const target=nearest();if(!target)return;const a=Math.atan2(target.y-player.y,target.x-player.x),n=(w.id==='knife'?Math.min(6,1+Math.floor(lv/2)):Math.min(4,1+Math.floor((lv-1)/3)))+(evo?2:0);for(let i=0;i<n;i++){const aa=a+(i-(n-1)/2)*.12;spawnShot(player.x,player.y,Math.cos(aa)*(w.id==='knife'?470:560),Math.sin(aa)*(w.id==='knife'?470:560),w.id==='knife'?6:5,(w.id==='knife'?22:28)*(1+lv*.22)*mul,base.col,evo?2.3:1.7,w.id,evo?3:Math.floor(lv/4))}sound(w.id==='gun'?700:520,.03,.012)}
 if(w.id==='frost'){const rad=120+lv*18+(evo?90:0);for(const e of [...enemies]){const dx=e.x-player.x,dy=e.y-player.y;if(dx*dx+dy*dy<rad*rad)damageEnemy(e,(18+lv*8)*mul,base.col,evo?2.8:1.4)}hazards.push({x:player.x,y:player.y,r:rad,l:.45,m:.45,col:base.col,kind:'ring'});sound(260,.12,.02)}
 if(w.id==='nova'){const rad=145+lv*20+(evo?110:0);for(const e of [...enemies]){const dx=e.x-player.x,dy=e.y-player.y;if(dx*dx+dy*dy<rad*rad)damageEnemy(e,(26+lv*11)*mul,base.col)}hazards.push({x:player.x,y:player.y,r:rad,l:.6,m:.6,col:base.col,kind:'nova'});shake=6;sound(160,.16,.025)}
 if(w.id==='laser'){let current=nearest(760);let from={x:player.x,y:player.y};for(let i=0;i<(evo?7:2+Math.floor(lv/2))&&current;i++){damageEnemy(current,(24+lv*8)*mul,base.col);hazards.push({x1:from.x,y1:from.y,x2:current.x,y2:current.y,l:.18,m:.18,col:base.col,kind:'beam'});from=current;let next=null,bd=180*180;for(const e of enemies){if(e===current)continue;const dx=e.x-current.x,dy=e.y-current.y,d=dx*dx+dy*dy;if(d<bd){bd=d;next=e}}current=next}sound(860,.08,.014)}
 if(w.id==='mine'){const n=evo?4:1+Math.floor(lv/3);for(let i=0;i<n;i++){const a=Math.random()*TAU,d=50+Math.random()*140;hazards.push({x:player.x+Math.cos(a)*d,y:player.y+Math.sin(a)*d,r:15+lv*2,l:3.5,m:3.5,col:base.col,kind:'mine',dmg:(48+lv*14)*mul})}}
 if(w.id==='boom'){const n=evo?4:1+Math.floor(lv/3);for(let i=0;i<n;i++){const a=player.face+(i-(n-1)/2)*.3;spawnShot(player.x,player.y,Math.cos(a)*360,Math.sin(a)*360,11,(34+lv*10)*mul,base.col,2.2,'boom',evo?6:3)}}
}
function orbitDamage(dt){const w=weapons.orbit;if(!w)return;w.spin+=dt*(2.2+w.lv*.08);const n=Math.min(7,2+Math.floor(w.lv/2)+(w.evolved?2:0)),rad=62+w.lv*5+(w.evolved?24:0);for(let i=0;i<n;i++){const a=w.spin+i*TAU/n,ox=player.x+Math.cos(a)*rad,oy=player.y+Math.sin(a)*rad;for(const e of [...enemies]){if(e._orb&&elapsed-e._orb<.18)continue;const dx=e.x-ox,dy=e.y-oy;if(dx*dx+dy*dy<(e.r+11)*(e.r+11)){e._orb=elapsed;damageEnemy(e,(11+w.lv*4)*player.dmg*(w.evolved?1.7:1),WEAPONS.orbit.col)}}}}
function petAttack(dt){player.petCd-=dt;if(player.petCd>0)return;const pet=player.pet;player.petCd=pet==='dragon'?1.7:pet==='owl'?2.1:pet==='wolf'?1.8:pet==='fox'?2.2:2.5;const target=nearest(560);if(!target)return;if(pet==='orb'){for(const e of [...enemies]){const dx=e.x-player.x,dy=e.y-player.y;if(dx*dx+dy*dy<180*180)damageEnemy(e,15*player.dmg,'#72f1ff')}hazards.push({x:player.x,y:player.y,r:180,l:.35,m:.35,col:'#72f1ff',kind:'ring'})}
 if(pet==='fox'){const a=Math.atan2(target.y-player.y,target.x-player.x);for(let i=-1;i<=1;i++)spawnShot(player.x,player.y,Math.cos(a+i*.16)*430,Math.sin(a+i*.16)*430,7,18*player.dmg,'#ff9d57',1.3,'pet',1)}
 if(pet==='owl'){let cur=target,from={x:player.x,y:player.y};for(let i=0;i<4&&cur;i++){damageEnemy(cur,20*player.dmg,'#ffe46b');hazards.push({x1:from.x,y1:from.y,x2:cur.x,y2:cur.y,l:.15,m:.15,col:'#ffe46b',kind:'beam'});from=cur;cur=nearest(220,cur)}}
 if(pet==='dragon'){const a=Math.atan2(target.y-player.y,target.x-player.x);for(let i=-2;i<=2;i++){const aa=a+i*.11;spawnShot(player.x,player.y,Math.cos(aa)*340,Math.sin(aa)*340,9,22*player.dmg,'#ff714d',.9,'fire',1)}}
 if(pet==='wolf'){const elite=enemies.find(e=>e.t==='elite'||e.t==='boss')||target;damageEnemy(elite,42*player.dmg,'#d8d0ff');particles(elite.x,elite.y,'#d8d0ff',12,220)}}
function evolveOne(){const candidates=Object.values(weapons).filter(w=>w.lv>=8&&!w.evolved);if(!candidates.length)return false;const w=candidates[Math.floor(Math.random()*candidates.length)];w.evolved=true;refreshStrip();toast(`${tr('ЭВОЛЮЦИЯ','EVOLUTION')}: ${EVO[WEAPONS[w.id].evo]}`);screenFlash=.55;shake=10;sound(980,.25,.04);return true}
function openChest(ch){const i=chests.indexOf(ch);if(i>=0)chests.splice(i,1);coins+=8;let evolved=evolveOne();if(!evolved){const owned=Object.values(weapons).filter(w=>w.lv<8);if(owned.length){const w=owned[Math.floor(Math.random()*owned.length)];w.lv=Math.min(8,w.lv+2);refreshStrip();toast(`${WEAPONS[w.id][lang]} +2`)}else{player.max+=12;player.hp=Math.min(player.max,player.hp+35);toast(tr('Сундук: здоровье усилено','Chest: health boosted'))}}particles(ch.x,ch.y,'#ffe17a',30,260)}
function toast(t){$('toast').textContent=t;$('toast').classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').classList.add('hidden'),1600)}
function levelUp(){if(leveling)return;leveling=true;paused=true;state='upgrade';show('upgrade');const choices=[];const ids=Object.keys(WEAPONS).sort(()=>Math.random()-.5);for(const id of ids){if(choices.length>=3)break;if(weapons[id]&&weapons[id].lv<8)choices.push({type:'weapon',id});else if(!weapons[id]&&Object.keys(weapons).length<6)choices.push({type:'weapon',id})}while(choices.length<3){const buffs=['power','speed','health','magnet'];choices.push({type:'buff',id:buffs[Math.floor(Math.random()*buffs.length)]})}$('upgradeCards').innerHTML=choices.map((o,i)=>{if(o.type==='weapon'){const w=WEAPONS[o.id],lv=weapons[o.id]?.lv||0;return `<button class="upgradeCard" data-choice="${i}"><b>${w.icon} ${w[lang]}</b><small>${lv?tr(`Уровень ${lv} → ${Math.min(8,lv+1)}`,`Level ${lv} → ${Math.min(8,lv+1)}`):tr('Новое оружие','New weapon')}</small></button>`}const n={power:['⚔️ Сила +10%','⚔️ Power +10%'],speed:['⚡ Скорость +8%','⚡ Speed +8%'],health:['❤ Здоровье +20','❤ Health +20'],magnet:['🧲 Магнит +25','🧲 Magnet +25']}[o.id];return `<button class="upgradeCard" data-choice="${i}"><b>${tr(n[0],n[1])}</b></button>`}).join('');document.querySelectorAll('[data-choice]').forEach(el=>el.onclick=()=>{const o=choices[+el.dataset.choice];if(o.type==='weapon')addWeapon(o.id);else if(o.id==='power')player.dmg*=1.10;else if(o.id==='speed')player.sp*=1.08;else if(o.id==='health'){player.max+=20;player.hp=Math.min(player.max,player.hp+20)}else player.pick+=25;paused=false;state='play';leveling=false;show('play');last=performance.now()})}
function update(dt){if(state!=='play'||paused||!player)return;elapsed+=dt;if(elapsed>=600){finish(true);return}player.inv=Math.max(0,player.inv-dt);player.skillCd=Math.max(0,player.skillCd-dt);spawnClock-=dt;const intensity=Math.min(8,1+wave()*.6),interval=Math.max(.08,.68/intensity);while(spawnClock<=0){spawnClock+=interval;const batch=wave()>=7?2:1;for(let i=0;i<batch;i++)spawnEnemy(false)}const targetBoss=Math.floor(elapsed/120);if(targetBoss>bossCount){bossCount=targetBoss;spawnEnemy(true);toast(tr('⚠ БОСС ПРИБЛИЖАЕТСЯ','⚠ BOSS INCOMING'));sound(95,.4,.04)}
 let dx=(keys['ArrowRight']||keys['KeyD']?1:0)-(keys['ArrowLeft']||keys['KeyA']?1:0),dy=(keys['ArrowDown']||keys['KeyS']?1:0)-(keys['ArrowUp']||keys['KeyW']?1:0);if(joystick.on){dx=joystick.dx;dy=joystick.dy}const mag=Math.hypot(dx,dy);if(mag>.05){dx/=Math.max(1,mag);dy/=Math.max(1,mag);player.x+=dx*player.sp*dt;player.y+=dy*player.sp*dt;player.face=Math.atan2(dy,dx);player.walk+=dt*10}
 for(const w of Object.values(weapons)){w.cd-=dt*player.haste;if(w.cd<=0&&w.id!=='orbit'){fireWeapon(w);w.cd+=WEAPONS[w.id].cd/Math.max(.7,1+w.lv*.035)}}orbitDamage(dt);petAttack(dt);
 for(const e of [...enemies]){e.hit=Math.max(0,e.hit-dt);e.slow=Math.max(0,e.slow-dt);const a=Math.atan2(player.y-e.y,player.x-e.x),spd=e.sp*(e.slow>0?.55:1);e.x+=Math.cos(a)*spd*dt;e.y+=Math.sin(a)*spd*dt;e.phase+=dt*4;if(e.t==='boss'){e.shotCd-=dt;if(e.shotCd<=0){e.shotCd=1.8;for(let i=0;i<10;i++){const aa=i*TAU/10+elapsed*.4;hazards.push({x:e.x,y:e.y,vx:Math.cos(aa)*145,vy:Math.sin(aa)*145,r:10,l:4,m:4,col:'#ff795e',kind:'enemyShot',dmg:14})}}}
 const dd=Math.hypot(e.x-player.x,e.y-player.y);if(dd<e.r+player.r&&player.inv<=0){player.hp-=e.dmg;player.inv=.7;shake=8;particles(player.x,player.y,'#ff6b6b',12,180);sound(120,.12,.03);if(player.hp<=0){if(!revived){paused=true;state='revive';show('revive')}else finish(false);return}}}
 for(const s of [...shots]){s.age+=dt;s.life-=dt;s.x+=s.vx*dt;s.y+=s.vy*dt;if(s.kind==='boom'){s.vx*=.995;s.vy*=.995}for(const e of [...enemies]){const dd=(e.x-s.x)**2+(e.y-s.y)**2;if(dd<(e.r+s.r)**2){damageEnemy(e,s.dmg,s.col,s.kind==='fire'?.35:0);if(s.pierce>0)s.pierce--;else{s.life=0;break}}}if(s.life<=0)shots.splice(shots.indexOf(s),1)}
 for(const h of [...hazards]){h.l-=dt;if(h.kind==='mine'){for(const e of [...enemies]){const dd=(e.x-h.x)**2+(e.y-h.y)**2;if(dd<(e.r+h.r+8)**2){for(const q of [...enemies]){const dx=q.x-h.x,dy=q.y-h.y;if(dx*dx+dy*dy<(90+h.r*2)**2)damageEnemy(q,h.dmg,h.col)}h.kind='nova';h.r=90+h.r*2;h.l=.35;h.m=.35;shake=5;break}}}else if(h.kind==='enemyShot'){h.x+=h.vx*dt;h.y+=h.vy*dt;const dd=(h.x-player.x)**2+(h.y-player.y)**2;if(dd<(h.r+player.r)**2&&player.inv<=0){player.hp-=h.dmg;player.inv=.5;h.l=0;shake=6}}if(h.l<=0)hazards.splice(hazards.indexOf(h),1)}
 for(const g of [...gems]){const dx=player.x-g.x,dy=player.y-g.y,d=Math.hypot(dx,dy);if(d<player.pick){const sp=220+Math.max(0,player.pick-d)*3;g.x+=dx/Math.max(1,d)*sp*dt;g.y+=dy/Math.max(1,d)*sp*dt}if(d<player.r+12){xp+=g.v*player.xpMul;gems.splice(gems.indexOf(g),1);sound(850,.025,.006)}}
 while(xp>=xpNeed){xp-=xpNeed;level++;xpNeed=Math.floor(24+level*11+level*level*.8);levelUp();break}
 for(const ch of [...chests]){ch.spin+=dt*2;if(Math.hypot(ch.x-player.x,ch.y-player.y)<player.r+ch.r+8)openChest(ch)}
 for(const f of [...fx]){f.l-=dt;f.x+=f.vx*dt;f.y+=f.vy*dt;f.vx*=.94;f.vy*=.94;if(f.l<=0)fx.splice(fx.indexOf(f),1)}screenFlash=Math.max(0,screenFlash-dt);shake=Math.max(0,shake-dt*18);updateHud()}
function updateHud(){$('hpText').textContent=`❤ ${Math.ceil(Math.max(0,player.hp))}/${Math.ceil(player.max)}`;$('lvlText').textContent=`${tr('УР.','LV.')} ${level}`;$('timeText').textContent=fmt(elapsed);$('coinText').textContent=`✦ ${coins}`;$('xpFill').style.width=`${clamp(xp/xpNeed*100,0,100)}%`}
function rr(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function drawGround(){const w=WORLDS[worldIndex()];ctx.fillStyle=w.bg;ctx.fillRect(0,0,W,H);ctx.save();ctx.translate(W/2-player.x,H/2-player.y);const tile=86,minX=Math.floor((player.x-W/2)/tile)-2,maxX=Math.floor((player.x+W/2)/tile)+2,minY=Math.floor((player.y-H/2)/tile)-2,maxY=Math.floor((player.y+H/2)/tile)+2;for(let gx=minX;gx<=maxX;gx++)for(let gy=minY;gy<=maxY;gy++){const px=gx*tile,py=gy*tile,seed=Math.abs((gx*928371+gy*364479)%997);ctx.fillStyle=(seed%3===0)?w.ground:w.bg;ctx.fillRect(px,py,tile-2,tile-2);ctx.strokeStyle=w.grid;ctx.globalAlpha=.42;ctx.strokeRect(px,py,tile,tile);ctx.globalAlpha=1;if(seed%5===0){ctx.save();ctx.translate(px+tile*.5,py+tile*.5);ctx.rotate(seed);ctx.fillStyle=w.glow;ctx.globalAlpha=.20;ctx.beginPath();ctx.moveTo(0,-18);ctx.lineTo(10,5);ctx.lineTo(0,16);ctx.lineTo(-9,5);ctx.closePath();ctx.fill();ctx.globalAlpha=1;ctx.restore()}if(seed%7===0){ctx.fillStyle=w.accent;ctx.globalAlpha=.13;ctx.beginPath();ctx.arc(px+18+(seed%50),py+18+((seed*3)%50),5+(seed%7),0,TAU);ctx.fill();ctx.globalAlpha=1}}ctx.restore()}
function drawHero(){const h=player.hero,t=player.walk,bob=Math.sin(t)*2;ctx.save();ctx.translate(player.x,player.y+bob);ctx.rotate(player.face+Math.PI/2);ctx.fillStyle='rgba(0,0,0,.28)';ctx.beginPath();ctx.ellipse(0,20,22,9,0,0,TAU);ctx.fill();ctx.shadowBlur=18;ctx.shadowColor=h.col;ctx.fillStyle=h.col;ctx.beginPath();ctx.arc(0,-3,18,0,TAU);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#10253b';rr(-14,-5,28,27,9);ctx.fill();ctx.fillStyle='#eaffff';rr(-13,-13,26,12,6);ctx.fill();ctx.fillStyle='#07131f';rr(-10,-10,20,7,4);ctx.fill();ctx.fillStyle=h.col;ctx.fillRect(-16,6,7,14);ctx.fillRect(9,6,7,14);ctx.fillStyle='#dcecff';ctx.fillRect(-19,18,9,8);ctx.fillRect(10,18,9,8);ctx.fillStyle='#a7dfff';ctx.fillRect(10,-1,5,17);ctx.fillRect(12,-14,5,16);ctx.restore()}
function drawPet(){const pet=PETS.find(v=>v.id===player.pet),a=elapsed*1.8;const px=player.x+Math.cos(a)*48,py=player.y+Math.sin(a)*30-22;ctx.save();ctx.translate(px,py);ctx.shadowBlur=15;ctx.shadowColor='#8cecff';ctx.fillStyle='#10283a';ctx.beginPath();ctx.arc(0,0,12,0,TAU);ctx.fill();ctx.shadowBlur=0;ctx.font='18px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(pet.icon,0,1);ctx.restore()}
function drawEnemies(){for(const e of enemies){ctx.save();ctx.translate(e.x,e.y+Math.sin(e.phase)*2);ctx.fillStyle='rgba(0,0,0,.28)';ctx.beginPath();ctx.ellipse(0,e.r*.65,e.r*.9,e.r*.32,0,0,TAU);ctx.fill();const col=e.hit?'#ffffff':e.t==='boss'?'#ff6a55':e.t==='elite'?'#ffb44d':e.t==='mech'?'#98a8bd':e.t==='runner'?'#ff5d8f':e.t==='swarm'?'#a7ff5f':'#69d7ff';ctx.shadowBlur=e.t==='boss'?25:10;ctx.shadowColor=col;ctx.fillStyle=col;if(e.t==='runner'||e.t==='swarm'){ctx.beginPath();ctx.moveTo(0,-e.r);ctx.lineTo(e.r*.85,e.r*.65);ctx.lineTo(0,e.r*.25);ctx.lineTo(-e.r*.85,e.r*.65);ctx.closePath();ctx.fill()}else if(e.t==='mech'){rr(-e.r*.75,-e.r*.72,e.r*1.5,e.r*1.45,7);ctx.fill();ctx.fillStyle='#223040';ctx.fillRect(-e.r*.4,-4,e.r*.8,8)}else{ctx.beginPath();for(let i=0;i<10;i++){const a=i*TAU/10-Math.PI/2,r=i%2?e.r*.72:e.r;const px=Math.cos(a)*r,py=Math.sin(a)*r;i?ctx.lineTo(px,py):ctx.moveTo(px,py)}ctx.closePath();ctx.fill()}ctx.shadowBlur=0;ctx.fillStyle='#07131c';ctx.beginPath();ctx.arc(-e.r*.25,-e.r*.15,Math.max(2,e.r*.1),0,TAU);ctx.arc(e.r*.25,-e.r*.15,Math.max(2,e.r*.1),0,TAU);ctx.fill();if(e.t==='boss'){ctx.fillStyle='#241019';rr(-e.r,-e.r-18,e.r*2,8,4);ctx.fill();ctx.fillStyle='#ff6b5a';rr(-e.r,-e.r-18,e.r*2*(e.hp/e.max),8,4);ctx.fill()}ctx.restore()}}
function drawCombat(){ctx.save();const sx=shake?(Math.random()-.5)*shake:0,sy=shake?(Math.random()-.5)*shake:0;ctx.translate(W/2-player.x+sx,H/2-player.y+sy);for(const g of gems){ctx.save();ctx.translate(g.x,g.y);ctx.rotate(elapsed*2);ctx.fillStyle='#72efff';ctx.shadowBlur=14;ctx.shadowColor='#72efff';ctx.beginPath();ctx.moveTo(0,-g.r);ctx.lineTo(g.r*.75,0);ctx.lineTo(0,g.r);ctx.lineTo(-g.r*.75,0);ctx.closePath();ctx.fill();ctx.restore()}for(const ch of chests){ctx.save();ctx.translate(ch.x,ch.y);ctx.rotate(Math.sin(ch.spin)*.08);ctx.shadowBlur=22;ctx.shadowColor='#ffe177';ctx.fillStyle='#6b4518';rr(-22,-17,44,34,7);ctx.fill();ctx.fillStyle='#ffd85f';ctx.fillRect(-22,-4,44,8);ctx.fillRect(-4,-17,8,34);ctx.restore()}for(const h of hazards){ctx.save();ctx.globalAlpha=clamp(h.l/h.m,0,1);if(h.kind==='beam'){ctx.strokeStyle=h.col;ctx.lineWidth=4;ctx.shadowBlur=14;ctx.shadowColor=h.col;ctx.beginPath();ctx.moveTo(h.x1,h.y1);ctx.lineTo(h.x2,h.y2);ctx.stroke()}else if(h.kind==='enemyShot'){ctx.fillStyle=h.col;ctx.shadowBlur=14;ctx.shadowColor=h.col;ctx.beginPath();ctx.arc(h.x,h.y,h.r,0,TAU);ctx.fill()}else{ctx.strokeStyle=h.col;ctx.fillStyle=h.col;ctx.shadowBlur=18;ctx.shadowColor=h.col;ctx.lineWidth=5;ctx.beginPath();ctx.arc(h.x,h.y,h.r,0,TAU);h.kind==='mine'?ctx.fill():ctx.stroke()}ctx.restore()}for(const s of shots){ctx.save();ctx.translate(s.x,s.y);ctx.fillStyle=s.col;ctx.shadowBlur=14;ctx.shadowColor=s.col;if(s.kind==='knife'){ctx.rotate(Math.atan2(s.vy,s.vx));ctx.fillRect(-10,-2,20,4)}else if(s.kind==='boom'){ctx.rotate(s.age*10);ctx.strokeStyle=s.col;ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,0,s.r,-2.5,2.5);ctx.stroke()}else{ctx.beginPath();ctx.arc(0,0,s.r,0,TAU);ctx.fill()}ctx.restore()}drawEnemies();drawPet();drawHero();const ow=weapons.orbit;if(ow){const n=Math.min(7,2+Math.floor(ow.lv/2)+(ow.evolved?2:0)),rad=62+ow.lv*5+(ow.evolved?24:0);for(let i=0;i<n;i++){const a=ow.spin+i*TAU/n,ox=player.x+Math.cos(a)*rad,oy=player.y+Math.sin(a)*rad;ctx.save();ctx.translate(ox,oy);ctx.rotate(a);ctx.fillStyle=WEAPONS.orbit.col;ctx.shadowBlur=15;ctx.shadowColor=WEAPONS.orbit.col;ctx.beginPath();ctx.moveTo(0,-12);ctx.lineTo(6,8);ctx.lineTo(0,5);ctx.lineTo(-6,8);ctx.closePath();ctx.fill();ctx.restore()}}for(const f of fx){ctx.globalAlpha=clamp(f.l/f.m,0,1);ctx.fillStyle=f.col;ctx.beginPath();ctx.arc(f.x,f.y,f.r,0,TAU);ctx.fill();ctx.globalAlpha=1}ctx.restore();if(screenFlash>0){ctx.fillStyle=`rgba(255,235,160,${screenFlash*.55})`;ctx.fillRect(0,0,W,H)}const w=WORLDS[worldIndex()];ctx.fillStyle='rgba(0,0,0,.35)';rr(W/2-88,H-58,176,30,15);ctx.fill();ctx.fillStyle=w.accent;ctx.font='700 13px system-ui';ctx.textAlign='center';ctx.fillText(`${w.name} · ${tr('Волна','Wave')} ${wave()}`,W/2,H-38)}
function draw(){if(!player){ctx.fillStyle='#081421';ctx.fillRect(0,0,W,H);return}drawGround();drawCombat()}
function loop(now){const dt=Math.min(.033,(now-last)/1000||0);last=now;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);

addEventListener('keydown',e=>{keys[e.code]=1;if(e.code==='Escape'&&state==='play'){paused=true;state='pause';show('pause')}});addEventListener('keyup',e=>keys[e.code]=0);
canvas.addEventListener('pointerdown',e=>{if(state!=='play')return;joystick.on=true;joystick.id=e.pointerId;joystick.x=e.clientX;joystick.y=e.clientY;joystick.dx=joystick.dy=0;$('joystick').classList.remove('hidden');$('joystick').style.left=(e.clientX-55)+'px';$('joystick').style.top=(e.clientY-55)+'px';canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!joystick.on||e.pointerId!==joystick.id)return;let dx=e.clientX-joystick.x,dy=e.clientY-joystick.y,d=Math.hypot(dx,dy),m=Math.min(44,d);joystick.dx=d?dx/d:0;joystick.dy=d?dy/d:0;$('stick').style.transform=`translate(${joystick.dx*m}px,${joystick.dy*m}px)`});function joyEnd(e){if(e.pointerId!==joystick.id)return;joystick.on=false;joystick.dx=joystick.dy=0;$('joystick').classList.add('hidden');$('stick').style.transform='translate(0,0)'}canvas.addEventListener('pointerup',joyEnd);canvas.addEventListener('pointercancel',joyEnd);

$('playBtn').onclick=()=>{state='select';show('select');selectionCards()};$('backBtn').onclick=menu;$('startBtn').onclick=startRun;$('metaBtn').onclick=()=>{state='meta';show('meta');meta()};$('metaBackBtn').onclick=menu;$('howBtn').onclick=()=>{state='help';show('help')};$('helpBackBtn').onclick=menu;$('pauseBtn').onclick=()=>{if(state==='play'){paused=true;state='pause';show('pause')}};$('resumeBtn').onclick=()=>{paused=false;state='play';show('play');last=performance.now()};$('quitBtn').onclick=()=>finish(false,true);$('retryBtn').onclick=startRun;$('resultMenuBtn').onclick=menu;$('reviveBtn').onclick=async()=>{const ok=await bridge.rewarded();if(ok){revived=true;player.hp=player.max*.55;player.inv=2.5;paused=false;state='play';show('play');last=performance.now()}else toast(tr('Реклама недоступна','Ad unavailable'))};$('skipReviveBtn').onclick=()=>finish(false);function toggleSound(){save.settings.muted=!save.settings.muted;persist();$('soundBtn').textContent=save.settings.muted?'🔇 ЗВУК':'🔊 ЗВУК';$('pauseSoundBtn').textContent=$('soundBtn').textContent}$('soundBtn').onclick=toggleSound;$('pauseSoundBtn').onclick=toggleSound;$('langBtn').onclick=()=>{lang=lang==='ru'?'en':'ru';localize()};

localize();menu();
