import{YandexBridge}from'./yandex.js';
const $=x=>document.getElementById(x),c=$('game'),g=c.getContext('2d'),b=new YandexBridge();await b.init();let W,H,D=1;
function resize(){D=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;c.width=W*D;c.height=H*D;c.style.width=W+'px';c.style.height=H+'px';g.setTransform(D,0,0,D,0,0)}addEventListener('resize',resize);resize();document.addEventListener('contextmenu',e=>e.preventDefault());
const L={ru:{play:'ИГРАТЬ',meta:'УЛУЧШЕНИЯ',how:'КАК ИГРАТЬ',hero:'Выбери героя',pet:'Выбери питомца',fight:'В БОЙ',back:'НАЗАД',up:'Новый уровень',pick:'Выбери усиление',pause:'Пауза',resume:'ПРОДОЛЖИТЬ',menu:'В МЕНЮ',revive:'ВОСКРЕСНУТЬ',finish:'ЗАКОНЧИТЬ ЗАБЕГ',retry:'ЕЩЁ РАЗ',metaTitle:'Постоянные улучшения',help:'Как играть',ok:'ПОНЯТНО',best:'Лучшее время',runs:'Забегов',wallet:'Кристаллы',win:'Победа!',lose:'Забег окончен',time:'Время',lvl:'Уровень',kills:'Врагов',earned:'Кристаллов',wave:'ВОЛНА',sound:'🔊 ЗВУК',mute:'🔇 ЗВУК',new:'НОВОЕ',passive:'ПАССИВ',evolve:'ЭВОЛЮЦИЯ',locked:'Откроется после',unavail:'Реклама недоступна',ach:'Достижение'},en:{play:'PLAY',meta:'UPGRADES',how:'HOW TO PLAY',hero:'Choose a hero',pet:'Choose a pet',fight:'START RUN',back:'BACK',up:'Level up',pick:'Choose an upgrade',pause:'Paused',resume:'RESUME',menu:'MAIN MENU',revive:'REVIVE',finish:'END RUN',retry:'RUN AGAIN',metaTitle:'Permanent upgrades',help:'How to play',ok:'GOT IT',best:'Best time',runs:'Runs',wallet:'Crystals',win:'Victory!',lose:'Run over',time:'Time',lvl:'Level',kills:'Enemies',earned:'Crystals',wave:'WAVE',sound:'🔊 SOUND',mute:'🔇 SOUND',new:'NEW',passive:'PASSIVE',evolve:'EVOLVE',locked:'Unlocks after',unavail:'Rewarded ad unavailable',ach:'Achievement'}};let lang=(b.lang||'ru').startsWith('ru')?'ru':'en',t=k=>L[lang][k];
const Hs=[['knight','🛡️','Рыцарь','Knight',135,180,1,0],['mage','🔮','Маг','Mage',92,178,1.22,0],['ranger','🏹','Следопыт','Ranger',102,200,1,2],['berserk','🪓','Берсерк','Berserker',126,188,1.1,5],['rogue','🗡️','Тень','Shade',92,225,1,8]].map(x=>({id:x[0],icon:x[1],ru:x[2],en:x[3],hp:x[4],speed:x[5],dmg:x[6],unlock:x[7]}));
const Ps=[['fox','🦊','Лис','Fox',0,p=>p.speed*=1.1],['owl','🦉','Сова','Owl',0,p=>p.xpb*=1.15],['slime','🟢','Слайм','Slime',3,p=>p.regen+=1],['dragon','🐉','Дракон','Dragon',6,p=>p.dmg*=1.12],['wolf','🐺','Волк','Wolf',9,p=>p.rate*=1.12]].map(x=>({id:x[0],icon:x[1],ru:x[2],en:x[3],unlock:x[4],apply:x[5]}));
const WD=[['bolt','✦','Звёздный болт','Star Bolt',.68],['spread','➤','Тройной залп','Triple Volley',1.05],['orbit','◉','Орбитальные клинки','Orbit Blades',99],['nova','✹','Солнечная нова','Solar Nova',2.7],['comet','⌁','Комета','Comet',1.45],['beam','━','Луч','Beam',1.8],['mine','⬢','Грави-мина','Grav Mine',2.25],['frost','❄','Морозный осколок','Frost Shard',1.18],['blade','✣','Клинки тени','Shadow Blades',.9],['zap','ϟ','Цепная молния','Chain Lightning',1.55]].map(x=>({id:x[0],icon:x[1],ru:x[2],en:x[3],cd:x[4]}));
const SU=[['dmg','Сила','Power',p=>p.dmg*=1.15],['rate','Темп','Tempo',p=>p.rate*=1.12],['hp','Живучесть','Vitality',p=>{p.max+=20;p.hp=Math.min(p.max,p.hp+25)}],['speed','Скорость','Speed',p=>p.speed*=1.1],['mag','Магнит','Magnet',p=>p.pick+=40],['crit','Удача','Luck',p=>p.crit=Math.min(.65,p.crit+.07)],['regen','Восстановление','Recovery',p=>p.regen+=.8],['armor','Броня','Armor',p=>p.armor=Math.min(.55,p.armor+.07)]];
const MT=[['power','⚔️','Сила','Power',8],['health','❤','Здоровье','Health',8],['speed','⚡','Скорость','Speed',6],['fortune','✦','Удача','Fortune',6]];
const DEF={best:0,runs:0,kills:0,currency:0,wins:0,meta:{power:0,health:0,speed:0,fortune:0},ach:{},settings:{muted:false}};let save=Object.assign({},DEF,await b.load()||{});save.meta=Object.assign({},DEF.meta,save.meta||{});save.ach=save.ach||{};save.settings=Object.assign({},DEF.settings,save.settings||{});
let state='menu',hero=null,pet=null,p=null,E=[],B=[],X=[],A=[],P=[],keys={},joy={on:false,id:0,x:0,y:0,dx:0,dy:0},last=performance.now(),time=0,spawn=0,boss=0,kills=0,level=1,xp=0,need=18,coins=0,revived=false,paused=false,shake=0,music=0,audio=null,platform=0;
const nm=o=>o[lang]||o.ru,fmt=s=>`${String(s/60|0).padStart(2,'0')}:${String(s%60|0).padStart(2,'0')}`,persist=()=>b.save(save);
function snd(f=440,d=.05,v=.02,type='sine'){if(save.settings.muted)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();let o=audio.createOscillator(),q=audio.createGain();o.type=type;o.frequency.value=f;q.gain.setValueAtTime(v,audio.currentTime);q.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(q);q.connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch{}}
function audioOff(){try{audio?.suspend()}catch{}}function audioOn(){try{if(!save.settings.muted)audio?.resume()}catch{}}function toast(s){$('toast').textContent=s;$('toast').classList.remove('hidden');clearTimeout(toast.i);toast.i=setTimeout(()=>$('toast').classList.add('hidden'),1800)}
function ach(id,ru,en){if(save.ach[id])return;save.ach[id]=1;persist();toast(`${t('ach')}: ${lang==='ru'?ru:en}`)}
function show(id){['menu','select','upgrade','pause','revive','result','meta','help'].forEach(x=>$(x).classList.toggle('hidden',x!==id));$('hud').classList.toggle('hidden',!['play','upgrade','pause','revive'].includes(id));if(id!=='play')$('joystick').classList.add('hidden')}
function ui(){[['playBtn','play'],['metaBtn','meta'],['howBtn','how'],['heroTitle','hero'],['petTitle','pet'],['startBtn','fight'],['backBtn','back'],['upgradeTitle','up'],['upgradeHint','pick'],['pauseTitle','pause'],['resumeBtn','resume'],['quitBtn','menu'],['reviveBtn','revive'],['skipReviveBtn','finish'],['retryBtn','retry'],['resultMenuBtn','menu'],['metaTitle','metaTitle'],['metaBackBtn','back'],['helpTitle','help'],['helpBackBtn','ok']].forEach(([id,k])=>$(id).textContent=t(k));$('soundBtn').textContent=$('pauseSoundBtn').textContent=save.settings.muted?t('mute'):t('sound');$('helpBody').innerHTML=lang==='ru'?'<p>WASD/стрелки или джойстик слева. Оружие стреляет автоматически. Собирай опыт, улучшай оружие и продержись 10 минут.</p>':'<p>Use WASD/arrows or the left-side joystick. Weapons fire automatically. Collect XP, upgrade weapons, and survive 10 minutes.</p>';fill();meta();if(state==='menu')menu()}
function menu(){state='menu';paused=false;show('menu');b.gameplayStop();$('bestText').textContent=`${t('best')}: ${fmt(save.best)} · ${t('runs')}: ${save.runs}`;$('walletText').textContent=`✦ ${t('wallet')}: ${save.currency}`}
function fill(){let card=(o,type)=>`<div class="card ${save.runs>=o.unlock?'':'locked'}" data-${type}="${o.id}"><div class="icon">${o.icon}</div><b>${nm(o)}</b><small>${save.runs>=o.unlock?'':`${t('locked')} ${o.unlock} ${t('runs').toLowerCase()}`}</small></div>`;$('heroes').innerHTML=Hs.map(x=>card(x,'hero')).join('');$('pets').innerHTML=Ps.map(x=>card(x,'pet')).join('');document.querySelectorAll('[data-hero]').forEach(e=>e.onclick=()=>{let h=Hs.find(x=>x.id===e.dataset.hero);if(save.runs<h.unlock)return;hero=h.id;document.querySelectorAll('[data-hero]').forEach(x=>x.classList.toggle('selected',x===e));check()});document.querySelectorAll('[data-pet]').forEach(e=>e.onclick=()=>{let q=Ps.find(x=>x.id===e.dataset.pet);if(save.runs<q.unlock)return;pet=q.id;document.querySelectorAll('[data-pet]').forEach(x=>x.classList.toggle('selected',x===e));check()});check()}
function check(){$('startBtn').disabled=!(hero&&pet)}
function meta(){if(!$('metaGrid'))return;$('metaWallet').textContent=`✦ ${t('wallet')}: ${save.currency}`;$('metaGrid').innerHTML=MT.map(m=>{let l=save.meta[m[0]]||0,c=30+l*40;return`<div class="metaCard"><b>${m[1]} ${lang==='ru'?m[2]:m[3]} · ${l}/${m[4]}</b><button data-m="${m[0]}" ${l>=m[4]||save.currency<c?'disabled':''}>${l>=m[4]?'MAX':`✦ ${c}`}</button></div>`}).join('');document.querySelectorAll('[data-m]').forEach(e=>e.onclick=()=>{let id=e.dataset.m,l=save.meta[id]||0,c=30+l*40;if(save.currency<c)return;save.currency-=c;save.meta[id]=l+1;persist();meta();snd(700)})}
function start(){let h=Hs.find(x=>x.id===hero)||Hs[0],q=Ps.find(x=>x.id===pet)||Ps[0];p={x:0,y:0,r:18,max:h.hp+save.meta.health*8,hp:h.hp+save.meta.health*8,speed:h.speed*(1+save.meta.speed*.02),dmg:h.dmg*(1+save.meta.power*.05),rate:1,pick:95,xpb:1,crit:.05+save.meta.fortune*.02,regen:0,armor:0,weapons:{bolt:{lv:1,t:.1}},color:['#75a7ff','#bd7dff','#68e39a','#ff6b67','#ffd15c'][Hs.indexOf(h)]};q.apply(p);if(h.id==='rogue')p.crit+=.08;E=[];B=[];X=[];A=[];P=[];time=0;spawn=.2;boss=0;kills=0;level=1;xp=0;need=18;coins=0;revived=false;paused=false;music=.2;state='play';show('play');b.gameplayStart();audioOn();last=performance.now();strip()}
function pause(){if(!['play','pause'].includes(state))return;paused=!paused;state=paused?'pause':'play';show(state);paused?(b.gameplayStop(),audioOff()):(b.gameplayStart(),audioOn(),last=performance.now())}
function end(win=false,quit=false){if(!p)return menu();state='result';paused=true;b.gameplayStop();audioOff();save.best=Math.max(save.best,time);save.runs++;save.kills+=kills;save.currency+=coins;save.wins+=win?1:0;persist();b.submitScore('arena_survival',time*100+kills*2|0);if(save.runs===1)ach('first','Первый полёт','First flight');if(kills>=100)ach('100','Охотник','Hunter');if(win)ach('win','Выживший','Survivor');if(quit)return menu();$('resultTitle').textContent=win?t('win'):t('lose');$('resultStats').innerHTML=`<p>${t('time')}: <b>${fmt(time)}</b></p><p>${t('lvl')}: <b>${level}</b></p><p>${t('kills')}: <b>${kills}</b></p><p>${t('earned')}: <b>✦ ${coins}</b></p>`;fill();show('result');if(!quit&&save.runs%3===0)b.fullscreen()}
function die(){if(!revived&&b.ysdk?.adv?.showRewardedVideo){paused=true;state='revive';b.gameplayStop();audioOff();show('revive')}else end()}
async function revive(){$('reviveBtn').disabled=true;let ok=await b.rewarded();$('reviveBtn').disabled=false;if(!ok)return toast(t('unavail'));revived=true;p.hp=p.max*.55;E=E.filter(e=>Math.hypot(e.x-p.x,e.y-p.y)>180);paused=false;state='play';show('play');b.gameplayStart();audioOn();last=performance.now()}
function enemy(isBoss=false){let a=Math.random()*6.283,d=Math.max(W,H)*.7+100,s=1+time/190,e={x:p.x+Math.cos(a)*d,y:p.y+Math.sin(a)*d,r:14+Math.random()*6,hp:24*s,spd:60+Math.random()*22,hit:0,dmg:10,color:'#ff6577',slow:0,boss:isBoss};if(time>90&&Math.random()<.15){e.r=24;e.hp=70*s;e.spd=44;e.color='#a46cff'}if(time>160&&Math.random()<.13){e.r=10;e.hp=18*s;e.spd=110;e.color='#ff9f5b'}if(isBoss){e.r=42;e.hp=700*(1+boss*.4);e.spd=48;e.dmg=24;e.color='#ffbf4d'}e.max=e.hp;E.push(e)}
function near(range=500,from=p){let r=null,z=range*range;for(let e of E){let x=e.x-from.x,y=e.y-from.y,d=x*x+y*y;if(d<z)z=d,r=e}return r}function hit(e,d){if(!e)return;e.hp-=d;e.hit=.08;if(e.hp<=0)kill(e)}function kill(e){let i=E.indexOf(e);if(i<0)return;kills++;X.push({x:e.x,y:e.y,v:e.boss?30:5,r:e.boss?10:6});if(e.boss)coins+=20+boss*4;else if(Math.random()<.08)coins++;burst(e.x,e.y,e.color,e.boss?18:7);E.splice(i,1);snd(e.boss?150:100,.04,.015,'square')}
function dmg(base){return base*p.dmg*(Math.random()<p.crit?2:1)}function bullet(a,sp,dam,r=5,life=1.2,color='#ffe273',extra={}){B.push({x:p.x,y:p.y,vx:Math.cos(a)*sp,vy:Math.sin(a)*sp,d:dam,r,life,color,seen:new Set(),...extra})}
function fire(id,w){let e=near(500),lv=w.lv,ev=lv>=6,a=e?Math.atan2(e.y-p.y,e.x-p.x):0;if(id!=='nova'&&id!=='mine'&&id!=='orbit'&&!e)return;if(id==='bolt'){for(let i=0,n=ev?3:1;i<n;i++)bullet(a+(i-(n-1)/2)*.12,580,dmg(22+lv*5),5+lv*.4,1.2,'#ffe273',{pierce:(lv/3|0)})}else if(id==='spread'){for(let i=0,n=3+(lv/2|0)+(ev?2:0);i<n;i++)bullet(a+(i-(n-1)/2)*.15,520,dmg(11+lv*3),4,1,'#8ff5ff')}else if(id==='nova'){for(let i=0,n=10+lv*2+(ev?6:0);i<n;i++)bullet(i/n*6.283,410,dmg(9+lv*3),4,1.1,'#ff9bd7')}else if(id==='comet')bullet(a,430,dmg(28+lv*5),8,2,'#ffb06e',{back:true,age:0,pierce:4+lv});else if(id==='beam'){A.push({type:'beam',x:p.x,y:p.y,a,life:.15,range:430+lv*35});for(let q of[...E]){let dx=q.x-p.x,dy=q.y-p.y,on=dx*Math.cos(a)+dy*Math.sin(a),per=Math.abs(-dx*Math.sin(a)+dy*Math.cos(a));if(on>0&&on<430+lv*35&&per<12+lv*2+q.r)hit(q,dmg(32+lv*8))}}else if(id==='mine')A.push({type:'mine',x:p.x+(Math.random()-.5)*220,y:p.y+(Math.random()-.5)*220,life:3,arm:.4,r:ev?150:100,d:dmg(38+lv*8)});else if(id==='frost')bullet(a,480,dmg(18+lv*4),6,1.35,'#91cfff',{slow:ev?2.1:1.2,pierce:1});else if(id==='blade'){for(let i=0,n=2+(lv/2|0)+(ev?2:0);i<n;i++)bullet(a+(i-(n-1)/2)*.1,690,dmg(13+lv*4),4,.7,'#fff',{pierce:2})}else if(id==='zap'){let q=e,seen=new Set(),pts=[{x:p.x,y:p.y}];for(let i=0;i<2+(lv/2|0)+(ev?3:0)&&q;i++){pts.push({x:q.x,y:q.y});seen.add(q);hit(q,dmg(18+lv*5));q=E.find(x=>!seen.has(x)&&Math.hypot(x.x-pts.at(-1).x,x.y-pts.at(-1).y)<150)}A.push({type:'zap',pts,life:.12})}snd(420+lv*30,.035,.012,'triangle')}
function weapons(dt){for(let[id,w]of Object.entries(p.weapons)){if(id==='orbit')continue;w.t-=dt;if(w.t<=0){fire(id,w);w.t=WD.find(x=>x.id===id).cd/Math.max(.4,p.rate)}}let o=p.weapons.orbit;if(o){let n=2+(o.lv/2|0)+(o.lv>=6?2:0),r=60+o.lv*7;for(let i=0;i<n;i++){let a=time*2+i/n*6.283,x=p.x+Math.cos(a)*r,y=p.y+Math.sin(a)*r;for(let e of[...E])if(Math.hypot(e.x-x,e.y-y)<e.r+8&&time-(e.oh||0)>.3)e.oh=time,hit(e,dmg(8+o.lv*3))}}}
function choices(){let a=[];for(let w of WD){let q=p.weapons[w.id];if(!q)a.push({w,id:w.id,name:nm(w),tag:t('new')});else if(q.lv<6)a.push({w,id:w.id,name:nm(w),tag:q.lv===5?t('evolve'):`LV ${q.lv+1}`})}for(let s of SU)a.push({s,id:s[0],name:lang==='ru'?s[1]:s[2],tag:t('passive')});return a.sort(()=>Math.random()-.5).slice(0,3)}
function levelup(){level++;xp-=need;need=need*1.24+7|0;paused=true;state='upgrade';b.gameplayStop();show('upgrade');$('upgradeCards').innerHTML='';for(let q of choices()){let z=document.createElement('button');z.className='upgradeCard';z.innerHTML=`<span class="tag">${q.tag}</span><b>${q.name}</b>`;z.onclick=()=>{if(q.w){if(p.weapons[q.id])p.weapons[q.id].lv++;else p.weapons[q.id]={lv:1,t:.2}}else SU.find(x=>x[0]===q.id)[3](p);paused=false;state='play';show('play');b.gameplayStart();last=performance.now();strip();snd(700)};$('upgradeCards').appendChild(z)}}function strip(){$('weaponStrip').innerHTML=Object.entries(p.weapons).map(([id,w])=>`<span class="weaponChip">${WD.find(x=>x.id===id).icon} ${w.lv>=6?'★':w.lv}</span>`).join('')}
function burst(x,y,color,n=8){for(let i=0;i<n;i++){let a=Math.random()*6.283,s=50+Math.random()*130;P.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.4,color})}}
function update(dt){if(state!=='play'||paused)return;time+=dt;if(time>=600)return end(true);music-=dt;if(music<=0){music=1.5;snd([110,131,147,165,196][time/6%5|0],.35,.006)}let mx=(keys.ArrowRight||keys.d?1:0)-(keys.ArrowLeft||keys.a?1:0),my=(keys.ArrowDown||keys.s?1:0)-(keys.ArrowUp||keys.w?1:0);if(joy.on)mx=joy.dx,my=joy.dy;let ml=Math.hypot(mx,my)||1;p.x+=mx/ml*p.speed*dt;p.y+=my/ml*p.speed*dt;p.hp=Math.min(p.max,p.hp+p.regen*dt);weapons(dt);spawn-=dt;if(spawn<=0){enemy();if(time>120&&Math.random()<.3)enemy();spawn=Math.max(.16,.7-time/1000)}let want=time/120|0;if(want>boss){boss=want;enemy(true)}for(let e of E){let dx=p.x-e.x,dy=p.y-e.y,l=Math.hypot(dx,dy)||1;e.slow=Math.max(0,e.slow-dt);e.x+=dx/l*e.spd*(e.slow?.58:1)*dt;e.y+=dy/l*e.spd*(e.slow?.58:1)*dt;e.hit=Math.max(0,e.hit-dt);if(l<p.r+e.r){p.hp-=e.dmg*(1-p.armor)*dt;shake=5;if(p.hp<=0)return die()}}for(let i=B.length-1;i>=0;i--){let q=B[i];q.age=(q.age||0)+dt;if(q.back&&q.age>1){let dx=p.x-q.x,dy=p.y-q.y,l=Math.hypot(dx,dy)||1;q.vx=dx/l*520;q.vy=dy/l*520}q.x+=q.vx*dt;q.y+=q.vy*dt;q.life-=dt;let rm=q.life<=0;for(let e of[...E])if(!rm&&!q.seen.has(e)&&Math.hypot(q.x-e.x,q.y-e.y)<q.r+e.r){q.seen.add(e);hit(e,q.d);if(q.slow)e.slow=Math.max(e.slow,q.slow);if(q.pierce>0)q.pierce--;else if(!q.back)rm=true}if(rm)B.splice(i,1)}for(let i=A.length-1;i>=0;i--){let a=A[i];a.life-=dt;if(a.type==='mine'){a.arm-=dt;if(a.arm<=0&&(E.some(e=>Math.hypot(e.x-a.x,e.y-a.y)<20+e.r)||a.life<=0)){for(let e of[...E])if(Math.hypot(e.x-a.x,e.y-a.y)<a.r+e.r)hit(e,a.d);burst(a.x,a.y,'#8fe0ff',14);a.life=-1}}if(a.life<=0)A.splice(i,1)}for(let i=X.length-1;i>=0;i--){let q=X[i],dx=p.x-q.x,dy=p.y-q.y,l=Math.hypot(dx,dy);if(l<p.pick){q.x+=dx/(l||1)*350*dt;q.y+=dy/(l||1)*350*dt}if(l<p.r+12){xp+=q.v*(p.xpb||1);X.splice(i,1);if(xp>=need)levelup()}}for(let i=P.length-1;i>=0;i--){let q=P[i];q.x+=q.vx*dt;q.y+=q.vy*dt;q.life-=dt;if(q.life<=0)P.splice(i,1)}shake=Math.max(0,shake-20*dt);$('hpText').textContent=`❤ ${Math.ceil(p.hp)}/${Math.ceil(p.max)}`;$('lvlText').textContent=`${t('lvl')} ${level} · ${t('wave')} ${1+(time/60|0)}`;$('timeText').textContent=fmt(time);$('coinText').textContent=`✦ ${coins}`;$('xpFill').style.width=Math.min(100,xp/need*100)+'%'}
function draw(){g.clearRect(0,0,W,H);g.fillStyle='#090f1c';g.fillRect(0,0,W,H);g.strokeStyle='rgba(125,174,255,.05)';for(let x=(-((p?.x||0)%64));x<W;x+=64){g.beginPath();g.moveTo(x,0);g.lineTo(x,H);g.stroke()}for(let y=(-((p?.y||0)%64));y<H;y+=64){g.beginPath();g.moveTo(0,y);g.lineTo(W,y);g.stroke()}if(!p||!['play','upgrade','pause','revive','result'].includes(state))return;g.save();if(shake)g.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);g.translate(W/2-p.x,H/2-p.y);for(let x of X){g.fillStyle='#64e8ff';g.fillRect(x.x-4,x.y-4,8,8)}for(let a of A){g.strokeStyle='#c8f5ff';if(a.type==='beam'){g.lineWidth=12;g.beginPath();g.moveTo(a.x,a.y);g.lineTo(a.x+Math.cos(a.a)*a.range,a.y+Math.sin(a.a)*a.range);g.stroke()}if(a.type==='zap'){g.lineWidth=3;g.beginPath();a.pts.forEach((q,i)=>i?g.lineTo(q.x,q.y):g.moveTo(q.x,q.y));g.stroke()}if(a.type==='mine'){g.beginPath();g.arc(a.x,a.y,10,0,6.283);g.stroke()}}for(let q of B){g.fillStyle=q.color;g.beginPath();g.arc(q.x,q.y,q.r,0,6.283);g.fill()}let o=p.weapons.orbit;if(o){let n=2+(o.lv/2|0)+(o.lv>=6?2:0),r=60+o.lv*7;for(let i=0;i<n;i++){let a=time*2+i/n*6.283;g.fillStyle='#a7c5ff';g.fillRect(p.x+Math.cos(a)*r-4,p.y+Math.sin(a)*r-8,8,16)}}for(let e of E){g.fillStyle=e.hit?'#fff':e.color;g.beginPath();g.arc(e.x,e.y,e.r,0,6.283);g.fill();if(e.boss){g.fillStyle='#222';g.fillRect(e.x-e.r,e.y-e.r-12,e.r*2,6);g.fillStyle='#ffd45a';g.fillRect(e.x-e.r,e.y-e.r-12,e.r*2*e.hp/e.max,6)}}for(let q of P){g.globalAlpha=q.life/.4;g.fillStyle=q.color;g.fillRect(q.x-2,q.y-2,4,4)}g.globalAlpha=1;g.fillStyle=p.color;g.shadowColor=p.color;g.shadowBlur=18;g.beginPath();g.arc(p.x,p.y,p.r,0,6.283);g.fill();g.restore()}
function loop(n){let dt=Math.min(.033,(n-last)/1000||0);last=n;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
$('playBtn').onclick=()=>{state='select';show('select')};$('backBtn').onclick=menu;$('howBtn').onclick=()=>{state='help';show('help')};$('helpBackBtn').onclick=menu;$('metaBtn').onclick=()=>{state='meta';meta();show('meta')};$('metaBackBtn').onclick=menu;$('startBtn').onclick=start;$('pauseBtn').onclick=pause;$('resumeBtn').onclick=pause;$('quitBtn').onclick=()=>end(false,true);$('retryBtn').onclick=start;$('resultMenuBtn').onclick=menu;$('reviveBtn').onclick=revive;$('skipReviveBtn').onclick=()=>end();$('soundBtn').onclick=$('pauseSoundBtn').onclick=()=>{save.settings.muted=!save.settings.muted;persist();ui()};$('langBtn').onclick=()=>{lang=lang==='ru'?'en':'ru';ui()};
addEventListener('keydown',e=>{keys[e.key]=1;if((e.key==='Escape'||e.key.toLowerCase()==='p')&&['play','pause'].includes(state))pause()});addEventListener('keyup',e=>keys[e.key]=0);c.addEventListener('touchstart',e=>{if(state!=='play'||paused)return;e.preventDefault();let q=e.changedTouches[0];if(q.clientX<W*.62){joy={on:true,id:q.identifier,x:q.clientX,y:q.clientY,dx:0,dy:0};$('joystick').style.left=q.clientX-54+'px';$('joystick').style.top=q.clientY-54+'px';$('joystick').classList.remove('hidden')}},{passive:false});c.addEventListener('touchmove',e=>{if(!joy.on)return;e.preventDefault();for(let q of e.changedTouches)if(q.identifier===joy.id){let x=q.clientX-joy.x,y=q.clientY-joy.y,l=Math.hypot(x,y),m=40;if(l>m)x*=m/l,y*=m/l;joy.dx=x/m;joy.dy=y/m;$('stick').style.transform=`translate(${x}px,${y}px)`}},{passive:false});function touchEnd(e){for(let q of e.changedTouches)if(q.identifier===joy.id){joy.on=false;joy.dx=joy.dy=0;$('stick').style.transform='';$('joystick').classList.add('hidden')}}c.addEventListener('touchend',touchEnd);c.addEventListener('touchcancel',touchEnd);
function sysPause(){platform=state==='play'?1:platform;if(state==='play'){paused=true;state='pause';show('pause');b.gameplayStop()}audioOff()}document.addEventListener('visibilitychange',()=>{if(document.hidden)sysPause()});addEventListener('blur',sysPause);try{b.ysdk?.on?.('game_api_pause',sysPause);b.ysdk?.on?.('game_api_resume',()=>{if(platform&&state==='pause'){platform=0;paused=false;state='play';show('play');b.gameplayStart();last=performance.now()}audioOn()})}catch{}
ui();
