const cv=document.getElementById('game'),ctx=cv.getContext('2d');let W=0,H=0,D=1,last=performance.now(),state='menu',t=0,kills=0,xp=0,level=1,shake=0,hitstop=0,boss=null;const keys={},shots=[],enemies=[],fx=[],loot=[],props=[];let p={x:0,y:0,hp:328,max:328,sp:235,a:0,fire:0,inv:0};
function resize(){D=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;cv.width=W*D;cv.height=H*D;cv.style.width=W+'px';cv.style.height=H+'px';ctx.setTransform(D,0,0,D,0,0)}addEventListener('resize',resize);resize();
const R=(a,b)=>a+Math.random()*(b-a),TAU=Math.PI*2;for(let i=0;i<120;i++)props.push({x:R(-1800,1800),y:R(-1800,1800),k:Math.random()<.45?'crystal':Math.random()<.55?'bush':'ruin',s:R(.7,1.35)});
function start(){state='play';document.getElementById('menu').classList.add('hidden');document.getElementById('hud').classList.remove('hidden');p={x:0,y:0,hp:328,max:328,sp:235,a:0,fire:0,inv:0};enemies.length=shots.length=fx.length=loot.length=0;t=kills=xp=0;level=1;boss=null;for(let i=0;i<10;i++)spawn();}
function spawn(type){let a=R(0,TAU),d=R(500,850),k=type||(['hound','crawler','brute'][Math.random()*3|0]);let hp=k==='brute'?150:k==='crawler'?75:95;enemies.push({x:p.x+Math.cos(a)*d,y:p.y+Math.sin(a)*d,k,hp,max:hp,sp:k==='brute'?48:k==='crawler'?92:74,r:k==='brute'?28:20,hit:0,phase:R(0,TAU)});}
function spawnBoss(){boss={x:p.x+520,y:p.y-80,hp:2400,max:2400,r:74,phase:0,cd:2};}
function burst(x,y,c,n=10){for(let i=0;i<n;i++){let a=R(0,TAU),s=R(40,260);fx.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,l:R(.25,.65),m:.65,c,r:R(2,6)})}}
function fire(){let target=[...enemies,boss].filter(Boolean).sort((a,b)=>(a.x-p.x)**2+(a.y-p.y)**2-((b.x-p.x)**2+(b.y-p.y)**2))[0];if(!target)return;let a=Math.atan2(target.y-p.y,target.x-p.x);p.a=a;shots.push({x:p.x+Math.cos(a)*28,y:p.y+Math.sin(a)*28,vx:Math.cos(a)*650,vy:Math.sin(a)*650,l:1.2,a});burst(p.x+Math.cos(a)*35,p.y+Math.sin(a)*35,'#ffb52e',5)}
function damage(e,d){e.hp-=d;e.hit=.09;shake=Math.max(shake,5);hitstop=.025;burst(e.x,e.y,'#75eaff',8);if(e.hp<=0){if(e===boss){burst(e.x,e.y,'#b05cff',55);boss=null;loot.push({x:e.x,y:e.y,k:'chest'});}else{enemies.splice(enemies.indexOf(e),1);kills++;xp+=8;loot.push({x:e.x,y:e.y,k:'crystal'});if(enemies.length<14)spawn();}}}
function update(dt){if(state!=='play')return;if(hitstop>0){hitstop-=dt;return}t+=dt;let dx=(keys.d||keys.ArrowRight?1:0)-(keys.a||keys.ArrowLeft?1:0),dy=(keys.s||keys.ArrowDown?1:0)-(keys.w||keys.ArrowUp?1:0),m=Math.hypot(dx,dy)||1;p.x+=dx/m*p.sp*dt;p.y+=dy/m*p.sp*dt;if(dx||dy)p.a=Math.atan2(dy,dx);p.fire-=dt;if(p.fire<=0){fire();p.fire=.28}if(!boss&&t>35)spawnBoss();if(enemies.length<12&&Math.random()<dt*3)spawn();
for(let e of enemies){let a=Math.atan2(p.y-e.y,p.x-e.x),d=Math.hypot(p.x-e.x,p.y-e.y);e.x+=Math.cos(a)*e.sp*dt;e.y+=Math.sin(a)*e.sp*dt;e.phase+=dt*5;e.hit-=dt;if(d<e.r+17&&p.inv<=0){p.hp-=e.k==='brute'?18:9;p.inv=.5;shake=10;burst(p.x,p.y,'#ff554f',16)}}if(boss){let e=boss,a=Math.atan2(p.y-e.y,p.x-e.x),d=Math.hypot(p.x-e.x,p.y-e.y);e.phase+=dt;e.cd-=dt;e.x+=Math.cos(a)*34*dt;e.y+=Math.sin(a)*34*dt;if(d<90&&p.inv<=0){p.hp-=28;p.inv=.7;shake=14}if(e.cd<0){e.cd=2.2;for(let q=0;q<12;q++){let aa=q/12*TAU;shots.push({x:e.x,y:e.y,vx:Math.cos(aa)*180,vy:Math.sin(aa)*180,l:3,enemy:true,a:aa})}}}p.inv-=dt;
for(let s of [...shots]){s.x+=s.vx*dt;s.y+=s.vy*dt;s.l-=dt;if(s.enemy){if(Math.hypot(s.x-p.x,s.y-p.y)<18&&p.inv<=0){p.hp-=12;p.inv=.4;s.l=0;burst(p.x,p.y,'#ff4f80',10)}}else{for(let e of [...enemies,boss].filter(Boolean))if(Math.hypot(s.x-e.x,s.y-e.y)<e.r+8){damage(e,42);s.l=0;break}}if(s.l<=0)shots.splice(shots.indexOf(s),1)}for(let f of fx){f.x+=f.vx*dt;f.y+=f.vy*dt;f.vx*=.96;f.vy*=.96;f.l-=dt}for(let i=fx.length-1;i>=0;i--)if(fx[i].l<=0)fx.splice(i,1);if(xp>=level*32){xp=0;level++;burst(p.x,p.y,'#ffe45b',35)}if(p.hp<=0)start();}
function poly(x,y,r,n,c,rot=0){ctx.fillStyle=c;ctx.beginPath();for(let i=0;i<n;i++){let a=rot+i/n*TAU;ctx.lineTo(x+Math.cos(a)*r,y+Math.sin(a)*r)}ctx.closePath();ctx.fill()}
function shadow(x,y,rx,ry){ctx.fillStyle='#07101788';ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,TAU);ctx.fill()}
function crystal(x,y,s=1,c='#7b55ff'){shadow(x,y+15*s,18*s,7*s);poly(x,y,17*s,5,c,-Math.PI/2);poly(x+11*s,y+7*s,10*s,5,'#49dfff',-.8);ctx.fillStyle='#e2fbff';ctx.fillRect(x-3*s,y-14*s,4*s,17*s)}
function hero(x,y){shadow(x,y+23,24,9);ctx.save();ctx.translate(x,y);let bob=Math.sin(t*10)*2;ctx.translate(0,bob);ctx.fillStyle='#121b2d';ctx.beginPath();ctx.ellipse(0,10,18,23,0,0,TAU);ctx.fill();ctx.fillStyle='#2e91b8';ctx.fillRect(-16,2,32,17);ctx.fillStyle='#d8a47c';ctx.beginPath();ctx.arc(0,-14,12,0,TAU);ctx.fill();ctx.fillStyle='#eaf8ff';for(let i=0;i<7;i++)poly(-13+i*4,-23-R(0,2),8,3,'#eaf8ff',i*.7);ctx.strokeStyle='#06101d';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(0,3);ctx.lineTo(Math.cos(p.a)*34,3+Math.sin(p.a)*34);ctx.stroke();ctx.strokeStyle='#48dfff';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle='#152235';ctx.save();ctx.translate(Math.cos(p.a)*30,Math.sin(p.a)*30);ctx.rotate(p.a);ctx.fillRect(0,-7,31,14);ctx.fillStyle='#54e8ff';ctx.fillRect(17,-4,21,5);ctx.restore();ctx.restore()}
function enemy(e,x,y){shadow(x,y+e.r*.65,e.r*.9,e.r*.35);let hit=e.hit>0?'#fff':e.k==='hound'?'#22253b':e.k==='crawler'?'#273448':'#30283c';ctx.fillStyle=hit;ctx.beginPath();ctx.ellipse(x,y,e.r*1.05,e.r*.78,0,0,TAU);ctx.fill();if(e.k==='hound'){ctx.beginPath();ctx.moveTo(x-e.r,y-4);ctx.lineTo(x-e.r-18,y-13);ctx.lineTo(x-e.r-12,y+4);ctx.fill();for(let i=-1;i<=1;i++)crystal(x+i*10,y-e.r*.55,.42,'#875cff')}else if(e.k==='crawler'){for(let i=-1;i<=1;i+=2){ctx.strokeStyle='#11182a';ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(x+i*8,y+5);ctx.lineTo(x+i*22,y+20);ctx.stroke()}crystal(x,y-e.r*.45,.55,'#49dfff')}else{ctx.fillStyle='#151828';ctx.fillRect(x-e.r*.8,y-5,e.r*1.6,e.r);crystal(x,y-e.r*.6,.7,'#a84cff')}ctx.fillStyle='#ff526e';ctx.fillRect(x+e.r*.45,y-5,5,5)}
function drawBoss(e,x,y){shadow(x,y+55,72,25);ctx.fillStyle='#1a1b2b';ctx.beginPath();ctx.ellipse(x,y+10,68,58,0,0,TAU);ctx.fill();ctx.fillStyle='#30344b';for(let i=0;i<5;i++){let a=i/5*TAU;ctx.beginPath();ctx.arc(x+Math.cos(a)*45,y+10+Math.sin(a)*30,25,0,TAU);ctx.fill()}for(let i=0;i<7;i++){let a=-2.8+i*.55;crystal(x+Math.cos(a)*52,y-5+Math.sin(a)*45,R(.8,1.25),'#984cff')}crystal(x,y-32,1.8,'#55dcff');ctx.fillStyle='#ff4774';ctx.fillRect(x-18,y+3,8,8);ctx.fillRect(x+10,y+3,8,8)}
function world(){let ox=W/2-p.x,oy=H/2-p.y,sx=shake?R(-shake,shake):0,sy=shake?R(-shake,shake):0;shake*=.86;ctx.save();ctx.translate(sx,sy);let g=64;for(let yy=Math.floor((p.y-H/2)/g)*g;yy<p.y+H/2+g;yy+=g)for(let xx=Math.floor((p.x-W/2)/g)*g;xx<p.x+W/2+g;xx+=g){let n=Math.sin(xx*.017)+Math.cos(yy*.019);ctx.fillStyle=n>.5?'#243b31':n<-.7?'#162b2d':'#1d342d';ctx.fillRect(xx+ox,yy+oy,g+1,g+1);ctx.fillStyle='#33504455';ctx.fillRect(xx+ox+8,yy+oy+10,18,5)}for(let q of props){let x=q.x+ox,y=q.y+oy;if(x<-100||y<-100||x>W+100||y>H+100)continue;if(q.k==='crystal')crystal(x,y,q.s);else if(q.k==='bush'){shadow(x,y+9,25*q.s,8*q.s);for(let i=0;i<5;i++){ctx.fillStyle=i%2?'#315e3e':'#244b35';ctx.beginPath();ctx.arc(x+R(-15,15)*q.s,y+R(-10,8)*q.s,12*q.s,0,TAU);ctx.fill()}}else{ctx.fillStyle='#56636a';ctx.fillRect(x-22*q.s,y-18*q.s,44*q.s,36*q.s);ctx.fillStyle='#26343a';ctx.fillRect(x-15*q.s,y-11*q.s,30*q.s,29*q.s);crystal(x+18*q.s,y-12*q.s,.5*q.s)}}for(let l of loot){let x=l.x+ox,y=l.y+oy;if(l.k==='crystal')crystal(x,y,.45,'#42dfff');else{shadow(x,y+15,25,8);ctx.fillStyle='#6b321b';ctx.fillRect(x-20,y-14,40,28);ctx.fillStyle='#ffc53b';ctx.fillRect(x-20,y-4,40,7);ctx.fillRect(x-3,y-14,7,28)}}for(let e of enemies)enemy(e,e.x+ox,e.y+oy);if(boss)drawBoss(boss,boss.x+ox,boss.y+oy);for(let s of shots){let x=s.x+ox,y=s.y+oy;ctx.save();ctx.translate(x,y);ctx.rotate(s.a);ctx.fillStyle=s.enemy?'#ff3f9a':'#ffb72c';ctx.fillRect(-8,-3,22,6);ctx.fillStyle=s.enemy?'#c05cff':'#fff2a0';ctx.fillRect(8,-1,14,2);ctx.restore()}for(let f of fx){ctx.globalAlpha=Math.max(0,f.l/f.m);ctx.fillStyle=f.c;ctx.beginPath();ctx.arc(f.x+ox,f.y+oy,f.r,0,TAU);ctx.fill()}ctx.globalAlpha=1;hero(W/2,H/2);ctx.restore();}
function hud(){document.getElementById('hpText').textContent=`❤ ${Math.max(0,p.hp|0)}/${p.max}`;document.getElementById('lvlText').textContent=`УР. ${level}`;document.getElementById('timeText').textContent=`${String(t/60|0).padStart(2,'0')}:${String(t%60|0).padStart(2,'0')}`;document.getElementById('coinText').textContent=`☠ ${kills}`;document.getElementById('xpFill').style.width=Math.min(100,xp/(level*32)*100)+'%';if(boss){ctx.fillStyle='#090b12dd';ctx.fillRect(W*.18,70,W*.64,42);ctx.fillStyle='#ff334e';ctx.fillRect(W*.19,93,W*.62*(boss.hp/boss.max),10);ctx.fillStyle='#fff';ctx.font='bold 17px sans-serif';ctx.textAlign='center';ctx.fillText('КРИСТАЛЬНЫЙ СТРАЖ',W/2,88)}}
function frame(now){let dt=Math.min(.033,(now-last)/1000);last=now;update(dt);ctx.clearRect(0,0,W,H);if(state==='play'){world();hud()}requestAnimationFrame(frame)}requestAnimationFrame(frame);addEventListener('keydown',e=>keys[e.key]=true);addEventListener('keyup',e=>keys[e.key]=false);document.getElementById('playBtn').onclick=start;document.getElementById('pauseBtn').onclick=()=>{};document.getElementById('metaBtn').onclick=()=>{};document.getElementById('howBtn').onclick=()=>{};document.getElementById('langBtn').onclick=()=>{};