// Lightweight original procedural art for the production HTML5 build.
// No external sprite licensing and no texture download cost.
const TAU=Math.PI*2;
function circle(c,x,y,r,fill){c.fillStyle=fill;c.beginPath();c.arc(x,y,r,0,TAU);c.fill()}
function shadow(c,x,y,r){c.save();c.globalAlpha=.22;c.fillStyle='#000';c.beginPath();c.ellipse(x,y+r*.8,r*.85,r*.35,0,0,TAU);c.fill();c.restore()}
export function drawWorldDecor(c,world,player,W,H){const ox=W/2-player.x,oy=H/2-player.y;c.save();c.translate(ox,oy);const sx=Math.floor((player.x-W/2)/180)*180,sy=Math.floor((player.y-H/2)/180)*180;for(let x=sx-180;x<sx+W+360;x+=180)for(let y=sy-180;y<sy+H+360;y+=180){const seed=Math.abs((x*31+y*17)%97);if(seed%3)continue;drawProp(c,world.id,x+seed,y+(seed*7)%80)}c.restore()}
function drawProp(c,id,x,y){c.save();c.globalAlpha=.48;if(id==='emerald'){c.fillStyle='#183d28';c.beginPath();c.moveTo(x,y-32);c.lineTo(x-20,y+15);c.lineTo(x+20,y+15);c.fill();c.fillStyle='#295c37';c.fillRect(x-4,y+8,8,24)}else if(id==='dunes'){c.strokeStyle='#8f6437';c.lineWidth=5;c.beginPath();c.moveTo(x,y+20);c.lineTo(x,y-22);c.moveTo(x,y-8);c.lineTo(x-13,y-18);c.moveTo(x,y-2);c.lineTo(x+12,y-12);c.stroke()}else if(id==='frost'){c.fillStyle='#5ca5bd';c.beginPath();c.moveTo(x,y-28);c.lineTo(x-15,y+18);c.lineTo(x+15,y+18);c.fill();c.fillStyle='#bdefff';c.beginPath();c.moveTo(x,y-20);c.lineTo(x-7,y+5);c.lineTo(x+8,y+5);c.fill()}else{c.strokeStyle='#6c3b83';c.lineWidth=3;c.beginPath();c.arc(x,y,16,0,TAU);c.stroke();circle(c,x,y,5,'#b868db')}c.restore()}
export function drawHero(c,p,heroId,skin,t=0){shadow(c,p.x,p.y,p.r);c.save();c.translate(p.x,p.y);const bob=Math.sin(t*7)*1.5;c.translate(0,bob);circle(c,0,2,p.r,skin.body);circle(c,0,-11,p.r*.58,'#f0c5a5');c.fillStyle=skin.accent;if(heroId==='knight'){c.fillRect(-13,-18,26,7);c.fillRect(-16,-8,6,23);c.strokeStyle=skin.accent;c.lineWidth=4;c.beginPath();c.arc(12,4,10,-1.2,1.2);c.stroke()}else if(heroId==='mage'){c.beginPath();c.moveTo(-15,-13);c.lineTo(0,-34);c.lineTo(17,-12);c.fill();circle(c,14,8,5,skin.accent)}else if(heroId==='ranger'){c.beginPath();c.moveTo(-15,-14);c.lineTo(0,-25);c.lineTo(15,-14);c.fill();c.strokeStyle=skin.accent;c.lineWidth=3;c.beginPath();c.arc(15,2,12,-1.5,1.5);c.stroke()}else if(heroId==='berserk'){c.fillRect(-17,-17,34,6);c.strokeStyle=skin.accent;c.lineWidth=5;c.beginPath();c.moveTo(14,0);c.lineTo(22,17);c.stroke()}else{c.beginPath();c.moveTo(-16,-15);c.lineTo(0,-26);c.lineTo(16,-15);c.fill();c.strokeStyle=skin.accent;c.lineWidth=3;c.beginPath();c.moveTo(12,3);c.lineTo(24,-6);c.stroke()}circle(c,5,-12,2.3,'#fff');c.restore()}
export function drawPet(c,p,id,t=0){shadow(c,p.x,p.y,p.r*.9);c.save();c.translate(p.x,p.y+Math.sin(t*9)*2);circle(c,0,0,p.r,p.color);circle(c,-5,-8,p.r*.48,p.color);circle(c,5,-8,p.r*.48,p.color);if(id==='fox'||id==='wolf'){c.fillStyle=p.color;c.beginPath();c.moveTo(-9,-7);c.lineTo(-12,-19);c.lineTo(-2,-11);c.fill();c.beginPath();c.moveTo(9,-7);c.lineTo(12,-19);c.lineTo(2,-11);c.fill()}if(id==='dragon'){c.fillStyle='#ffe6a8';c.beginPath();c.moveTo(-8,3);c.lineTo(-20,10);c.lineTo(-8,13);c.fill();c.beginPath();c.moveTo(8,3);c.lineTo(20,10);c.lineTo(8,13);c.fill()}circle(c,-4,-2,2,'#151822');circle(c,4,-2,2,'#151822');c.restore()}
export function drawEnemy(c,e,t=0){shadow(c,e.x,e.y,e.r);c.save();c.translate(e.x,e.y);const pulse=1+Math.sin(t*5+e.x*.01)*.025;c.scale(pulse,pulse);circle(c,0,0,e.r,e.hit?'#fff':e.color);c.fillStyle='rgba(0,0,0,.24)';if(e.type.includes('wolf')||e.type==='fang'){c.beginPath();c.moveTo(-e.r*.8,-e.r*.5);c.lineTo(-e.r*.35,-e.r*1.2);c.lineTo(0,-e.r*.55);c.fill();c.beginPath();c.moveTo(e.r*.8,-e.r*.5);c.lineTo(e.r*.35,-e.r*1.2);c.lineTo(0,-e.r*.55);c.fill()}if(e.type.includes('mage')||e.type==='shaman'||e.type==='warlock'||e.type==='djinn'){c.strokeStyle='rgba(255,255,255,.5)';c.lineWidth=3;c.beginPath();c.arc(0,0,e.r*.72,0,TAU);c.stroke()}circle(c,-e.r*.28,-2,Math.max(2,e.r*.11),'#17151d');circle(c,e.r*.28,-2,Math.max(2,e.r*.11),'#17151d');if(e.boss){c.strokeStyle='#fff1a0';c.lineWidth=4;c.beginPath();c.moveTo(-e.r*.65,-e.r*.7);c.lineTo(-e.r*.35,-e.r*1.12);c.lineTo(-.05*e.r,-e.r*.72);c.lineTo(e.r*.35,-e.r*1.12);c.lineTo(e.r*.65,-e.r*.7);c.stroke()}c.restore()}
