const lanes={
"EXP Lane":["Aldous","Alice","Argus","Arlott","Benedetta","Chou","Cici","Dyrroth","Edith","Esmeralda","Freya","Guinevere","Lapu-Lapu","Lukas","Masha","Minsitthar","Paquito","Phoveus","Ruby","Silvanna","Sora","Sun","Terizla","Thamuz","Uranus","X.Borg","Yu Zhong","Zilong"],
"Jungle":["Aamon","Alpha","Alucard","Aulus","Balmond","Bane","Barats","Baxia","Fanny","Fredrinn","Gusion","Hanzo","Harley","Hayabusa","Helcurt","Hirara","Joy","Julian","Karina","Lancelot","Leomord","Ling","Martis","Natalia","Nolan","Popol and Kupa","Roger","Saber","Suyou","Yi Sun-shin","Yin"],
"Mid Lane":["Aurora","Cecilion","Chang'e","Cyclops","Eudora","Faramis","Gord","Kadita","Kagura","Kimmy","Lunox","Luo Yi","Lylia","Nana","Novaria","Odette","Pharsa","Selena","Vale","Valentina","Valir","Vexana","Xavier","Yve","Zetian","Zhask","Zhuxin"],
"Gold Lane":["Beatrix","Brody","Bruno","Claude","Clint","Granger","Hanabi","Harith","Irithel","Ixia","Karrie","Layla","Lesley","Melissa","Miya","Moskov","Natan","Obsidia","Wanwan"],
"Roam":["Akai","Angela","Atlas","Badang","Belerick","Carmilla","Chip","Diggie","Estes","Floryn","Franco","Gatotkaca","Gloo","Grock","Hilda","Hylos","Jawhead","Johnson","Kaja","Kalea","Khaleed","Khufra","Lolita","Marcel","Mathilda","Minotaur","Rafaela","Tigreal"]};
const heroes=[...new Set(Object.values(lanes).flat())].sort((a,b)=>a.localeCompare(b));
const heroLanes=Object.fromEntries(heroes.map(h=>[h,Object.keys(lanes).filter(l=>lanes[l].includes(h))]));
const builds=[
["Burst / Penetration","Взрывной урон + пробивание"],["Attack Speed / On-hit","Скорость атаки и on-hit"],["Crit Glass Cannon","Крит, минимум защиты"],["Sustain / Spell Vamp","Долгие драки и восстановление"],["Full Tank","Живучесть и резисты"],["Cooldown / Utility","КД и частое использование навыков"],["Hybrid Bruiser","Урон + 2 защитных слота"],["Move Speed / Roam","Мобильность и ротации"],["Anti-heal Core","Ранний антихил"],["Late Game Scaling","Максимум силы в лейте"]];
const spells=["Flicker","Purify","Retribution","Execute","Sprint","Aegis","Petrify","Vengeance","Inspire","Revitalize","Arrival"];
const emblems=["Tank","Fighter","Assassin","Mage","Marksman","Support","Common"];
const tasks=["Не умирай первые 5 минут","Сделай 5 ассистов до своей 3-й смерти","Участвуй минимум в 60% командных убийств","Сделай ротацию на другую линию до 4:00","Помоги забрать первого Turtle","После выигранной драки сразу бери объект","Сделай 2 убийства/ассиста подряд без базы","Сделай минимум 3 сейва союзника","Закончи матч с ассистов не меньше, чем убийств","Попробуй закончить матч с менее чем 6 смертями","Минимум дважды помоги продавить башню","Перед Lord сначала выиграй позицию","Сделай один осознанный bait и выживи","Не спорь за чужой фарм первые 8 минут","Сыграй весь матч без токсичных сообщений","После каждой смерти назови себе одну ошибку","Сделай минимум 2 результативных ганга","Хотя бы раз отдай очевидный килл союзнику"];
const hard=["До 10-й минуты не инициируй первым — только контр-инициация","Один слот сборки весь матч должен быть защитным","После каждого убийства меняй линию или зону карты","Нельзя повторять один маршрут из базы два раза подряд","Выбери союзника и минимум 3 раза прикрой именно его","Первые 8 минут покупай предметы только после возвращения на базу"];
const bonuses=["Без бонус-правила","Первый предмет — ботинки","После смерти меняй приоритет цели","Каждый Turtle/Lord — обязательный сбор","Не гоняйся глубже одной башни","После выигранной драки сразу объект","Минимум один защитный предмет к лейту","Если отстаёшь — не форси, играй от камбэка"];
let state={hero:null,lane:null,build:null,spell:null,emblem:null,task:null,bonus:null};
let locks={lane:false,build:false,spell:false,emblem:false,task:false,bonus:false};
let recent=[];let filter="Все";let history=JSON.parse(localStorage.getItem("mlbbHistory")||"[]");
const $=x=>document.getElementById(x),pick=a=>a[Math.floor(Math.random()*a.length)];
function pool(a){if(!$("noRepeat").checked||a.length<8)return a;const f=a.filter(x=>!recent.includes(x));return f.length?f:a}
function pair(){const forced=$("forcedLane").value,mode=$("mode").value;if(forced){return{lane:forced,hero:pick(pool(mode==="chaos"?heroes:lanes[forced]))}}if(mode==="smart"){const lane=pick(Object.keys(lanes));return{lane:lane,hero:pick(pool(lanes[lane]))}}const hero=pick(pool(heroes));return{hero:hero,lane:mode==="chaos"?pick(Object.keys(lanes)):pick(heroLanes[hero])}}
function randomTask(){return pick($("hard").checked?tasks.concat(hard):tasks)}
function animate(final,cb){$("wheel").classList.add("spinning");let n=0;const t=setInterval(function(){$("hero").textContent=pick(heroes);n++;if(n>13){clearInterval(t);$("hero").textContent=final;$("wheel").classList.remove("spinning");if(cb)cb()}},60)}
function spin(){const p=pair();state.hero=p.hero;if(!locks.lane)state.lane=p.lane;if(!locks.build)state.build=pick(builds);if(!locks.spell)state.spell=pick(spells);if(!locks.emblem)state.emblem=pick(emblems);if(!locks.task)state.task=randomTask();if(!locks.bonus)state.bonus=pick(bonuses);recent=[state.hero].concat(recent.filter(x=>x!==state.hero)).slice(0,10);animate(state.hero,function(){render();save()})}
function rerollHero(){const p=pair();state.hero=p.hero;if(!locks.lane)state.lane=p.lane;recent=[state.hero].concat(recent.filter(x=>x!==state.hero)).slice(0,10);animate(state.hero,render)}
function render(){
$("hero").textContent=state.hero||"Нажми «Крутить»";$("heroLanes").textContent=state.hero?"Рекомендовано: "+heroLanes[state.hero].join(" · "):"—";
$("lane").textContent=state.lane||"—";$("laneNote").textContent=state.hero&&state.lane&&!heroLanes[state.hero].includes(state.lane)?"⚡ Необычная линия":"совместимо с режимом";
$("build").textContent=state.build?state.build[0]:"—";$("buildNote").textContent=state.build?state.build[1]:"—";$("spell").textContent=state.spell||"—";$("emblem").textContent=state.emblem||"—";$("task").textContent=state.task||"—";$("bonus").textContent=state.bonus||"—";
document.querySelectorAll(".lock").forEach(function(b){const on=locks[b.dataset.lock];b.classList.toggle("on",on);b.textContent=on?"🔒":"🔓"})}
function save(){history=[{hero:state.hero,lane:state.lane,build:state.build?state.build[0]:"",task:state.task,time:new Date().toLocaleString("ru-RU",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"})}].concat(history).slice(0,10);localStorage.setItem("mlbbHistory",JSON.stringify(history));showHistory()}
function esc(s){return String(s).replace(/[&<>"']/g,function(m){return{"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]})}
function showHistory(){const root=$("history");if(!history.length){root.innerHTML="<p style='color:#95a1c4'>История пока пустая.</p>";return}root.innerHTML=history.map(function(r){return"<div class='historyRow'><span><b>"+esc(r.hero)+"</b></span><span>"+esc(r.lane)+"</span><span>"+esc(r.build)+"</span><span>"+esc(r.task)+"</span><span>"+esc(r.time)+"</span></div>"}).join("")}
function showHeroes(){const q=$("search").value.toLowerCase();const list=heroes.filter(function(h){return(filter==="Все"||heroLanes[h].includes(filter))&&h.toLowerCase().includes(q)});$("count").textContent=list.length+" из "+heroes.length;$("heroes").innerHTML=list.map(function(h){return"<button class='heroBtn' data-h='"+esc(h)+"'><b>"+esc(h)+"</b><span>"+heroLanes[h].join(" · ")+"</span></button>"}).join("");document.querySelectorAll(".heroBtn").forEach(function(b){b.onclick=function(){state.hero=b.dataset.h;if(!locks.lane)state.lane=pick(heroLanes[state.hero]);recent=[state.hero].concat(recent.filter(x=>x!==state.hero)).slice(0,10);animate(state.hero,render);scrollTo({top:0,behavior:"smooth"})}})}
function initFilters(){const names=["Все"].concat(Object.keys(lanes));$("filters").innerHTML=names.map(function(n){return"<button data-l='"+n+"' class='"+(n==="Все"?"on":"")+"'>"+n+"</button>"}).join("");document.querySelectorAll("#filters button").forEach(function(b){b.onclick=function(){filter=b.dataset.l;document.querySelectorAll("#filters button").forEach(x=>x.classList.toggle("on",x===b));showHeroes()}})}
function copy(){if(!state.hero){spin();return}const txt="MLBB Chaos Roulette\nГерой: "+state.hero+"\nЛиния: "+state.lane+"\nСборка: "+(state.build?state.build[0]:"")+"\nСпелл: "+state.spell+"\nЭмблема: "+state.emblem+"\nЗадание: "+state.task+"\nБонус: "+state.bonus;navigator.clipboard.writeText(txt).then(function(){$("copy").textContent="✅ Скопировано";setTimeout(function(){$("copy").textContent="📋 Скопировать"},1000)}).catch(function(){prompt("Скопируй:",txt)})}
$("spin").onclick=spin;$("rerollHero").onclick=rerollHero;$("rerollTask").onclick=function(){if(!locks.task){state.task=randomTask();render()}};$("copy").onclick=copy;$("unlock").onclick=function(){Object.keys(locks).forEach(k=>locks[k]=false);render()};$("clearHistory").onclick=function(){history=[];localStorage.removeItem("mlbbHistory");showHistory()};$("search").oninput=showHeroes;$("forcedLane").onchange=function(){if($("forcedLane").value&&!locks.lane){state.lane=$("forcedLane").value;render()}};document.querySelectorAll(".lock").forEach(function(b){b.onclick=function(){locks[b.dataset.lock]=!locks[b.dataset.lock];render()}});initFilters();showHeroes();showHistory();render();
