// game1 platform/input/localization patch: combat, controls, RU/EN, Yandex lifecycle.
(function(){
'use strict';
const cv=document.getElementById('screen');
document.addEventListener('contextmenu',e=>e.preventDefault());
document.addEventListener('selectstart',e=>e.preventDefault());
if(cv) cv.tabIndex=0;

function combatReady(){return typeof game!=='undefined'&&game&&game.state==='play'&&typeof keys!=='undefined'&&typeof pending!=='undefined';}
function attack(){if(!combatReady())return;keys.attack=true;pending.whip=true;try{AudioSys.resume();}catch(e){}}
function attackUp(){if(typeof keys!=='undefined')keys.attack=false;}
function jump(){if(combatReady())pending.jump=true;}
function dash(){if(combatReady())pending.dash=true;}
addEventListener('keydown',e=>{const k=(e.key||'').toLowerCase();if(['f','z','j'].includes(k)){attack();e.preventDefault();}if(k===' '){jump();e.preventDefault();}if(k==='shift'){dash();e.preventDefault();}});
addEventListener('keyup',e=>{if(['f','z','j'].includes((e.key||'').toLowerCase()))attackUp();});
if(cv){cv.addEventListener('pointerdown',e=>{cv.focus();if(e.pointerType==='mouse'){e.preventDefault();if(e.button===0)attack();if(e.button===2)dash();}});addEventListener('pointerup',e=>{if(e.pointerType==='mouse'&&e.button===0)attackUp();});}

const ui={ru:{controls:'УПРАВЛЕНИЕ',move:'Движение',attack:'Атака',jump:'Прыжок',dash:'Рывок',heal:'Лечение',pause:'Пауза / меню',sub:'Доп. оружие',pc:'ПК',mobile:'ТЕЛЕФОН',close:'Закрыть',language:'Язык'},en:{controls:'CONTROLS',move:'Movement',attack:'Attack',jump:'Jump',dash:'Dash',heal:'Heal',pause:'Pause / menu',sub:'Sub-weapon',pc:'PC',mobile:'MOBILE',close:'Close',language:'Language'}};
let lang=(localStorage.getItem('game1-lang')||((navigator.language||'en').toLowerCase().startsWith('ru')?'ru':'en'));window.GAME_LANG=lang;

// Translate the original game's bitmap strings without rewriting its gameplay code.
const RU={
'PLAYER':'ИГРОК','PRESS ENTER':'НАЖМИ ENTER','A NIGHT OF THE HUNTER':'НОЧЬ ОХОТНИКА','NEW HUNT':'НОВАЯ ОХОТА','CONTINUE':'ПРОДОЛЖИТЬ','ATTACK':'АТАКА','JUMP':'ПРЫЖОК','BACKDASH':'РЫВОК НАЗАД','SUB-WEAPON':'ДОП. ОРУЖИЕ','DROP DOWN':'СПРЫГНУТЬ ВНИЗ','BOSS RUSH':'БИТВА С БОССАМИ','BESTIARY':'БЕСТИАРИЙ','DEEDS':'ДОСТИЖЕНИЯ','DAILY CASTLE':'ЗАМОК ДНЯ','ERASE ALL PROGRESS':'СТЕРЕТЬ ВЕСЬ ПРОГРЕСС','ERASE EVERYTHING THE CASTLE REMEMBERS?':'СТЕРЕТЬ ВСЁ, ЧТО ПОМНИТ ЗАМОК?','PRESS DELETE AGAIN TO CONFIRM':'НАЖМИ DELETE ЕЩЁ РАЗ','ALL RECORD OF YOU IS GONE':'ВСЕ ЗАПИСИ О ТЕБЕ СТЁРТЫ','PAUSED':'ПАУЗА','RESUME':'ПРОДОЛЖИТЬ','GAME OVER':'ИГРА ОКОНЧЕНА','TRY AGAIN':'ПОПРОБОВАТЬ СНОВА','VICTORY':'ПОБЕДА','HEARTS':'СЕРДЦА','GEMS':'САМОЦВЕТЫ','GOLDEN KEY':'ЗОЛОТОЙ КЛЮЧ','HEALING DRAUGHT':'ЛЕЧЕБНОЕ ЗЕЛЬЕ','NOT ENOUGH GEMS':'НЕ ХВАТАЕТ САМОЦВЕТОВ','SOLD':'ПРОДАНО','BUY':'КУПИТЬ','LEAVE':'ВЫЙТИ','THE WANDERING MERCHANT':'СТРАНСТВУЮЩИЙ ТОРГОВЕЦ','SHRINE OF THE HUNT':'СВЯТИЛИЩЕ ОХОТЫ','LEARNED':'ИЗУЧЕНО','SEALED':'ЗАПЕЧАТАНО','LEARN':'ИЗУЧИТЬ','ARCANA BINDING':'СВЯЗЬ АРКАНОВ','ACTION':'ДЕЙСТВИЕ','ATTRIBUTE':'СВОЙСТВО','UNKNOWN':'НЕИЗВЕСТНО','BOUND':'СВЯЗАНО','NOT YET FOUND':'ЕЩЁ НЕ НАЙДЕНО','THE CASTLE OPENS THREE ROADS':'ЗАМОК ОТКРЫВАЕТ ТРИ ПУТИ','CHOOSE YOUR DESCENT':'ВЫБЕРИ ПУТЬ ВНИЗ','CHOOSE':'ВЫБРАТЬ','TAKE THE ROAD':'ВЫБРАТЬ ПУТЬ','STAGE':'ЭТАП','NEW DEPTH REACHED':'ДОСТИГНУТА НОВАЯ ГЛУБИНА','CURSE':'ПРОКЛЯТИЕ','TREASURE':'СОКРОВИЩЕ','OBELISK AWAKENED':'ОБЕЛИСК ПРОБУЖДЁН','RESTED':'ОТДЫХ','FLASKS REFILLED':'ФЛЯГИ ПОПОЛНЕНЫ','THE CASTLE STIRS':'ЗАМОК ПРОБУЖДАЕТСЯ','ITEM CRASH':'СУПЕРУДАР','THE FLOOR IS MAPPED':'ЭТАЖ НАНЕСЁН НА КАРТУ','THE VOID ANSWERS':'БЕЗДНА ОТВЕЧАЕТ','SOUL BOUND':'ДУША СВЯЗАНА','MARKED':'МЕТКА ПОСТАВЛЕНА','MARK SCRUBBED':'МЕТКА УДАЛЕНА','ORE':'РУДА','COMBO':'КОМБО','VOL':'ГРОМКОСТЬ','PRAY':'МОЛИТЬСЯ','RELICS':'РЕЛИКВИИ','CRAFT':'КОВАТЬ','TRADE':'ТОРГОВАТЬ','REST':'ОТДОХНУТЬ','CLOSE':'ЗАКРЫТЬ','MAP':'КАРТА','SATCHEL':'СУМКА','WEAPON':'ОРУЖИЕ','RELIC':'РЕЛИКВИЯ','SKILL':'НАВЫК','HEALTH':'ЗДОРОВЬЕ','MAX HEALTH':'МАКС. ЗДОРОВЬЕ','DAMAGE':'УРОН','ARMOR':'БРОНЯ','SPEED':'СКОРОСТЬ','LEVEL':'УРОВЕНЬ','SLAIN':'УБИТО','FORMS':'ФОРМЫ','DEEPEST STAGE':'МАКС. ГЛУБИНА','TABLETS RECOVERED':'НАЙДЕНО ТАБЛИЧЕК','FIENDS SLAIN IN ALL':'ВСЕГО ВРАГОВ УБИТО','EARNED':'ПОЛУЧЕНО','DEEDS OF THE HUNT':'ПОДВИГИ ОХОТЫ','LEFT/RIGHT CHOOSE':'ВЛЕВО/ВПРАВО — ВЫБОР','ENTER CLOSE':'ENTER — ЗАКРЫТЬ','ENTER LEAVE':'ENTER — ВЫЙТИ','UP/DOWN SCROLL':'ВВЕРХ/ВНИЗ — ЛИСТАТЬ','ARROWS MOVE':'СТРЕЛКИ — ВЫБОР','Z BIND':'Z — СВЯЗАТЬ','Q CLOSE':'Q — ЗАКРЫТЬ'};
function tr(s){if(lang!=='ru'||typeof s!=='string')return s;if(RU[s])return RU[s];let out=s;const keys=Object.keys(RU).sort((a,b)=>b.length-a.length);for(const k of keys)out=out.split(k).join(RU[k]);return out;}
function installTextHooks(){for(const name of ['drawText','drawTextShadow','drawTextCentered']){const orig=window[name];if(typeof orig==='function'&&!orig.__g1){const fn=function(g,text,...rest){return orig.call(this,g,tr(text),...rest)};fn.__g1=true;window[name]=fn;}}}
installTextHooks();setTimeout(installTextHooks,0);

const btn=document.createElement('button');btn.textContent='?';btn.setAttribute('aria-label','Controls');btn.style.cssText='position:fixed;right:10px;top:10px;z-index:100;width:38px;height:38px;border:1px solid #8a6d2f;background:#100c1dcc;color:#ffe080;font:bold 20px monospace;cursor:pointer;border-radius:5px';
const panel=document.createElement('div');panel.style.cssText='display:none;position:fixed;inset:0;z-index:99;background:#05040bd9;color:#e8e4d8;font:16px monospace;align-items:center;justify-content:center;line-height:1.65';
function panelHTML(){const t=ui[lang];return '<div style="width:min(620px,88vw);max-height:82vh;overflow:auto;background:#0d0918;border:2px solid #8a6d2f;padding:24px"><div style="font-size:26px;color:#ffe080;margin-bottom:12px">'+t.controls+'</div><b>'+t.pc+'</b><br>'+t.move+': A/D, ←/→<br>'+t.attack+': Z / J / F / ЛКМ<br>'+t.jump+': X / K / SPACE<br>'+t.dash+': C / L / SHIFT / ПКМ<br>'+t.heal+': H<br>'+t.sub+': ↑ + '+t.attack+'<br>'+t.pause+': ENTER / ESC<br><br><b>'+t.mobile+'</b><br>'+(lang==='ru'?'Экранные кнопки движения, прыжка, атаки, рывка и доп. оружия':'On-screen movement, jump, attack, dash and sub-weapon buttons')+'<br><br>'+t.language+': <button id="g1lang" style="font:inherit;padding:5px 12px">'+(lang==='ru'?'English':'Русский')+'</button> &nbsp; <button id="g1close" style="font:inherit;padding:5px 12px">'+t.close+'</button></div>';}
function renderPanel(){panel.innerHTML=panelHTML();panel.querySelector('#g1lang').onclick=()=>{lang=lang==='ru'?'en':'ru';window.GAME_LANG=lang;localStorage.setItem('game1-lang',lang);renderPanel();};panel.querySelector('#g1close').onclick=()=>{panel.style.display='none';yStop(false);};}
btn.onclick=()=>{renderPanel();panel.style.display='flex';yStop(true);};document.body.append(panel,btn);addEventListener('keydown',e=>{if(e.key==='?'||e.key==='/')btn.click();if(e.key==='Escape'&&panel.style.display==='flex'){panel.style.display='none';yStop(false);}});

let ysdk=null,ready=false;async function initYandex(){if(typeof YaGames==='undefined')return;try{ysdk=await YaGames.init();window.ysdk=ysdk;const ylang=ysdk.environment&&ysdk.environment.i18n&&ysdk.environment.i18n.lang;if(!localStorage.getItem('game1-lang')&&ylang){lang=ylang==='ru'?'ru':'en';window.GAME_LANG=lang;}setTimeout(()=>{if(!ready&&ysdk?.features?.LoadingAPI){ysdk.features.LoadingAPI.ready();ready=true;}},0);}catch(e){console.warn('Yandex SDK:',e);}}
function yStop(stop){try{if(ysdk?.features?.GameplayAPI){stop?ysdk.features.GameplayAPI.stop():ysdk.features.GameplayAPI.start();}}catch(e){}try{if(stop&&typeof AudioSys!=='undefined')AudioSys.stopMusic();else if(!stop&&typeof AudioSys!=='undefined')AudioSys.resume();}catch(e){}}
window.Game1Yandex={init:initYandex,stop:()=>yStop(true),start:()=>yStop(false)};document.addEventListener('visibilitychange',()=>yStop(document.hidden));addEventListener('blur',()=>yStop(true));addEventListener('focus',()=>{if(!document.hidden)yStop(false);});initYandex();
})();