// On-screen touch controls for phones/tablets. Uses the same input flags as keyboard/gamepad.
(function(){
'use strict';
if(!window.TOUCH)return;
const resume=()=>{try{AudioSys.resume();}catch(e){}};
const ru=()=>window.GAME_LANG==='ru';
let upDpad=false,subTimer=null;const setUp=()=>{keys.up=upDpad||subTimer!==null;};
const B=[
{id:'up',pad:'dpad',col:2,row:1,glyph:'▲',press:()=>{upDpad=true;pending.up=true;setUp();},release:()=>{upDpad=false;setUp();}},
{id:'left',pad:'dpad',col:1,row:2,glyph:'◀',press:()=>{keys.left=true;pending.leftN=true;},release:()=>{keys.left=false;}},
{id:'right',pad:'dpad',col:3,row:2,glyph:'▶',press:()=>{keys.right=true;pending.rightN=true;},release:()=>{keys.right=false;}},
{id:'down',pad:'dpad',col:2,row:3,glyph:'▼',press:()=>{keys.down=true;pending.downN=true;},release:()=>{keys.down=false;}},
{id:'sub',pad:'act',col:1,row:1,glyph:()=>ru()?'ДОП':'SUB',kind:'act sub',press:()=>{pending.whip=true;resume();if(subTimer)clearTimeout(subTimer);subTimer=setTimeout(()=>{subTimer=null;setUp();},150);setUp();}},
{id:'dash',pad:'act',col:2,row:1,glyph:()=>ru()?'РЫВ':'DSH',kind:'act dash',press:()=>{pending.dash=true;}},
{id:'atk',pad:'act',col:1,row:2,glyph:()=>ru()?'АТК':'ATK',kind:'act atk',press:()=>{keys.attack=true;pending.whip=true;resume();},release:()=>{keys.attack=false;}},
{id:'jump',pad:'act',col:2,row:2,glyph:()=>ru()?'ПРГ':'JMP',kind:'act jump',press:()=>{pending.jump=true;resume();}},
{id:'start',pad:'util',glyph:'☰',title:()=>ru()?'Старт / пауза':'Start / Pause',press:()=>{pending.enter=true;resume();}},
{id:'heal',pad:'util',glyph:'✚',kind:'heal',title:()=>ru()?'Выпить зелье':'Drink Flask',press:()=>{pending.heal=true;}},
{id:'cards',pad:'util',glyph:'✦',title:()=>ru()?'Арканы':'Arcana',press:()=>{pending.q=true;}},
{id:'crash',pad:'util',glyph:'✷',title:()=>ru()?'Суперудар':'Item Crash',press:()=>{pending.crash=true;}},
{id:'bag',pad:'util',glyph:'▤',title:()=>ru()?'Сумка':'Satchel',press:()=>{pending.inv=true;}},
{id:'map',pad:'util',glyph:'❖',title:()=>ru()?'Карта':'Map',press:()=>{pending.map=true;}}
];
const css=`#tc{position:fixed;inset:0;z-index:50;pointer-events:none;touch-action:none;-webkit-user-select:none;user-select:none;-webkit-tap-highlight-color:transparent;font-family:monospace;font-weight:bold}#tc .grp{position:absolute;display:grid;gap:8px;padding:10px;padding-left:max(10px,env(safe-area-inset-left));padding-right:max(10px,env(safe-area-inset-right));padding-bottom:max(10px,env(safe-area-inset-bottom));padding-top:max(8px,env(safe-area-inset-top))}#tc .dpad{left:0;bottom:0;grid-template-columns:repeat(3,auto)}#tc .act{right:0;bottom:0;grid-template-columns:repeat(2,auto)}#tc .util{right:0;top:0;display:flex;gap:6px}#tc button{pointer-events:auto;touch-action:none;margin:0;-webkit-appearance:none;appearance:none;color:rgba(230,224,255,.9);font-family:inherit;font-weight:bold;background:rgba(26,20,48,.18);border:1.5px solid rgba(170,145,240,.38);border-radius:14px;display:flex;align-items:center;justify-content:center;line-height:1;text-shadow:0 1px 3px #000;transition:background .05s,border-color .05s}#tc button:active,#tc button.on{background:rgba(130,100,225,.45);border-color:rgba(210,190,255,.8);color:#fff}#tc .dir{width:clamp(46px,12vmin,84px);height:clamp(46px,12vmin,84px);font-size:clamp(16px,4.4vmin,30px);border-radius:12px}#tc .act button{width:clamp(56px,15vmin,104px);height:clamp(56px,15vmin,104px);border-radius:50%;font-size:clamp(12px,3vmin,20px)}#tc .act .jump{background:rgba(60,130,95,.22);border-color:rgba(120,235,170,.45)}#tc .act .atk{background:rgba(160,65,75,.22);border-color:rgba(255,140,150,.45)}#tc .util button{width:clamp(34px,8vmin,54px);height:clamp(34px,8vmin,54px);font-size:clamp(15px,3.6vmin,24px);border-radius:10px;background:rgba(18,14,36,.2)}#tc .util .heal{background:rgba(60,130,95,.26);border-color:rgba(120,235,170,.5);color:#d6ffe6}#tc-rotate{position:fixed;inset:0;z-index:60;display:none;background:#08060f;color:#b9b0e0;pointer-events:auto;flex-direction:column;align-items:center;justify-content:center;text-align:center;font-family:monospace;gap:14px;padding:24px}#tc-rotate .icon{font-size:64px;animation:tcSpin 2.4s ease-in-out infinite}#tc-rotate b{color:#e8e0ff;font-size:20px;letter-spacing:1px}@keyframes tcSpin{0%,55%{transform:rotate(0)}80%,100%{transform:rotate(90deg)}}@media(orientation:portrait){html.touch #tc-rotate{display:flex}html.touch #tc{display:none}}`;
const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);
const root=document.createElement('div');root.id='tc';const groups={dpad:mk('grp dpad'),act:mk('grp act'),util:mk('grp util')};function mk(cls){const d=document.createElement('div');d.className=cls;root.appendChild(d);return d;}
const els=[];for(const b of B){const el=document.createElement('button');const refresh=()=>{el.textContent=typeof b.glyph==='function'?b.glyph():b.glyph;if(b.title)el.setAttribute('aria-label',typeof b.title==='function'?b.title():b.title);};refresh();els.push(refresh);el.className=b.pad==='dpad'?'dir':(b.kind||'');if(b.col){el.style.gridColumn=b.col;el.style.gridRow=b.row;}el.oncontextmenu=e=>{e.preventDefault();return false;};bind(el,b);groups[b.pad].appendChild(el);}
const rot=document.createElement('div');rot.id='tc-rotate';function refreshLang(){els.forEach(f=>f());rot.innerHTML='<div class="icon">↻</div><b>'+(ru()?'ПОВЕРНИТЕ УСТРОЙСТВО':'ROTATE YOUR DEVICE')+'</b><div>'+(ru()?'Игра работает в альбомной ориентации.':'Moonfang Castle plays in landscape.')+'</div>';}refreshLang();setInterval(refreshLang,1000);document.body.appendChild(rot);document.body.appendChild(root);
function bind(el,b){const ids=new Set();const down=e=>{e.preventDefault();const first=ids.size===0;ids.add(e.pointerId);try{el.setPointerCapture(e.pointerId);}catch(_){}if(first){el.classList.add('on');if(b.press)b.press();}};const up=e=>{if(!ids.has(e.pointerId))return;ids.delete(e.pointerId);if(ids.size===0){el.classList.remove('on');if(b.release)b.release();}};el.addEventListener('pointerdown',down,{passive:false});el.addEventListener('pointerup',up,{passive:false});el.addEventListener('pointercancel',up,{passive:false});el.addEventListener('lostpointercapture',up,{passive:false});}
window.addEventListener('orientationchange',()=>{if(window.fitCanvas)setTimeout(window.fitCanvas,250);});
})();