// v5 arcade controls: joystick for air hockey + synchronized maze race
if(!GAMES.some(x=>x[0]==='maze')){GAMES.push(['maze','🕹️','Лабиринт-гонка','Управляйте персонажами джойстиками и первым доберитесь до центра.']);TITLES.maze='Лабиринт-гонка'}
if(typeof CAT!=='undefined')CAT.maze='Аркада';
let joy={x:0,y:0,active:false},joyFrame=0,joyLast=0,guestJoy={x:360,y:80};
let mazeMine=null,mazeOther=null,mazeCtx=null,mazeCanvas=null,mazeFrame=0,mazeLast=0,mazeSend=0;
const _auApply=applyAction,_auRender=renderGame,_auHandle=handleMessage,_auBack=backMenu,_auAir=renderAir;
function joyHTML(label='Джойстик'){return `<div class="joyLabel">${esc(label)}</div><div class="joyWrap"><div id="joystick" class="joystick"><div id="joyKnob" class="joyKnob"></div></div></div>`}
function initJoystick(onMove){let j=$('joystick'),k=$('joyKnob');if(!j||!k)return;joy={x:0,y:0,active:false};const set=e=>{let r=j.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=e.clientX-cx,dy=e.clientY-cy,max=r.width*.32,d=Math.hypot(dx,dy)||1,scale=Math.min(1,max/d);dx*=scale;dy*=scale;joy.x=dx/max;joy.y=dy/max;k.style.transform=`translate(${dx}px,${dy}px)`;onMove?.(joy.x,joy.y)};j.onpointerdown=e=>{e.preventDefault();j.setPointerCapture?.(e.pointerId);joy.active=true;set(e)};j.onpointermove=e=>{if(joy.active)set(e)};const end=e=>{if(!joy.active)return;joy.active=false;joy.x=joy.y=0;k.style.transform='translate(0,0)';onMove?.(0,0)};j.onpointerup=end;j.onpointercancel=end}

renderAir=function(){$('roundPill').textContent='До 5 голов';$('bar').style.width='100%';$('gameCard').innerHTML=`<div class="airscore"><b id="airHostScore">0</b><span>${esc(hostName())} · ${esc(guestName())}</span><b id="airGuestScore">0</b></div><canvas id="airCanvas" class="aircanvas"></canvas><div class="muted">${role==='host'?'Ты играешь снизу.':'Ты играешь сверху.'} Можно водить пальцем по своей половине поля или использовать джойстик.</div>${joyHTML('Управление битой')}<div class="actions"><button class="ghost" onclick="openChat()">💬 Чат</button><button class="btn" onclick="dispatch('air_restart')">Новый матч</button></div>`;requestAnimationFrame(()=>{initAirCanvas();initAirJoystick()})}
function initAirJoystick(){guestJoy=role==='guest'&&airLatest?.g?{x:airLatest.g.x,y:airLatest.g.y}:{x:360,y:80};initJoystick();cancelAnimationFrame(joyFrame);joyLast=performance.now();airJoyLoop()}
function airJoyLoop(t=performance.now()){if(state.type!=='air')return;let dt=Math.min(.04,(t-joyLast)/1000||.016);joyLast=t;if(joy.active){let speed=330;if(role==='host'&&air){air.host.x=Math.max(30,Math.min(690,air.host.x+joy.x*speed*dt));air.host.y=Math.max(260,Math.min(450,air.host.y+joy.y*speed*dt))}else if(role==='guest'){guestJoy.x=Math.max(30,Math.min(690,guestJoy.x+joy.x*speed*dt));guestJoy.y=Math.max(30,Math.min(220,guestJoy.y+joy.y*speed*dt));if(t-joyLast>9999){};direct({t:'airInput',x:guestJoy.x,y:guestJoy.y})}}joyFrame=requestAnimationFrame(airJoyLoop)}

const MAZE_WALLS=[[120,50,26,300],[120,350,190,26],[250,0,26,190],[250,190,200,26],[420,190,26,210],[560,105,26,295],[445,105,141,26],[310,350,136,26]];
function mazeStartPos(){return actor()==='host'?{x:40,y:435}:{x:680,y:45}}
function circleRectHit(x,y,r,w){let nx=Math.max(w[0],Math.min(x,w[0]+w[2])),ny=Math.max(w[1],Math.min(y,w[1]+w[3]));return (x-nx)*(x-nx)+(y-ny)*(y-ny)<r*r}
function mazeCan(x,y){if(x<17||x>703||y<17||y>463)return false;for(const w of MAZE_WALLS)if(circleRectHit(x,y,14,w))return false;return true}
function initMazeGame(){mazeMine=mazeStartPos();mazeOther=actor()==='host'?{x:680,y:45}:{x:40,y:435};direct({t:'mazePos',x:mazeMine.x,y:mazeMine.y});cancelAnimationFrame(mazeFrame);mazeLast=performance.now();mazeLoop()}
applyAction=function(a,v,who){if(a==='game'&&v==='maze'){state={screen:'game',type:'maze',winner:null};sync();renderFromState();return}if(state.type==='maze'&&a==='maze_win'&&!state.winner){state.winner=who;sync();renderFromState();return}_auApply(a,v,who)};
handleMessage=function(m){if(m&&m.t==='mazePos'){mazeOther={x:Number(m.x)||0,y:Number(m.y)||0};drawMaze();return}_auHandle(m)};
renderGame=function(){if(state.type==='maze')return renderMaze();return _auRender()};
backMenu=function(){cancelAnimationFrame(joyFrame);cancelAnimationFrame(mazeFrame);joyFrame=mazeFrame=0;_auBack()};
function renderMaze(){$('roundPill').textContent='Гонка';$('bar').style.width=state.winner?'100%':'65%';let win=state.winner?(state.winner==='host'?hostName():guestName())+' победил(а) 🎉':'';$('gameCard').innerHTML=`<div class="bigemoji">🕹️</div><div class="question smallq">Доберись до ⭐ в центре</div>${win?`<div class="result">${esc(win)}</div>`:''}<canvas id="mazeCanvas" class="aircanvas"></canvas>${state.winner?'':joyHTML('Джойстик персонажа')}<div class="muted">Ты — ${actor()==='host'?'розовый':'фиолетовый'} кружок. Стены трогать нельзя.</div><div class="actions"><button class="ghost" onclick="openChat()">💬 Чат</button><button class="btn" onclick="dispatch('game','maze')">Новая гонка</button></div>`;requestAnimationFrame(()=>{mazeCanvas=$('mazeCanvas');if(!mazeCanvas)return;let r=mazeCanvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);mazeCanvas.width=Math.round(r.width*d);mazeCanvas.height=Math.round(r.width*(2/3)*d);mazeCanvas.style.height=(r.width*(2/3))+'px';mazeCtx=mazeCanvas.getContext('2d');mazeCtx.setTransform(mazeCanvas.width/720,0,0,mazeCanvas.height/480,0,0);if(!state.winner){initJoystick();initMazeGame()}else{mazeMine=mazeMine||mazeStartPos();drawMaze()}})}
function mazeLoop(t=performance.now()){if(state.type!=='maze'||state.winner)return;let dt=Math.min(.04,(t-mazeLast)/1000||.016);mazeLast=t;if(joy.active&&mazeMine){let speed=190,nx=mazeMine.x+joy.x*speed*dt,ny=mazeMine.y+joy.y*speed*dt;if(mazeCan(nx,mazeMine.y))mazeMine.x=nx;if(mazeCan(mazeMine.x,ny))mazeMine.y=ny;if(t-mazeSend>45){direct({t:'mazePos',x:mazeMine.x,y:mazeMine.y});mazeSend=t}if(Math.hypot(mazeMine.x-360,mazeMine.y-245)<31)dispatch('maze_win')}drawMaze();mazeFrame=requestAnimationFrame(mazeLoop)}
function drawMaze(){if(!mazeCtx||!mazeCanvas)return;let x=mazeCtx;x.clearRect(0,0,720,480);x.fillStyle='#15101d';x.fillRect(0,0,720,480);x.fillStyle='#ffffff18';for(const w of MAZE_WALLS)x.fillRect(...w);x.fillStyle='#ffd35a';x.font='34px system-ui';x.textAlign='center';x.fillText('★',360,256);let h=actor()==='host'?mazeMine:mazeOther,g=actor()==='guest'?mazeMine:mazeOther;if(h){x.fillStyle='#ff6fae';x.beginPath();x.arc(h.x,h.y,14,0,Math.PI*2);x.fill()}if(g){x.fillStyle='#9879ff';x.beginPath();x.arc(g.x,g.y,14,0,Math.PI*2);x.fill()}}
