// v6 reaction duel — first to 3 rounds
if(!GAMES.some(x=>x[0]==='duel')){GAMES.unshift(['duel','⚡','Дуэль реакции','Ждите сигнал «ОГОНЬ!» и нажмите быстрее соперника. Фальстарт проигрывает раунд.']);TITLES.duel='Дуэль реакции'}
if(typeof CAT!=='undefined')CAT.duel='Аркада';
let duelSignalStart=0,duelWaitTimer=0,duelMissTimer=0,duelPrevPhase='';
const _duApply=applyAction,_duRender=renderGame,_duHandle=handleMessage,_duBack=backMenu;
function freshDuel(scores={host:0,guest:0},round=1){return{screen:'game',type:'duel',phase:'ready',ready:{host:false,guest:false},shots:{host:null,guest:null},scores,round,winner:null,reason:'',matchOver:false}}
function clearDuelTimers(){clearTimeout(duelWaitTimer);clearTimeout(duelMissTimer);duelWaitTimer=duelMissTimer=0;duelSignalStart=0;duelPrevPhase=''}
function armDuelHost(){if(role!=='host'||state.type!=='duel'||state.phase!=='wait')return;clearTimeout(duelWaitTimer);let delay=1800+Math.floor(Math.random()*3300);duelWaitTimer=setTimeout(()=>{if(state.type!=='duel'||state.phase!=='wait')return;state.phase='fire';state.shots={host:null,guest:null};duelSignalStart=performance.now();sync();renderFromState();duelMissTimer=setTimeout(()=>{if(role==='host'&&state.type==='duel'&&state.phase==='fire')resolveDuelIfReady(true)},2600)},delay)}
function duelName(w){return w==='host'?hostName():guestName()}
function resolveDuelRound(winner,reason){if(role!=='host'||state.type!=='duel'||state.phase==='result')return;clearTimeout(duelWaitTimer);clearTimeout(duelMissTimer);state.phase='result';state.winner=winner;state.reason=reason||'';state.scores[winner]=(state.scores[winner]||0)+1;state.matchOver=state.scores[winner]>=3;sync();renderFromState()}
function resolveDuelIfReady(force=false){if(role!=='host'||state.type!=='duel'||state.phase!=='fire')return;let h=state.shots.host,g=state.shots.guest;if(!force&&(h===null||g===null))return;if(h===null)h=9999;if(g===null)g=9999;state.shots.host=h;state.shots.guest=g;if(h===g)return resolveDuelRound(Math.random()<.5?'host':'guest','Почти идеальная ничья — решило случайное преимущество.');resolveDuelRound(h<g?'host':'guest','Быстрее на '+Math.abs(h-g).toFixed(0)+' мс')}
function duelReady(){dispatch('duel_ready')}
function duelTrigger(){if(state.type!=='duel')return;if(state.phase==='wait'){dispatch('duel_shot',{early:true});return}if(state.phase!=='fire')return;let ms=duelSignalStart?Math.max(0,performance.now()-duelSignalStart):9999;dispatch('duel_shot',{ms:Math.round(ms)})}
applyAction=function(a,v,who){
 if(a==='game'&&v==='duel'){clearDuelTimers();state=freshDuel();sync();renderFromState();return}
 if(state.type==='duel'){
  if(a==='duel_ready'&&state.phase==='ready'){state.ready[who]=true;if(state.ready.host&&state.ready.guest){state.phase='wait';sync();renderFromState();armDuelHost();return}sync();renderFromState();return}
  if(a==='duel_shot'){
   if(state.phase==='wait'){return resolveDuelRound(who==='host'?'guest':'host',duelName(who)+' сделал(а) фальстарт')}
   if(state.phase==='fire'&&state.shots[who]===null){let ms=Number(v&&v.ms);state.shots[who]=Number.isFinite(ms)?Math.max(0,Math.min(9999,ms)):9999;resolveDuelIfReady(false);if(state.phase==='fire'){sync();renderFromState()}return}
  }
  if(a==='duel_next'&&state.phase==='result'){if(state.matchOver){clearDuelTimers();state=freshDuel();}else{let scores={host:state.scores.host,guest:state.scores.guest},round=state.round+1;clearDuelTimers();state=freshDuel(scores,round)}sync();renderFromState();return}
 }
 _duApply(a,v,who)
};
handleMessage=function(m){_duHandle(m)};
renderGame=function(){if(state.type==='duel')return renderDuel();return _duRender()};
backMenu=function(){clearDuelTimers();_duBack()};
function renderDuel(){
 let phase=state.phase||'ready';$('roundPill').textContent=`Раунд ${state.round||1} · ${state.scores?.host||0}:${state.scores?.guest||0}`;$('bar').style.width=((state.scores?.host||0)+(state.scores?.guest||0))/3*50+'%';
 if(phase!==duelPrevPhase){duelPrevPhase=phase;if(phase==='fire'&&!duelSignalStart)duelSignalStart=performance.now();if(phase!=='fire')duelSignalStart=0}
 let hs=state.scores?.host||0,gs=state.scores?.guest||0;
 let score=`<div class="duelScore"><div><small>${esc(hostName())}</small><b>${hs}</b></div><span>VS</span><div><small>${esc(guestName())}</small><b>${gs}</b></div></div>`;
 if(phase==='ready'){
  let mine=!!state.ready?.[actor()],other=!!state.ready?.[actor()==='host'?'guest':'host'];$('gameCard').innerHTML=`${score}<div class="duelScene"><div class="duelAvatar">🤠</div><div class="duelVs">⚡</div><div class="duelAvatar flip">🤠</div></div><div class="question smallq">Приготовься</div><div class="muted">После готовности обоих будет случайная пауза. Не нажимай раньше сигнала.</div><div class="actions"><button class="btn duelReadyBtn" ${mine?'disabled':''} onclick="duelReady()">${mine?(other?'Оба готовы':'Готов · ждём соперника'):'Я готов(а)'}</button><button class="ghost" onclick="openChat()">💬 Чат</button></div>`;return
 }
 if(phase==='wait'){$('gameCard').innerHTML=`${score}<div class="duelScene tense"><div class="duelAvatar">🤠</div><div class="duelVs">…</div><div class="duelAvatar flip">🤠</div></div><button class="duelFire wait" onclick="duelTrigger()"><span>ЖДИ…</span><small>Не нажимай — будет фальстарт</small></button>`;return}
 if(phase==='fire'){$('gameCard').innerHTML=`${score}<div class="duelScene fire"><div class="duelAvatar">🤠</div><div class="duelVs">💥</div><div class="duelAvatar flip">🤠</div></div><button class="duelFire go" onclick="duelTrigger()"><span>ОГОНЬ!</span><small>ЖМИ!</small></button><div class="muted">${state.shots?.[actor()]!==null?'Твой результат принят — ждём соперника…':'Кто быстрее?'}</div>`;return}
 let w=state.winner,won=actor()===w,h=state.shots?.host,g=state.shots?.guest,rows=(h!==null||g!==null)?`<div class="duelTimes"><div>${esc(hostName())}<b>${h===null?'—':h>=9000?'не нажал':Math.round(h)+' мс'}</b></div><div>${esc(guestName())}<b>${g===null?'—':g>=9000?'не нажал':Math.round(g)+' мс'}</b></div></div>`:'';
 $('gameCard').innerHTML=`${score}<div class="bigemoji">${won?'🏆':'⚡'}</div><div class="question">${state.matchOver?esc(duelName(w))+' выигрывает матч!':esc(duelName(w))+' выигрывает раунд!'}</div>${rows}<div class="resultReason">${esc(state.reason||'')}</div><div class="actions"><button class="btn" onclick="dispatch('duel_next')">${state.matchOver?'Новый матч':'Следующий раунд'}</button><button class="ghost" onclick="openChat()">💬 Чат</button></div>`
}
(function addDuelStyle(){if(document.getElementById('duelStyle'))return;let s=document.createElement('style');s.id='duelStyle';s.textContent=`.duelScore{display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:12px;max-width:520px;margin:8px auto 18px}.duelScore div{padding:11px;border:1px solid #ffffff18;border-radius:16px;background:#ffffff09}.duelScore small{display:block;color:var(--muted);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.duelScore b{font-size:30px}.duelScore>span{font-weight:900;color:#ffb44d}.duelScene{display:flex;align-items:center;justify-content:center;gap:clamp(24px,8vw,80px);min-height:135px;margin:8px 0}.duelAvatar{font-size:clamp(54px,13vw,88px);filter:drop-shadow(0 12px 20px #0008)}.duelAvatar.flip{transform:scaleX(-1)}.duelVs{font-size:36px;font-weight:900}.duelScene.tense{animation:duelPulse .85s ease-in-out infinite alternate}.duelScene.fire{animation:duelFlash .18s ease-out}@keyframes duelPulse{to{transform:scale(1.025)}}@keyframes duelFlash{from{filter:brightness(2.2)}}.duelFire{width:min(520px,100%);min-height:150px;border-radius:28px;border:2px solid #ffffff22;color:#fff;margin:8px auto 12px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:7px;font-weight:950;touch-action:manipulation;-webkit-tap-highlight-color:transparent}.duelFire span{font-size:clamp(34px,9vw,60px);letter-spacing:1px}.duelFire small{font-size:13px;font-weight:650}.duelFire.wait{background:linear-gradient(160deg,#2a2026,#171119);color:#d5c6cf}.duelFire.go{background:linear-gradient(145deg,#ff3e56,#ff8b35);box-shadow:0 0 45px #ff5b4766;animation:firePulse .38s ease-in-out infinite alternate}@keyframes firePulse{to{transform:scale(1.025);box-shadow:0 0 75px #ff5b4790}}.duelTimes{display:grid;grid-template-columns:1fr 1fr;gap:10px;max-width:520px;margin:14px auto}.duelTimes div{padding:13px;border-radius:16px;background:#ffffff0a;border:1px solid #ffffff14}.duelTimes b{display:block;font-size:21px;margin-top:4px}.resultReason{color:var(--muted);margin:8px 0 16px}.duelReadyBtn{min-width:200px}`;document.head.appendChild(s)})();
