function answerLabel(v,t){if(t==='who')return v==='host'?hostName():v==='guest'?guestName():'Оба';if(t==='rps')return {rock:'Камень ✊',paper:'Бумага ✋',scissors:'Ножницы ✌️'}[v];return v===0?'Вариант A':'Вариант B'}
function waitHTML(){return `<div class="muted">${state.answers[actor()]!==null?'Твой ответ принят. Ждём второго игрока…':'Выбери ответ. Он откроется после выбора обоих.'}</div>`}
function revealHTML(t){return `<div class="answers"><div class="answerbox"><small>${esc(hostName())}</small><b>${esc(answerLabel(state.answers.host,t))}</b></div><div class="answerbox"><small>${esc(guestName())}</small><b>${esc(answerLabel(state.answers.guest,t))}</b></div></div>`}
function option(v,label){let chosen=state.answers[actor()]===v,locked=state.answers[actor()]!==null;return `<button class="option ${chosen?'me':''} ${locked?'locked':''}" ${locked?'disabled':''} onclick='dispatch("answer",${JSON.stringify(v)})'>${esc(label)}</button>`}
function round(i,n){$('roundPill').textContent=`${i%n+1}/${n}`;$('bar').style.width=((i%n+1)/n*100)+'%'}
function nextButton(t){return `<div class="actions"><button class="btn" onclick="dispatch('next')">${t}</button></div>`}
function renderGame(){({who:renderWho,would:renderWould,compat:renderCompat,talk:renderTalk,truth:renderTruth,rps:renderRps}[state.type]||renderTalk)()}
function renderWho(){let q=WHO[state.idx%WHO.length];round(state.idx,WHO.length);let h=`<div class="eyebrow">Ответьте одновременно</div><div class="question">Кто из вас скорее ${esc(q)}</div>`;h+=state.reveal?revealHTML('who')+nextButton('Следующий вопрос'):`<div class="options">${option('host',hostName())}${option('guest',guestName())}${option('both','Оба 😄')}</div>${waitHTML()}`;$('gameCard').innerHTML=h}
function renderWould(){let q=WOULD[state.idx%WOULD.length];round(state.idx,WOULD.length);let h=`<div class="eyebrow">${esc(q[0])}</div><div class="question">Что бы ты выбрал?</div>`;h+=state.reveal?revealHTML('would')+`<div class="muted">A · ${esc(q[1])}<br>B · ${esc(q[2])}</div>`+nextButton('Следующая дилемма'):`<div class="options">${option(0,'A · '+q[1])}${option(1,'B · '+q[2])}</div>${waitHTML()}`;$('gameCard').innerHTML=h}
function renderCompat(){let total=COMPAT.length;if(state.done){$('roundPill').textContent='Результат';$('bar').style.width='100%';let pct=Math.round(state.matches/total*100),txt=pct>=80?'У вас очень много одинаковых выборов 💞':pct>=50?'Хороший баланс общего и различий ✨':'Вы часто выбираете по-разному — зато можете удивлять друг друга 💫';$('gameCard').innerHTML=`<div class="bigemoji">💖</div><div class="result">${pct}% совпадений</div><div class="question">${txt}</div><div class="muted">Это развлекательный тест.</div><div class="actions"><button class="btn" onclick="dispatch('game','compat')">Пройти снова</button></div>`;return}let q=COMPAT[state.idx];round(state.idx,total);let h=`<div class="eyebrow">${esc(q[0])}</div><div class="question">Выбери ближе тебе</div>`;h+=state.reveal?revealHTML('compat')+`<div class="muted">A · ${esc(q[1])}<br>B · ${esc(q[2])}</div>`+nextButton(state.idx===total-1?'Показать результат':'Дальше'):`<div class="options">${option(0,'A · '+q[1])}${option(1,'B · '+q[2])}</div>${waitHTML()}`;$('gameCard').innerHTML=h}
function renderTalk(){let q=TALK[state.idx%TALK.length];round(state.idx,TALK.length);$('gameCard').innerHTML=`<div class="bigemoji">💬</div><div class="eyebrow">Обсудите вдвоём</div><div class="question">${esc(q)}</div><div class="muted">Сначала отвечает один, потом второй.</div>${nextButton('Следующий вопрос')}`}
function renderTruth(){let x=TRUTH[state.idx%TRUTH.length];$('roundPill').textContent=x[0];$('bar').style.width='100%';$('gameCard').innerHTML=`<div class="bigemoji">${x[0]==='Правда'?'💬':'⚡'}</div><div class="eyebrow">${x[0]}</div><div class="question">${esc(x[1])}</div>${nextButton('Ещё карточка')}`}
function rpsResult(a,b){if(a===b)return'Ничья 😄';return((a==='rock'&&b==='scissors')||(a==='scissors'&&b==='paper')||(a==='paper'&&b==='rock')?esc(hostName()):esc(guestName()))+' побеждает 🎉'}
function renderRps(){$('roundPill').textContent='Раунд';$('bar').style.width='100%';let h='<div class="eyebrow">Выбор скрыт до ответа обоих</div><div class="question">Камень, ножницы или бумага?</div>';h+=state.reveal?revealHTML('rps')+`<div class="result">${rpsResult(state.answers.host,state.answers.guest)}</div><div class="actions"><button class="btn" onclick="dispatch('game','rps')">Ещё раунд</button></div>`:`<div class="options">${option('rock','Камень ✊')}${option('scissors','Ножницы ✌️')}${option('paper','Бумага ✋')}</div>${waitHTML()}`;$('gameCard').innerHTML=h}