// v5: in-app chat, written replies and extra turn-based games
const ASSOC_PROMPTS=['море','ночь','поцелуй','дом','лето','ревность','путешествие','уют','сюрприз','музыка','свидание','будущее','счастье','приключение','дождь','мечта','выходной','подарок'];
const ONEWORD_PROMPTS=['Опиши наши отношения одним словом','Какое слово лучше всего описывает меня сегодня?','Какое слово описывает наше идеальное свидание?','Что нам сейчас нужнее всего? Одно слово','Какое слово напоминает тебе о нашей первой встрече?','Как одним словом описать наш следующий совместный месяц?'];
[['assoc','🔗','Ассоциации','Одно слово — два скрытых ответа. Посмотрите, думаете ли вы одинаково.'],['oneword','🪄','Одним словом','Короткие ответы открываются одновременно — иногда получается очень смешно.'],['ttt','⭕','Крестики-нолики','Классика 1×1 прямо в вашей комнате.'],['connect4','🟣','Четыре в ряд','Соберите четыре фишки раньше партнёра.']].forEach(g=>{if(!GAMES.some(x=>x[0]===g[0])){GAMES.push(g);TITLES[g[0]]=g[2]}});

let roomChat=[],chatUnread=0,cardReply={key:'',mine:'',other:''};
const _suHandle=handleMessage,_suApply=applyAction,_suRender=renderGame,_suRenderMenu=renderMenu,_suRenderFrom=renderFromState,_suLobby=renderLobby;

function injectChat(){if(document.getElementById('chatFab'))return;document.body.insertAdjacentHTML('beforeend',`<button id="chatFab" class="chatFab" onclick="toggleChat()">💬 Чат <span id="chatBadge" class="chatBadge"></span></button><aside id="chatPanel" class="chatPanel"><div class="chatHead"><b>💬 Чат комнаты</b><span id="chatWho" class="muted"></span><button class="ghost" onclick="toggleChat(false)">✕</button></div><div id="chatMessages" class="chatMessages"></div><div class="quickReacts">${['❤️','😂','😈','👀','😘','🔥'].map(x=>`<button class="reactBtn" onclick="sendChat('${x}')">${x}</button>`).join('')}</div><div class="chatComposer"><input id="chatInput" maxlength="500" placeholder="Написать сообщение…"><button class="btn" onclick="sendChatInput()">➤</button></div></aside>`);let i=$('chatInput');if(i)i.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();sendChatInput()}})}
function updateChatVisibility(){injectChat();let f=$('chatFab');if(f)f.classList.toggle('on',!!connected);let w=$('chatWho');if(w)w.textContent=connected?(hostName()+' + '+guestName()):''}
function toggleChat(force){injectChat();let p=$('chatPanel'),open=typeof force==='boolean'?force:!p.classList.contains('on');p.classList.toggle('on',open);if(open){chatUnread=0;updateChatBadge();renderChat();setTimeout(()=>$('chatInput')?.focus(),50)}}
function openChat(prefill=''){toggleChat(true);if(prefill){let i=$('chatInput');if(i){i.value=prefill;i.focus()}}}
function updateChatBadge(){let b=$('chatBadge');if(!b)return;b.textContent=chatUnread>99?'99+':chatUnread;b.classList.toggle('on',chatUnread>0)}
function addChat(author,text,mine){roomChat.push({author:String(author||'Игрок').slice(0,24),text:String(text||'').slice(0,500),mine,time:Date.now()});if(roomChat.length>150)roomChat.shift();if(!mine&&!$('chatPanel')?.classList.contains('on')){chatUnread++;updateChatBadge();toast('💬 Новое сообщение')}renderChat()}
function renderChat(){let box=$('chatMessages');if(!box)return;box.innerHTML=roomChat.map(m=>`<div class="msg ${m.mine?'me':''}"><small>${esc(m.author)}</small>${esc(m.text)}</div>`).join('');box.scrollTop=box.scrollHeight}
function sendChat(text){text=String(text||'').trim();if(!text||!connected)return;if(text.length>500)text=text.slice(0,500);addChat(myName,text,true);send({t:'chat',name:myName,text})}
function sendChatInput(){let i=$('chatInput');if(!i)return;let t=i.value.trim();if(!t)return;sendChat(t);i.value=''}

function replyKey(){return `${state.type||''}:${state.idx||0}`}
function ensureReply(){let k=replyKey();if(cardReply.key!==k)cardReply={key:k,mine:'',other:''}}
function submitCardReply(){ensureReply();let i=$('cardAnswerInput');if(!i||!i.value.trim())return;cardReply.mine=i.value.trim().slice(0,500);send({t:'cardReply',key:cardReply.key,text:cardReply.mine});renderGame()}
function replyComposer(label='Напиши ответ'){ensureReply();let both=cardReply.mine&&cardReply.other;if(both)return `<div class="textReveal"><div class="answerbox"><small>${esc(myName)}</small><b>${esc(cardReply.mine)}</b></div><div class="answerbox"><small>${esc(otherName||'Партнёр')}</small><b>${esc(cardReply.other)}</b></div></div>`;if(cardReply.mine)return `<div class="turnBanner">✓ Ответ отправлен. Ждём партнёра…</div><div class="actions"><button class="ghost" onclick="openChat()">💬 Открыть чат</button></div>`;return `<div class="answerComposer"><textarea id="cardAnswerInput" maxlength="500" placeholder="${esc(label)}"></textarea><div class="actions"><button class="btn" onclick="submitCardReply()">Отправить ответ</button><button class="ghost" onclick="openChat()">💬 Просто написать в чат</button></div></div>`}

handleMessage=function(m){if(m&&m.t==='chat'){addChat(m.name||otherName||'Партнёр',m.text,false);return}if(m&&m.t==='cardReply'){ensureReply();if(m.key===cardReply.key){cardReply.other=String(m.text||'').slice(0,500);renderGame()}return}_suHandle(m);updateChatVisibility()};

function win3(b){const L=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];for(const l of L)if(b[l[0]]&&b[l[0]]===b[l[1]]&&b[l[1]]===b[l[2]])return b[l[0]];return b.every(Boolean)?'draw':null}
function win4(b){const at=(r,c)=>b[r*7+c];for(let r=0;r<6;r++)for(let c=0;c<7;c++){let v=at(r,c);if(!v)continue;if(c<=3&&v===at(r,c+1)&&v===at(r,c+2)&&v===at(r,c+3))return v;if(r<=2&&v===at(r+1,c)&&v===at(r+2,c)&&v===at(r+3,c))return v;if(r<=2&&c<=3&&v===at(r+1,c+1)&&v===at(r+2,c+2)&&v===at(r+3,c+3))return v;if(r<=2&&c>=3&&v===at(r+1,c-1)&&v===at(r+2,c-2)&&v===at(r+3,c-3))return v}return b.every(Boolean)?'draw':null}
applyAction=function(a,v,who){
 if(a==='game'&&v==='ttt'){state={screen:'game',type:'ttt',board:Array(9).fill(null),turn:'host',winner:null};sync();renderFromState();return}
 if(a==='game'&&v==='connect4'){state={screen:'game',type:'connect4',board:Array(42).fill(null),turn:'host',winner:null};sync();renderFromState();return}
 if(a==='game'&&(v==='assoc'||v==='oneword')){let arr=v==='assoc'?ASSOC_PROMPTS:ONEWORD_PROMPTS;state={screen:'game',type:v,idx:Math.floor(Math.random()*arr.length)};cardReply={key:'',mine:'',other:''};sync();renderFromState();return}
 if(state.type==='ttt'&&a==='ttt'&&!state.winner&&who===state.turn&&Number.isInteger(v)&&v>=0&&v<9&&!state.board[v]){state.board[v]=who;state.winner=win3(state.board);if(!state.winner)state.turn=who==='host'?'guest':'host';sync();renderFromState();return}
 if(state.type==='connect4'&&a==='drop'&&!state.winner&&who===state.turn&&Number.isInteger(v)&&v>=0&&v<7){for(let r=5;r>=0;r--){let i=r*7+v;if(!state.board[i]){state.board[i]=who;state.winner=win4(state.board);if(!state.winner)state.turn=who==='host'?'guest':'host';sync();renderFromState();return}}return}
 if((state.type==='assoc'||state.type==='oneword')&&a==='next'){let arr=state.type==='assoc'?ASSOC_PROMPTS:ONEWORD_PROMPTS;state.idx=(state.idx+1)%arr.length;cardReply={key:'',mine:'',other:''};sync();renderFromState();return}
 _suApply(a,v,who);updateChatVisibility();
};

function renderTtt(){let mine=actor()===state.turn,n=state.turn==='host'?hostName():guestName();$('roundPill').textContent='1×1';$('bar').style.width='100%';let result=state.winner?(state.winner==='draw'?'Ничья 😄':(state.winner==='host'?hostName():guestName())+' победил(а) 🎉'):(mine?'Твой ход':'Ходит '+n);$('gameCard').innerHTML=`<div class="bigemoji">⭕</div><div class="turnBanner">${esc(result)}</div><div class="board3">${state.board.map((v,i)=>`<button class="cell3" ${state.winner||!mine||v?'disabled':''} onclick="dispatch('ttt',${i})">${v==='host'?'✕':v==='guest'?'○':''}</button>`).join('')}</div><div class="actions"><button class="ghost" onclick="openChat()">💬 Чат</button><button class="btn" onclick="dispatch('game','ttt')">Новая партия</button></div>`}
function renderConnect4(){let mine=actor()===state.turn,n=state.turn==='host'?hostName():guestName();$('roundPill').textContent='1×1';$('bar').style.width='100%';let result=state.winner?(state.winner==='draw'?'Ничья 😄':(state.winner==='host'?hostName():guestName())+' победил(а) 🎉'):(mine?'Твой ход':'Ходит '+n);$('gameCard').innerHTML=`<div class="turnBanner">${esc(result)}</div><div class="connectCols">${Array.from({length:7},(_,c)=>`<button ${!mine||state.winner?'disabled':''} onclick="dispatch('drop',${c})">↓</button>`).join('')}</div><div class="connectBoard">${state.board.map(v=>`<div class="connectCell ${v==='host'?'h':v==='guest'?'g':''}"></div>`).join('')}</div><div class="actions"><button class="ghost" onclick="openChat()">💬 Чат</button><button class="btn" onclick="dispatch('game','connect4')">Новая партия</button></div>`}
function renderAssoc(){let arr=state.type==='assoc'?ASSOC_PROMPTS:ONEWORD_PROMPTS,q=arr[state.idx%arr.length];round(state.idx,arr.length);let isAssoc=state.type==='assoc';$('gameCard').innerHTML=`<div class="bigemoji">${isAssoc?'🔗':'🪄'}</div><div class="eyebrow">${isAssoc?'Напишите первую ассоциацию':'Ответьте максимально коротко'}</div><div class="question">${esc(q)}</div>${replyComposer(isAssoc?'Первое слово, которое пришло в голову…':'Одно слово…')}${cardReply.mine&&cardReply.other?nextButton('Следующая карточка'):''}`}

renderGame=function(){if(state.type==='ttt')return renderTtt();if(state.type==='connect4')return renderConnect4();if(state.type==='assoc'||state.type==='oneword')return renderAssoc();return _suRender()};

// Replace conversation-heavy cards with written, in-site replies.
renderTalk=function(){let q=TALK[state.idx%TALK.length];round(state.idx,TALK.length);$('gameCard').innerHTML=`<div class="bigemoji">💬</div><div class="eyebrow">Ответьте прямо здесь</div><div class="question">${esc(q)}</div>${replyComposer('Напиши свой ответ…')}${cardReply.mine&&cardReply.other?nextButton('Следующий вопрос'):''}`}
renderIce=function(){round(state.idx,ICEBREAKERS.length);$('gameCard').innerHTML=`<div class="bigemoji">🧊</div><div class="eyebrow">Когда переписка застопорилась</div><div class="question">${esc(ICEBREAKERS[state.idx%ICEBREAKERS.length])}</div>${replyComposer('Ответь прямо в игре…')}${cardReply.mine&&cardReply.other?nextButton('Другая тема'):''}`}
const _suFlirt=renderFlirt;
renderFlirt=function(){if(!(state.consent?.host&&state.consent?.guest))return _suFlirt();let x=FLIRT[state.idx%FLIRT.length];$('roundPill').textContent='По желанию';$('bar').style.width='100%';$('gameCard').innerHTML=`<div class="bigemoji">${x[0]==='18+'?'🌶️':x[0]==='Челлендж'?'⚡':'💘'}</div><div class="eyebrow">${esc(x[0])}</div><div class="question">${esc(x[1])}</div>${replyComposer(x[0]==='Челлендж'?'Напиши, как выполнил(а), или ответ…':'Напиши ответ…')}${cardReply.mine&&cardReply.other?nextButton('Следующая карточка'):''}`}
const _suHide=renderHide;
renderHide=function(){_suHide();if(state.phase==='guess'){let a=$('gameCard');if(a)a.insertAdjacentHTML('beforeend',`<div class="actions"><button class="ghost" onclick="openChat('Вопрос: ')">💬 Задать вопрос в чате</button></div>`)} }

const CATEGORY_ORDER=['Аркада','Игры словами','Тесты для пары','Поговорить и посмеяться','Флирт'];
const CAT={air:'Аркада',ttt:'Аркада',connect4:'Аркада',rps:'Аркада',crocodile:'Аркада',hide:'Игры словами',assoc:'Игры словами',oneword:'Игры словами',would:'Игры словами',who:'Игры словами',compat:'Тесты для пары',values:'Тесты для пары',distance:'Тесты для пары',birthday:'Тесты для пары',talk:'Поговорить и посмеяться',ice:'Поговорить и посмеяться',truth:'Поговорить и посмеяться',flirt:'Флирт'};
renderMenu=function(){$('menuPlayers').textContent=hostName()+' + '+guestName();$('menuCode').textContent=roomCode;let html='';for(const c of CATEGORY_ORDER){let gs=GAMES.filter(g=>(CAT[g[0]]||'Поговорить и посмеяться')===c);if(!gs.length)continue;html+=`<div class="sectionTitle">${esc(c)}</div>`+gs.map(g=>`<button class="tile" onclick="chooseGame('${g[0]}')"><div class="ico">${g[1]}</div><b>${g[2]}</b><span>${g[3]}</span><em class="badge">${g[0]==='air'?'Джойстик':g[0]==='crocodile'?'Рисование':g[0]==='flirt'?'18+ по согласию':g[0]==='birthday'?'Развлекательный':'Для двоих'}</em></button>`).join('')} $('gamesGrid').innerHTML=html;updateChatVisibility()};
renderFromState=function(){_suRenderFrom();updateChatVisibility()};
renderLobby=function(){_suLobby();updateChatVisibility()};
injectChat();updateChatVisibility();