// v20: more low-latency variety games + consent-gated non-graphic adult preference deck

// ---------------- Adult preference deck ----------------
const V20_TRY_CARDS=[
 ['Атмосфера','Устроить вечер только вдвоём без телефонов'],['Атмосфера','Приглушить свет и включить любимую музыку'],['Атмосфера','Сделать красивый домашний вечер вместо выхода куда-то'],['Атмосфера','Устроить ночную прогулку без заранее заданного маршрута'],['Атмосфера','Выбрать друг другу плейлист для романтического вечера'],['Атмосфера','Сделать свидание с одной выбранной темой или цветом'],['Атмосфера','Встретиться наряднее обычного просто без повода'],['Атмосфера','Устроить вечер, где один полностью придумывает план'],['Атмосфера','Оставить часть вечера сюрпризом до самого момента'],['Атмосфера','Устроить домашнее мини-свидание с красивой сервировкой'],
 ['Флирт','Первым начать флирт неожиданным комплиментом'],['Флирт','Отправить голосовое с очень тёплым комплиментом'],['Флирт','Весь день иногда отправлять друг другу короткие намёки'],['Флирт','Придумать друг другу новое мило-дерзкое прозвище'],['Флирт','Сказать три вещи, которые особенно притягивают в партнёре'],['Флирт','Попробовать дольше держать взгляд, прежде чем что-то сказать'],['Флирт','Устроить мини-игру: кто первым смутит второго комплиментом'],['Флирт','Написать сообщение так, будто вы только начинаете знакомиться'],['Флирт','Выбрать один вечер, когда инициативу во флирте берёт один человек'],['Флирт','Придумать секретную фразу, которая означает «хочу больше флирта»'],
 ['Нежность','Дольше обниматься при встрече и никуда не спешить'],['Нежность','Устроить медленный танец дома'],['Нежность','Сделать друг другу массаж плеч или спины после тяжёлого дня'],['Нежность','Полежать рядом и просто поговорить без телефонов'],['Нежность','Засыпать на звонке или видео, если вы далеко'],['Нежность','Чаще говорить прямо, когда хочется объятий или близости'],['Нежность','Сделать вечер максимально спокойным и нежным'],['Нежность','Вспомнить самый тёплый момент вместе и рассказать, почему он важен'],['Нежность','Оставить друг другу короткую романтическую записку'],['Нежность','Составить список маленьких вещей, которые помогают чувствовать заботу'],
 ['Поцелуи','Долгий поцелуй при встрече после разлуки'],['Поцелуи','Неожиданный поцелуй в обычный момент'],['Поцелуи','Поцелуй перед уходом сделать вашим маленьким ритуалом'],['Поцелуи','Спросить друг друга, какой поцелуй запомнился больше всего'],['Поцелуи','Чаще проявлять инициативу первым(ой)'],['Поцелуи','Сделать паузу перед поцелуем и не торопить момент'],['Поцелуи','Устроить свидание, где главным будет не место, а близость и разговор'],['Поцелуи','Встретиться и первые несколько минут вообще не смотреть в телефон'],
 ['Инициатива','По очереди полностью выбирать формат свидания'],['Инициатива','Дать партнёру придумать сюрприз без подсказок'],['Инициатива','Сказать прямо, чего хочется больше в ваших романтических моментах'],['Инициатива','Чаще самому(ой) делать первый шаг к примирению и нежности'],['Инициатива','Один вечер позволить партнёру задавать темп планов'],['Инициатива','Поменяться привычными ролями: кто обычно планирует — отдыхает'],['Инициатива','Попробовать говорить желания прямо вместо намёков'],['Инициатива','Выбрать по одной новой романтической идее друг для друга'],
 ['Свидание','Устроить свидание на рассвете'],['Свидание','Устроить поздний пикник или чай на улице'],['Свидание','Выбрать случайное место на карте и пойти туда'],['Свидание','Сходить туда, где ни один из вас раньше не был'],['Свидание','Устроить свидание за минимальный бюджет'],['Свидание','Одеться друг для друга так, как партнёру особенно нравится'],['Свидание','Повторить одно из первых ваших свиданий'],['Свидание','Устроить вечер вопросов друг о друге вместо фильма'],['Свидание','Сделать совместную фотопрогулку'],['Свидание','Вместе приготовить блюдо, которое никто раньше не делал'],
 ['Расстояние','Устроить синхронный ужин по видеосвязи'],['Расстояние','Одновременно включить один фильм и переписываться по ходу'],['Расстояние','Отправлять друг другу одно фото дня без объяснения'],['Расстояние','Записать друг другу длинное голосовое перед сном'],['Расстояние','Устроить виртуальное свидание с одинаковой едой'],['Расстояние','Составить список того, что хотите сделать при следующей встрече'],['Расстояние','Отправить маленький сюрприз доставкой'],['Расстояние','Вместе выбрать место будущей поездки'],['Расстояние','Устроить один час видеосвязи, занимаясь каждый своими делами'],['Расстояние','Сделать общий плейлист до следующей встречи'],
 ['Новое','Попробовать новое совместное хобби на один вечер'],['Новое','Поменяться музыкальными плейлистами на день'],['Новое','Выбрать друг другу одежду или образ для свидания'],['Новое','Устроить мини-квест друг для друга из трёх заданий'],['Новое','Вместе придумать новый ритуал вашей пары'],['Новое','Сделать коробку идей для будущих свиданий'],['Новое','Устроить день, где каждый предлагает по одной спонтанной идее'],['Новое','Попробовать приготовить кухню новой страны'],['Новое','Записать совместный список «50 вещей, которые хотим попробовать»'],['Новое','Устроить вечер без привычного фильма, сериала и соцсетей'],
 ['Разговор','Обсудить, что помогает каждому чувствовать себя желанным и любимым'],['Разговор','Спросить друг друга, чего стало не хватать в последнее время'],['Разговор','Рассказать, какой комплимент особенно приятно получать'],['Разговор','Обсудить, кому и когда комфортнее проявлять инициативу'],['Разговор','Назвать три границы, которые важно всегда уважать'],['Разговор','Придумать слово, которое означает «давай замедлимся»'],['Разговор','Придумать слово, которое означает «мне всё комфортно»'],['Разговор','Спросить, какие романтические сюрпризы точно нравятся, а какие нет'],['Разговор','Рассказать, что делает близкий момент безопасным и спокойным'],['Разговор','Сказать, о чём хотелось бы чаще говорить без стеснения']
];

if(!GAMES.some(g=>g[0]==='trytogether'))GAMES.push(['trytogether','💞','Пробуем? 18+','Большая колода идей: каждый выбирает «Пробуем», «Может быть» или «Нет», затем открываются совпадения.']);
TITLES.trytogether='💞 Пробуем? 18+';
if(typeof CAT!=='undefined')CAT.trytogether='🌶️ Пошлое 18+';
if(typeof V19_ADULT_IDS!=='undefined')V19_ADULT_IDS.add('trytogether');

function v20TryNew(){return{screen:'game',type:'trytogether',idx:Math.floor(Math.random()*V20_TRY_CARDS.length),consent:{host:false,guest:false},answers:{host:null,guest:null},reveal:false,seen:0,yesMatches:0,maybeMatches:0}}
function v20TryGate(){const yes=!!state.consent?.[actor()];$('roundPill').textContent='18+ · согласие обоих';$('bar').style.width='25%';$('gameCard').innerHTML=`<div class="bigemoji">💞</div><div class="question">Пробуем? · только 18+</div><div class="muted">Это не список обязательств. Каждый отвечает отдельно. «Нет» всегда означает просто «нет», без объяснений и давления. Раздел не содержит подробных сексуальных инструкций.</div><div class="actions"><button class="btn" ${yes?'disabled':''} onclick="dispatch('v20_try_consent',true)">${yes?'Ты подтвердил(а) · ждём партнёра':'Мне 18+ и я хочу играть'}</button><button class="ghost" onclick="backMenu()">Не сейчас</button></div>`}
function v20TryLabel(v){return v==='yes'?'🔥 Пробуем':v==='maybe'?'✨ Может быть':'🤍 Нет'}
function renderV20Try(){
 if(!(state.consent?.host&&state.consent?.guest))return v20TryGate();
 const [cat,text]=V20_TRY_CARDS[state.idx%V20_TRY_CARDS.length],mine=state.answers?.[actor()];$('roundPill').textContent=`18+ · ${state.seen+1}`;$('bar').style.width=state.reveal?'100%':'62%';
 let h=`<div class="v20TryStats"><span>🔥 совпало: <b>${state.yesMatches||0}</b></span><span>✨ возможно: <b>${state.maybeMatches||0}</b></span></div><div class="eyebrow">${esc(cat)}</div><div class="question">${esc(text)}</div>`;
 if(!state.reveal){
   if(mine==null)h+=`<div class="v20TryButtons"><button onclick="dispatch('v20_try_answer','yes')">🔥 Пробуем</button><button onclick="dispatch('v20_try_answer','maybe')">✨ Может быть</button><button onclick="dispatch('v20_try_answer','no')">🤍 Нет</button></div><div class="muted">Ответ партнёра откроется только после твоего выбора.</div>`;
   else h+=`<div class="turnBanner">✓ Твой выбор сохранён. Ждём партнёра…</div>`;
 }else{
   const a=state.answers.host,b=state.answers.guest,bothYes=a==='yes'&&b==='yes',soft=a!=='no'&&b!=='no'&&!bothYes;
   h+=`<div class="v19Reveal"><div><small>${esc(hostName())}</small><b>${esc(v20TryLabel(a))}</b></div><div><small>${esc(guestName())}</small><b>${esc(v20TryLabel(b))}</b></div></div><div class="v20TryResult ${bothYes?'hot':soft?'soft':''}">${bothYes?'🔥 Оба хотите попробовать':soft?'✨ Можно спокойно обсудить':'🤍 Оставляем эту идею'}</div><div class="actions"><button class="btn" onclick="dispatch('v20_try_next')">Следующая идея</button><button class="ghost" onclick="backMenu()">Закончить</button></div>`;
 }
 $('gameCard').innerHTML=h;
}

// ---------------- New easy games ----------------
const V20_NEW_GAMES=[
 ['oddone','👀','Найди лишний','На поле почти одинаковые эмодзи. Кто первым нажмёт на отличающийся — берёт раунд.'],
 ['anagram','🔤','Анаграммы','Соберите слово из перемешанных букв. Кто первым введёт правильный ответ — получает очко.'],
 ['secret30','🔐','Секретное число','Один загадывает число от 1 до 30, второй ищет его по подсказкам больше/меньше.'],
 ['doors3','🚪','Три двери','Оба выбирают дверь. За одной спрятана звезда — пять коротких раундов удачи.']
];
for(const g of V20_NEW_GAMES)if(!GAMES.some(x=>x[0]===g[0])){GAMES.push(g);TITLES[g[0]]=g[2]}
if(typeof CAT!=='undefined')Object.assign(CAT,{oddone:'Лёгкие игры',anagram:'Игры словами',secret30:'Настолки',doors3:'Лёгкие игры'});

function v20Other(w){return w==='host'?'guest':'host'}
function v20Name(w){return w==='host'?hostName():guestName()}

// Odd one out
const V20_ODD_EMOJI=['😀','😎','🥰','🐱','🐶','🍓','🍋','🌙','⭐','🌸','🍀','🎈','🍕','🍩','⚽','🎲','🚗','🚀','💎','🧸'];
function v20OddNew(){return{screen:'game',type:'oddone',round:1,seed:Math.floor(Math.random()*1e9),score:{host:0,guest:0},roundWinner:null,winner:null}}
function v20OddData(){let base=V20_ODD_EMOJI[state.seed%V20_ODD_EMOJI.length],odd=V20_ODD_EMOJI[(state.seed*7+3)%V20_ODD_EMOJI.length];if(odd===base)odd=V20_ODD_EMOJI[(V20_ODD_EMOJI.indexOf(base)+1)%V20_ODD_EMOJI.length];return{base,odd,pos:(state.seed*13+state.round*17)%42}}
function v20OddPick(i,who){if(state.roundWinner||state.winner)return;const d=v20OddData();if(Number(i)!==d.pos)return;state.roundWinner=who;state.score[who]++;if(state.score[who]>=3)state.winner=who;sync();renderFromState()}
function v20OddNext(){if(!state.roundWinner||state.winner)return;state.round++;state.seed=Math.floor(Math.random()*1e9);state.roundWinner=null;sync();renderFromState()}
function renderV20Odd(){const d=v20OddData();$('roundPill').textContent=`Раунд ${state.round}`;$('bar').style.width=Math.min(100,(state.score.host+state.score.guest)/5*100)+'%';let h=`<div class="v20Score"><b>${state.score.host}</b><span>${esc(hostName())} · ${esc(guestName())}</span><b>${state.score.guest}</b></div><div class="question">Найди лишний символ</div><div class="v20OddGrid">${Array.from({length:42},(_,i)=>`<button ${state.roundWinner||state.winner?'disabled':''} onclick="dispatch('v20_odd_pick',${i})">${i===d.pos?d.odd:d.base}</button>`).join('')}</div>`;if(state.winner)h+=`<div class="result">🏆 ${esc(v20Name(state.winner))} победил(а)!</div><div class="actions"><button class="btn" onclick="dispatch('game','oddone')">Ещё партия</button></div>`;else if(state.roundWinner)h+=`<div class="turnBanner">⚡ ${esc(v20Name(state.roundWinner))} нашёл(ла) первым!</div><div class="actions"><button class="btn" onclick="dispatch('v20_odd_next')">Следующий раунд</button></div>`;$('gameCard').innerHTML=h}

// Anagrams
const V20_WORDS=[['апельсин','фрукт'],['ромашка','цветок'],['телефон','вещь'],['путешествие','приключение'],['кофейня','место'],['мороженое','десерт'],['облако','небо'],['подарок','сюрприз'],['космос','далеко'],['фонарик','свет'],['чемодан','поездка'],['музыка','звук'],['кактус','растение'],['пингвин','животное'],['радуга','после дождя'],['подушка','сон'],['кроссовки','обувь'],['шоколад','сладкое'],['кинотеатр','фильм'],['велосипед','транспорт'],['будильник','утро'],['наушники','музыка'],['пицца','еда'],['черепаха','животное'],['фотография','память'],['календарь','даты'],['библиотека','книги'],['снежинка','зима'],['комплимент','приятные слова'],['свидание','встреча']];
function v20ShuffleWord(w,seed){let a=[...w],x=seed||1;for(let i=a.length-1;i>0;i--){x=(x*1664525+1013904223)>>>0;let j=x%(i+1);[a[i],a[j]]=[a[j],a[i]]}let s=a.join('');return s===w?a.reverse().join(''):s}
function v20AnaNew(){return{screen:'game',type:'anagram',round:1,wordIdx:Math.floor(Math.random()*V20_WORDS.length),seed:Math.floor(Math.random()*1e9),score:{host:0,guest:0},roundWinner:null,winner:null}}
function v20AnaGuess(v,who){if(state.roundWinner||state.winner)return;const word=V20_WORDS[state.wordIdx][0];if(String(v||'').trim().toLowerCase()!==word)return toast('Пока не то 🙂');state.roundWinner=who;state.score[who]++;if(state.score[who]>=3)state.winner=who;sync();renderFromState()}
function v20AnaNext(){if(!state.roundWinner||state.winner)return;state.round++;state.wordIdx=(state.wordIdx+7+state.round)%V20_WORDS.length;state.seed=Math.floor(Math.random()*1e9);state.roundWinner=null;sync();renderFromState()}
function renderV20Ana(){const [word,clue]=V20_WORDS[state.wordIdx],mix=v20ShuffleWord(word,state.seed);$('roundPill').textContent=`Раунд ${state.round}`;$('bar').style.width=Math.min(100,(state.score.host+state.score.guest)/5*100)+'%';let h=`<div class="v20Score"><b>${state.score.host}</b><span>${esc(hostName())} · ${esc(guestName())}</span><b>${state.score.guest}</b></div><div class="eyebrow">Подсказка: ${esc(clue)}</div><div class="v20Letters">${[...mix].map(c=>`<i>${esc(c.toUpperCase())}</i>`).join('')}</div>`;if(!state.roundWinner&&!state.winner)h+=`<div class="guessrow"><input id="v20Ana" autocomplete="off" placeholder="Какое слово?"><button class="btn" onclick="dispatch('v20_ana_guess',$('v20Ana').value)">Ответить</button></div>`;if(state.roundWinner)h+=`<div class="turnBanner">✅ ${esc(v20Name(state.roundWinner))}: ${esc(word)}</div>`;if(state.winner)h+=`<div class="result">🏆 ${esc(v20Name(state.winner))} победил(а)!</div><div class="actions"><button class="btn" onclick="dispatch('game','anagram')">Ещё партия</button></div>`;else if(state.roundWinner)h+=`<div class="actions"><button class="btn" onclick="dispatch('v20_ana_next')">Следующее слово</button></div>`;$('gameCard').innerHTML=h}

// Secret number
function v20SecretNew(){return{screen:'game',type:'secret30',round:1,setter:'host',secret:null,phase:'set',attempts:0,last:null,score:{host:0,guest:0}}}
function v20SecretSet(v,who){if(state.phase!=='set'||who!==state.setter)return;v=Math.round(Number(v));if(v<1||v>30)return;state.secret=v;state.phase='guess';state.attempts=0;state.last=null;sync();renderFromState()}
function v20SecretGuess(v,who){if(state.phase!=='guess'||who===state.setter)return;v=Math.round(Number(v));if(v<1||v>30)return;state.attempts++;if(v===state.secret){state.last='hit';state.score[who]++;state.phase='done'}else state.last=v<state.secret?'up':'down';sync();renderFromState()}
function v20SecretNext(){if(state.phase!=='done')return;state.round++;state.setter=v20Other(state.setter);state.secret=null;state.phase='set';state.attempts=0;state.last=null;sync();renderFromState()}
function renderV20Secret(){const me=actor(),setter=state.setter,guesser=v20Other(setter);$('roundPill').textContent=`Раунд ${state.round}`;$('bar').style.width=state.phase==='set'?'30%':state.phase==='guess'?'65%':'100%';let h=`<div class="v20Score"><b>${state.score.host}</b><span>${esc(hostName())} · ${esc(guestName())}</span><b>${state.score.guest}</b></div>`;if(state.phase==='set')h+=me===setter?`<div class="question">Загадай число от 1 до 30</div><div class="guessrow"><input id="v20Secret" type="number" min="1" max="30" placeholder="1–30"><button class="btn" onclick="dispatch('v20_secret_set',Number($('v20Secret').value))">Загадать</button></div>`:`<div class="knowWait"><div class="bigemoji">🤫</div><b>${esc(v20Name(setter))} загадывает число</b></div>`;else if(state.phase==='guess')h+=me===guesser?`<div class="question">Угадай число 1–30</div>${state.last?`<div class="turnBanner">${state.last==='up'?'⬆️ Нужно больше':'⬇️ Нужно меньше'} · попыток ${state.attempts}</div>`:''}<div class="guessrow"><input id="v20Guess" type="number" min="1" max="30" placeholder="Твой вариант"><button class="btn" onclick="dispatch('v20_secret_guess',Number($('v20Guess').value))">Проверить</button></div>`:`<div class="knowWait"><div class="bigemoji">🔐</div><b>${esc(v20Name(guesser))} пытается угадать</b><span>Попыток: ${state.attempts}</span></div>`;else h+=`<div class="result">🎯 ${esc(v20Name(guesser))} угадал(а) число ${state.secret} за ${state.attempts} попыток!</div><div class="actions"><button class="btn" onclick="dispatch('v20_secret_next')">Поменяться ролями</button></div>`;$('gameCard').innerHTML=h}

// Three doors
function v20DoorsNew(){return{screen:'game',type:'doors3',round:1,star:Math.floor(Math.random()*3),choices:{host:null,guest:null},score:{host:0,guest:0},reveal:false,winner:null}}
function v20DoorPick(v,who){if(state.reveal||state.winner||state.choices[who]!=null)return;v=Number(v);if(v<0||v>2)return;state.choices[who]=v;if(state.choices.host!=null&&state.choices.guest!=null){state.reveal=true;if(state.choices.host===state.star)state.score.host++;if(state.choices.guest===state.star)state.score.guest++}sync();renderFromState()}
function v20DoorNext(){if(!state.reveal||state.winner)return;if(state.round>=5){state.winner=state.score.host===state.score.guest?'draw':state.score.host>state.score.guest?'host':'guest'}else{state.round++;state.star=Math.floor(Math.random()*3);state.choices={host:null,guest:null};state.reveal=false}sync();renderFromState()}
function renderV20Doors(){const mine=state.choices[actor()];$('roundPill').textContent=`Раунд ${state.round}/5`;$('bar').style.width=(state.round/5*100)+'%';let h=`<div class="v20Score"><b>${state.score.host}</b><span>${esc(hostName())} · ${esc(guestName())}</span><b>${state.score.guest}</b></div><div class="question">За какой дверью звезда?</div><div class="v20Doors">${[0,1,2].map(i=>`<button ${state.reveal||mine!=null||state.winner?'disabled':''} onclick="dispatch('v20_door',${i})"><span>${state.reveal&&i===state.star?'⭐':'🚪'}</span><small>${i+1}</small></button>`).join('')}</div>`;if(!state.reveal&&mine!=null)h+='<div class="turnBanner">✓ Дверь выбрана. Ждём партнёра…</div>';if(state.reveal)h+=`<div class="v19Reveal"><div><small>${esc(hostName())}</small><b>Дверь ${state.choices.host+1}${state.choices.host===state.star?' ⭐':''}</b></div><div><small>${esc(guestName())}</small><b>Дверь ${state.choices.guest+1}${state.choices.guest===state.star?' ⭐':''}</b></div></div>`;if(state.winner)h+=`<div class="result">${state.winner==='draw'?'🤝 Ничья!':'🏆 '+esc(v20Name(state.winner))+' победил(а)!'}</div><div class="actions"><button class="btn" onclick="dispatch('game','doors3')">Ещё партия</button></div>`;else if(state.reveal)h+=`<div class="actions"><button class="btn" onclick="dispatch('v20_door_next')">${state.round>=5?'Итог':'Следующая дверь'}</button></div>`;$('gameCard').innerHTML=h}

// ---------------- Hook into game engine ----------------
const V20_PREV_APPLY=applyAction,V20_PREV_RENDER=renderGame;
applyAction=function(a,v,who){
 if(a==='game'&&v==='trytogether'){state=v20TryNew();sync();renderFromState();return}
 if(state.type==='trytogether'&&a==='v20_try_consent'){state.consent[who]=!!v;sync();renderFromState();return}
 if(state.type==='trytogether'&&a==='v20_try_answer'&&!state.reveal&&['yes','maybe','no'].includes(v)){state.answers[who]=v;if(state.answers.host&&state.answers.guest)state.reveal=true;sync();renderFromState();return}
 if(state.type==='trytogether'&&a==='v20_try_next'&&state.reveal){const x=state.answers.host,y=state.answers.guest;if(x==='yes'&&y==='yes')state.yesMatches++;else if(x!=='no'&&y!=='no')state.maybeMatches++;state.seen++;state.idx=(state.idx+1+state.seen*3)%V20_TRY_CARDS.length;state.answers={host:null,guest:null};state.reveal=false;sync();renderFromState();return}
 if(a==='game'&&v==='oddone'){state=v20OddNew();sync();renderFromState();return}if(state.type==='oddone'&&a==='v20_odd_pick'){v20OddPick(v,who);return}if(state.type==='oddone'&&a==='v20_odd_next'){v20OddNext();return}
 if(a==='game'&&v==='anagram'){state=v20AnaNew();sync();renderFromState();return}if(state.type==='anagram'&&a==='v20_ana_guess'){v20AnaGuess(v,who);return}if(state.type==='anagram'&&a==='v20_ana_next'){v20AnaNext();return}
 if(a==='game'&&v==='secret30'){state=v20SecretNew();sync();renderFromState();return}if(state.type==='secret30'&&a==='v20_secret_set'){v20SecretSet(v,who);return}if(state.type==='secret30'&&a==='v20_secret_guess'){v20SecretGuess(v,who);return}if(state.type==='secret30'&&a==='v20_secret_next'){v20SecretNext();return}
 if(a==='game'&&v==='doors3'){state=v20DoorsNew();sync();renderFromState();return}if(state.type==='doors3'&&a==='v20_door'){v20DoorPick(v,who);return}if(state.type==='doors3'&&a==='v20_door_next'){v20DoorNext();return}
 V20_PREV_APPLY(a,v,who)
};
renderGame=function(){if(state.type==='trytogether')return renderV20Try();if(state.type==='oddone')return renderV20Odd();if(state.type==='anagram')return renderV20Ana();if(state.type==='secret30')return renderV20Secret();if(state.type==='doors3')return renderV20Doors();return V20_PREV_RENDER()};

if(typeof v19Badge==='function'){const V20_OLD_BADGE=v19Badge;v19Badge=function(id,key){if(id==='trytogether')return'80+ идей · ответы скрыты';if(['oddone','anagram','secret30','doors3'].includes(id))return'новинка v20';return V20_OLD_BADGE(id,key)}}

(function(){if(document.getElementById('v20Style'))return;const s=document.createElement('style');s.id='v20Style';s.textContent=`
.v20TryStats,.v20Score{display:flex;justify-content:center;gap:12px;align-items:center;margin:10px 0 15px;padding:9px 12px;border-radius:15px;background:rgba(255,255,255,.055);font-size:.78rem}.v20TryStats b,.v20Score b{font-size:1.35rem}.v20TryButtons{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:16px 0}.v20TryButtons button{border:1px solid rgba(255,255,255,.1);background:rgba(255,255,255,.07);color:inherit;border-radius:15px;padding:14px 8px;font:inherit;font-weight:800}.v20TryResult{padding:13px;margin:12px 0;border-radius:16px;text-align:center;font-weight:850;background:rgba(255,255,255,.06)}.v20TryResult.hot{background:rgba(255,91,142,.13)}.v20TryResult.soft{background:rgba(181,145,255,.11)}.v20OddGrid{display:grid;grid-template-columns:repeat(7,1fr);gap:5px;margin:14px auto;max-width:520px}.v20OddGrid button{aspect-ratio:1;border:1px solid rgba(255,255,255,.08);background:rgba(255,255,255,.055);border-radius:11px;font-size:23px;padding:0}.v20Letters{display:flex;gap:6px;justify-content:center;flex-wrap:wrap;margin:18px 0}.v20Letters i{font-style:normal;font-weight:900;font-size:1.15rem;min-width:38px;height:44px;display:grid;place-items:center;border-radius:12px;background:rgba(255,255,255,.08);border:1px solid rgba(255,255,255,.1)}.v20Doors{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;max-width:430px;margin:18px auto}.v20Doors button{min-height:130px;border:1px solid rgba(255,255,255,.1);background:rgba(255,255,255,.055);border-radius:20px;color:inherit}.v20Doors span{display:block;font-size:54px}.v20Doors small{display:block;margin-top:7px;font-weight:800}.v20Score span{color:var(--muted);font-size:.75rem}@media(max-width:430px){.v20TryButtons{grid-template-columns:1fr}.v20OddGrid{grid-template-columns:repeat(6,1fr)}.v20OddGrid button{font-size:21px}.v20Doors button{min-height:108px}.v20Doors span{font-size:44px}}
`;document.head.appendChild(s)})();
